### ISSUE TITLE
[typo, bug] detecton vs detection

### ISSUE THREAD

**Issue by cmmoenne** [spyking-circus/spyking-circus#100]
https://github.com/spyking-circus/spyking-circus/blob/e7b3c4125d7d7337d8504a2837582452c71a2d9b/circus/extracting.py#L17

```
configparser.NoSectionError: No section: 'detecton'
```

**Comment by yger** [comment]
Thanks for spotting that. In fact, the extracing mode is not used anymore. If you are using it, let me know any bugs that you may found
