### ISSUE TITLE
Phy output: templates don't match signal in trace view.

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#101]
I am using Spyking circus on a 32 channel array. Each electrode is too far for spikes to be on more than one, so no electrodes are "adjacent" to any others.

After I run and convert to phy's format, I am looking at the trace view. I can see that the spikes are highlighted in the trace view, but it looks like the fit spikes don't match up at all with the trace. 

Take a look here:
![image](https://user-images.githubusercontent.com/1988783/50366984-a1ad9980-0542-11e9-866d-984eed8be642.png)
I'm looking at spikes on channel 9. For some reason, phy still thinks the channels are adjacent to others, so its highlighting the spike's time on multiple traces. The highlights on channels other than 9 seem to match the signal perfectly, but the highlight on channel 9 is different than the underlying raw signal. **What's going on here?**

My first thought was that the highlight was just showing the template (possibly scaled) but that can't be. The signal is too noisy and there isn't even a hint of the spike in  the gray underlying trace. Is it showing the templlate PLUS the underlying signal? Are the spikes subtracted from the underlying signal?

**Comment by holmescharles** [comment]
Ah I see. To be clear, the highlighted traces must be showing the fit spike PLUS the residuals, and the gray trace is JUST the residuals. Is that right?

Thanks for the speedy reply!

On Sat, Dec 22, 2018 at 2:24 AM Pierre Yger <notifications@github.com<mailto:notifications@github.com>> wrote:
I am not sure to understand your problem: what do you mean by "spikes don't
match"? In the traceview, you see in slightly darker gray the residuals
when there is a fitted spikes. So in blue is the spike, and the gray lines
during this spikes are the residuals, i.e. the raw data minus the fitted
spikes. If you watch closely, you'll see that gray levels are different.
And residuals should be close to 0, as we see on your plot.

Do not hesitate if not clear

Le sam. 22 déc. 2018 à 00:10, Chuck Holmes <notifications@github.com<mailto:notifications@github.com>> a
écrit :

**Comment by yger** [comment]
The highlighted trace are the raw data (comprised because a spike has been
detected here, on some channels that are colorcoded arbitrarily by phy).
Just that superimposed in gray (during this portion) are the residuals i.e.
the raw data MINUS the fitted spike. Elsewhere, gray is showing the raw
data, as expected

Pierre

Le sam. 22 déc. 2018 à 19:02, Chuck Holmes <notifications@github.com> a
écrit :

> Ah I see. To be clear, the highlighted traces must be showing the fit
> spike PLUS the residuals, and the gray trace is JUST the residuals. Is that
> right?
>
> Thanks for the speedy reply!
>
> On Sat, Dec 22, 2018 at 2:24 AM Pierre Yger <notifications@github.com

**Comment by holmescharles** [comment]
Thanks for clarifying!

On Sat, Dec 22, 2018 at 12:33 PM Pierre Yger <notifications@github.com<mailto:notifications@github.com>> wrote:
The highlighted trace are the raw data (comprised because a spike has been
detected here, on some channels that are colorcoded arbitrarily by phy).
Just that superimposed in gray (during this portion) are the residuals i.e.
the raw data MINUS the fitted spike. Elsewhere, gray is showing the raw
data, as expected

Pierre

Le sam. 22 déc. 2018 à 19:02, Chuck Holmes <notifications@github.com<mailto:notifications@github.com>> a
écrit :

> Ah I see. To be clear, the highlighted traces must be showing the fit
> spike PLUS the residuals, and the gray trace is JUST the residuals. Is that
> right?
>
> Thanks for the speedy reply!
>
> On Sat, Dec 22, 2018 at 2:24 AM Pierre Yger <notifications@github.com<mailto:notifications@github.com>
