### ISSUE TITLE
Does raw_binary support multi-files?

### ISSUE THREAD

**Issue by jschmiedt** [spyking-circus/spyking-circus#102]
I'm trying to get Spyking Circus to work with our TDT data, which are basically just several binary files with a 40 byte header. Each channel is stored separately in a single file. If I understood the documentation right (https://spyking-circus.readthedocs.io/en/latest/code/fileformat.html), this should be possible with the `raw_binary` format using `stream_mode = ['multi-files']`.
However, when I try to actually start the data loading (Version 0.7.4) I get the error 
```
----------------------------  Error  -----------------------------
| The file format raw_binary does not support stream mode 'multi-files'
------------------------------------------------------------------
```
Am I doing something wrong?

**Comment by jschmiedt** [comment]
The params file looks like the following
```
[data]
file_format    = raw_binary                     
sampling_rate  = 24414.0625
nb_channels    = 24
data_offset    = 40
gain           = 1
data_dtype     = 'int16'
stream_mode    = 'multi-files' 
mapping        = vprobe.prb    
suffix         =                      
overwrite      = True                 
parallel_hdf5  = True               
output_dir     =   
```

**Comment by yger** [comment]
You should remove the quotes in the parameter files:

stream_mode = multi-files

Best

Pierre

Le mer. 2 janv. 2019 à 17:15, Joscha Schmiedt <notifications@github.com> a
écrit :

**Comment by jschmiedt** [comment]
Thanks a lot! I realized now that strings should be without quotes. Is the parameter file in a standardized format such as json or yaml?

**Comment by yger** [comment]
Not really, but you are right, it should be done. Sorry for that

Le jeu. 3 janv. 2019 à 09:31, Joscha Schmiedt <notifications@github.com> a
écrit :
