### ISSUE TITLE
Lower detection threshold leads to worse detection of good clusters.

### ISSUE THREAD

**Issue by Tom-TBT** [spyking-circus/spyking-circus#108]
Hello Pierre,
here is something strange I spotted while I was processing my data. 
I first did the detection for the clusters with a spike_thresh of 7.5. A bit low for my noisy data but I wanted to see if I could get something out of it. But I got this as a result in phy:
![bug_spyking-circus_th7 5](https://user-images.githubusercontent.com/10853316/50973656-b8b02d80-14e9-11e9-9417-244fe9b72973.PNG)
I display here all the clusters See how the two good channels don't have their spikes assigned to a cluster. And all the cluster you see are basically noise.

Then I used a threshold of 10. Here is the result:
![bug_spyking-circus_th10](https://user-images.githubusercontent.com/10853316/50973959-74715d00-14ea-11e9-8f51-49fb25d256f3.PNG)
With that threshold the noise is now mostly discarded (17 clusters against 62 before) **and the two interesting clusters are detected.**

It's strange for me to see that lowering the threshold leads to not detecting anymore the large signals. What do you think? I can send you my data if you want to reproduce and explore the issue.

Thanks!
Tom

**Comment by yger** [comment]
This is not so strange. Keep in mind that the code is estimating the templates from a **subset** of all the spikes in your recording. With default parameters, every electrode will try to collect N=10000 "spikes" (or local threshold crossings), and then independent clusterings are performed. 

So, if you decrease the threshold, assuming that spikes are randomly sampled, then you'll end up collecting lot of noise, and thus the selection of the spikes will not be so good. Therefore, for a low threshold and/or if data are noisy, most of your threshold crossings that are collected may be noise snippets, and not real spikes. As a result, the clustering will be bad, and templates will not be properly estimated. It may be counter-intuitive, but this is a consequence of clustering on a randomly chosen subset of all spikes.

In practice, our smart-search procedure should enhance the selection of the spikes, forcing the code to select non-redundant spikes and thus be more robust to low threshold values, but still, if data are noisy, I would not recommend to decrease too much the threshold.

**Comment by Tom-TBT** [comment]
I see, it makes sense like that. Thanks for clarifying this!
