### ISSUE TITLE
[Feature request] Include data file path in "Informations" print out

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#109]
Spyking circus prints an informative header before it starts up. It would be great if this could indicate which file is being worked on. When running a batch of files, its impossible to know which file (or call) you are currently on without doing the counting yourself. Thanks!

**Comment by yger** [comment]
Good idea too. Done: the file name should now be displayed in the header, in the master branch. Will be propagated to 0.7.6 when I'll do a release

**Comment by holmescharles** [comment]
Great! Glad to help with ideas!

On Thu, Jan 10, 2019 at 11:38 AM Pierre Yger <notifications@github.com<mailto:notifications@github.com>> wrote:

Good idea too. Done: the file name should now be displayed in the header, in the master branch. Will be propagated to 0.7.6 when I'll do a release
