### ISSUE TITLE
'TemplateController' object has no attribute 'channel_order' when lauching latest phy

### ISSUE THREAD

**Issue by mspacek** [spyking-circus/spyking-circus#11]
Cyrille Rossant just made some changes to phy that deal with channel order and labelling:

https://github.com/kwikteam/phy/pull/719

Now, when I try viewing spyking-circus results in phy using `circus-gui-python`, I get `AttributeError: 'TemplateController' object has no attribute 'channel_order'`

**Comment by mspacek** [comment]
Sorry, I forgot to update `phy-contrib` as well. Problem solved.

**Comment by yger** [comment]
Good to know, because I was just about to say that I could not reproduce the error :-) But thanks a lot for keeping my in sync
