### ISSUE TITLE
Clustering failure, concatenation axis must match exactly

### ISSUE THREAD

**Issue by Tom-TBT** [spyking-circus/spyking-circus#112]
Hi Pierre,
I have this frequent error during clustering:

Traceback (most recent call last):
... I removed the whole stack ....
  File "C:\Users\tombo\Anaconda3\envs\circus7.6\lib\site-packages\circus\clustering.py", line 951, in main
    result['data_' + str(ielec)] = numpy.concatenate((result['data_' + str(ielec)], data))
ValueError: all the input array dimensions except for the concatenation axis must match exactly

I Checked the dimensions of **result['data_' str(ielec)]** and **data** and I have something like that:
result['data_ielec'].shape:   (0, 5)     data.shape: (2, 2) 

For the problematic channels, shape[1] is always equal to shape[0]. I guess that data are missing for those channels. Shouldn't they be put aside automatically in this case?

**I'm using spyking-circus  0.7.6 and numpy 1.12.1**
Let me know if you need me to run more tests or give you more info

Many thanks,
Tom

**Comment by yger** [comment]
Thanks for spotting that. I'll fix this asap next week, as it may be
related to not enough spikes on some channels

Best

Pierre

Le mar. 19 févr. 2019 à 15:20, Tom Boissonnet <notifications@github.com> a
écrit :

**Comment by yger** [comment]
I'm not sure to be able to reproduce the error. If the data are not too large, could you please share some with me (probe file, params file, and binary)?

**Comment by Tom-TBT** [comment]
Hi Pierre,
I made the data available so you can get it with this link (expires the 31/03/2019):
https://oc.embl.de/index.php/s/IC02P0eAWeM171P

Tell me if it works or if you need something more.

Bests,
Tom

**Comment by yger** [comment]
Ok, I was able to reproduce the problem, and this should be patched in the master branch. This happened only when a very small number of spikes is found, on a given electrode, during the smart search step.

**Comment by Tom-TBT** [comment]
Thank you Pierre for the support!

**Comment by yger** [comment]
By the way, in your data, why setting the threshold so high to 9? You could decrease it I guess, and bring it back to normal values such as 6/7. Because currently, I can see that you are missing spikes

**Comment by Tom-TBT** [comment]
Hi Pierre,
Yeah it's a high treshold indeed. I have sometimes noisy data so I try the sorting with it from time to time. In general I use a lower threshold. In any case this bug fix will be useful when there is a small number of spikes per channel.

Thanks!
