### ISSUE TITLE
Merging step fails on cluster, requires GUI

### ISSUE THREAD

**Issue by shashwatsridhar** [spyking-circus/spyking-circus#120]
Hello,

I sort data using Spyking Circus on a cluster. All steps until the fitting work fine, but the automatic merging step fails with the following error:

```
| Step "merging" failed for reason Command '['mpiexec', '-np', '24', 'spyking-circus-subtask', 'merging', '/tmp/i140703-001/i140703-001.dat', '24', '0', 'False', 'None']' returned non-zero exit status 1.!
```
My error file also shows this:
```
: cannot connect to X server
```
My guess is this happens because Spyking Circus attempts to launch the GUI, but it can't because the nodes on my cluster don't have an X server running on them.

Is there a workaround to this? Can I somehow call the merging step without invoking the GUI?

Thanks!

**Comment by yger** [comment]
Yes, you can skip the GUI, by setting a value in the auto_mode field of the
[merging] section in the parameter file. I think this should work. However,
note that this value (that could be 1 by default) should be a bit tailored
for your data, and this is why this step is not yet included in the default
pipeline

Best

Pierre

Le mer. 10 avr. 2019 à 12:43, Shashwat Sridhar <notifications@github.com> a
écrit :

**Comment by shashwatsridhar** [comment]
Hey Pierre,
Thanks for the quick reply!

I am not sure if this works.

When i try this out on my laptop (not on the cluster), a black GUI window appears during the merging step. Nothing is displayed in the window and the window silently disappears when the merging step is over.

When running this on the cluster, the merging step fails with this error.

```
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 19501 RUNNING AT blaustein26
=   EXIT CODE: 6
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
----------------------------  Error  -----------------------------
| Step "merging" failed for reason Command '['mpiexec', '-f', '/tmp/i140703-001/i140703-001.hosts', '-np', '24', 'spyking-circus-subtask', 'merging', '/tmp/i140703-001/i140703-001.dat', '24', '0', 'False', 'None']' returned non-zero exit status 6.!
------------------------------------------------------------------
QXcbConnection: Could not connect to display
```

Any clue what could be done? Do you need more info to debug this?

**Comment by yger** [comment]
Indeed, you are right, the Qt app still need to be created even if not displayed. I'll try to make a fix soon

**Comment by shashwatsridhar** [comment]
Thank you, that would be great :)

**Comment by yger** [comment]
This has been implemented in the master branch. Will be part of 0.8.1
