### ISSUE TITLE
Dimension and data type for raw binary input

### ISSUE THREAD

**Issue by hangletn** [spyking-circus/spyking-circus#138]
Hello, thank you for creating Spyking Circus! This sorter is amazing. I'm trying to convert my data from Blackrock to .dat file for Spyking Circus to read as a raw binary file, and I run into some confusion. First, I'm not sure which data type I should save my .dat file as so that it's compatible with Spyking circus. I've tried int16, but would love to hear your suggestion. Second, I'm converting my data to a matrix in the .dat file but not sure which kind of dimension would fit for Spyking Circus. Should I save my data as a mxn matrix with m channels and n timepoints, or a nxm matrix with n timepoints and m channels? Would really appreciate your response. Thank you very much!

**Comment by hangletn** [comment]
Hello, I just figured out that I'm suppose to set the data type in the params file so maybe that solve the problem with data type. I'm still not really sure about the dimension. Thanks!

**Comment by yger** [comment]
The data dtype has to be specified by the user (you need to know how the data have been saved). Similarly, the number of dimensions (i.e. the number of channels recorded in the file) need also to be specified (in the probe file, with the parameter total_nb_channels)
