### ISSUE TITLE
software stops to work after clustering

### ISSUE THREAD

**Issue by sronchi** [spyking-circus/spyking-circus#140]
Hi, 

I installed Spyking Circus 0.8.3 in my home folder, after installing miniconda3 and the software itself through conda.
After pre-processing my data, the Spyking Circus software starts, but it shows the following error after the clustering step (1/3).

_Traceback (most recent call last):
  File "/home/sronchi/miniconda3/bin/spyking-circus-subtask", line 11, in <module>
  File "/home/sronchi/miniconda3/lib/python3.7/site-packages/circus/scripts/subtask.py", line 43, in main
  File "/home/sronchi/miniconda3/lib/python3.7/site-packages/circus/__init__.py", line 21, in launch
  File "/home/sronchi/miniconda3/lib/python3.7/site-packages/circus/clustering.py", line 696, in main
IndexError: index 10 is out of bounds for axis 1 with size 10_

I wanted to kindly ask you if you have some ideas on the kind of problem I might have. The same pre-processed file was analysed by the software without any problem for other colleagues, so I think that something went wrong with the installation.

I thank you for your time and for considering my issue.

Silvia Ronchi

**Comment by yger** [comment]
No, I guess it might then be a bug in 0.8.3. My bad. Can you try with 0.8.2
and see if this is working? It should, as I refactored the aforementioned
lines in 0.8.3, and clearly, I may not have covered all use cases. If your
files are not too large, can you send them to me?

Best

Pierre

**Comment by yger** [comment]
Otherwise, I just pushed a patch in the master branch: can you try to update the software and tell me if this is fixed (assumnin you know how to install the latest version from git master branch, otherwise let me know)

**Comment by sronchi** [comment]
I just installed the version 0.8.2 and it worked. Thank you very much for your time and help!

**Comment by yger** [comment]
If you do have time, let me know if this is also working with 0.8.4 (from
master). At least I would know if the patch I made is good. So from a
terminal, simply do

>> pip install
https://github.com/spyking-circus/spyking-circus/master/archive.zip
--upgrade

You should see 0.8.4 in the version number (and you can revert if not
working)

**Comment by sronchi** [comment]
Hi,
I will try it as soon as possible and let you know. I was and still am a bit busy at work, but I will contact you when I know whether it works. Sorry for the delay.

**Comment by takahashikazutaka** [comment]
Actually I got the same issue by running 0.8.3 and the master link above to upgrade is not active any more. Can you post it again please?
