### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#143]
I have set up Miniconda (linux; 64 bit) and created a new environment with python 3.6.

I have installed spyking circus with:
`conda install -c conda-forge -c anaconda -c spyking-circus spyking-circus`

When I try to run spyking circus, it tells me "colorama" is not installed.

I have no problem installing the dependencies, but I am wondering if A) the dependencies should install with spyking circus and, if so, B) why aren't then installing and does this suggest another issue if they are not.

Thanks,
Chuck

**Comment by yger** [comment]
Strange, as colorama is a required dependency both in setup.py and in conda_recipe/meta.yaml. Thanks for reporting, I'll look into that. If you install it manually, then the software works?

**Comment by holmescharles** [comment]
It seems to work so far. I'll report any issues as they come.
I also had to install joblib and cycler manually. I installed all 3 with conda.

**Comment by yger** [comment]
joblib and cycler are related to phy, and not required per se by SpyKING CIRCUS. I'll have a look at the conda pacakges, but so far on travis and appveyor evertyhing seems to work.
