### ISSUE TITLE
Automatic solving of dependency to `sip` module

### ISSUE THREAD

**Issue by wuffi** [spyking-circus/spyking-circus#148]
Thanks for making _Spyking Circus_ available!
First tests with the program worked very well.

Just 1 very small issue:

Trying to run the Python preview GUI gave me `ImportError: No module named sip`, which is of course easy to fix manually with `conda install -c anaconda sip`.
For people not familiar with Python, it could be helpful to add the `sip` module to solve the dependency automatically.

**Comment by yger** [comment]
Currently travelling, I'll deal with this issue end of August. But thanks for reporting!
