### ISSUE TITLE
Probe channel order

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#149]
I have been experiencing some non-intuitive behavior when working with channel order.
I am using a 32 channel semi-chronic drive from Graymatter Research, which I mate with an INTAN headstage. The channel orders do no match up exactly, so channels 1, 2, 3, 4, ... on the graymatter drive correspond to channels 7, 8, 6, 9, ... on the INTAN board. My data are saved in INTAN channel order, but I prefer to think in terms of the Graymatter channel order.
As additional information, the INTAN board collects 3 auxillary channels which I don't care about (making it 35 channel total) and I have broken about half of the channels (forgive me).

Here is my probe:
```
# SC32 Graymatter drive
total_nb_channels = 35
radius = 100

SC32_GEOMETRY = (
                [1, 5], [2, 5], [3, 5], [4, 5], [5, 5],
                [1, 4], [2, 4], [3, 4], [4, 4], [5, 4],
        [0, 3], [1, 3], [2, 3], [3, 3], [4, 3], [5, 3],
        [0, 2], [1, 2], [2, 2], [3, 2], [4, 2], [5, 2],
                [1, 1], [2, 1], [3, 1], [4, 1], [5, 1],
                [1, 0], [2, 0], [3, 0], [4, 0], [5, 0])

SC32_TO_INTAN = (
        # 32 drive channels
              7,  8,  6,  9,  5,
             10,  4, 11,  3, 12,
          2, 13,  1, 14,  0, 15,
         31, 16, 30, 17, 29, 18,
             28, 19, 27, 20, 26,
             21, 25, 22, 24, 23,
        # Auxillary channels
             32, 33, 34)

CHANNELS = [1, 2, 4, 5, 6, 8, 11, 16, 20, 21, 23, 25, 26, 28, 29, 32]
CHANNELS.sort(key=lambda x: SC32_TO_INTAN[x-1])  #***
channel_groups = {
        x: {'channels': [SC32_TO_INTAN[x - 1]],
            'graph': [],
            'geometry': {SC32_TO_INTAN[x - 1]: SC32_GEOMETRY[x - 1]}}
        for x in CHANNELS}
```

When I originally tried working with the data, I did not include the like marked with "***", and the waveforms on the channel (in the preview gui) would not be where I expected them to be (I had 2 channels with clear spikes that were in the wrong places). However, when I include the aforementioned line, they are in the right place. For some reason it seems that the channel groups must be made in the same order as they appear in the data file, at least for the preview gui. Why is this?

I have not yet tested whether this affects spike sorting in any way (its conceivable that the sorting algorithm will interpret the channels correctly even if they are not in the "right" order).

Anyways, this behavior is concerning to me since since it seems to be another layer of "something I can mess up". Furthermore, python dictionaries are supposed to be orderless, so if anything were to jumble to order in memory, it could mess up the program. Would it be possible to fix this so that order does not matter? I will look at the code myself, but I am quite unfamiliar with it and might not be able to figure it out nearly as fast as someone else.

Thanks,
Chuck

**Comment by holmescharles** [comment]
This issue seems to be isolated to the preview GUI.
I ran spyking circus on two copied of my data. The only difference was that in one version (sorted), in included the line in the original post's code block with the "***" mark and in the other version (unsorted) I did not. Aside from slight difference that would be expected from the random elements of the sorting algorithm, the outputs seems identical and phy correctly picks the waveforms from the right channel.

For now, I will just use the sorted version so I can use the preview gui, but it might be more robust if the order-dependency could be fixed.

Thanks!

**Comment by yger** [comment]
Currently travelling, I'll deal with this issue end of August. But thanks for reporting!

**Comment by yger** [comment]
Trying to catch up with this problem, and to understand what is the issue. Why are you creating so many channel groups? In the .prb, a channel group is a shank and/or a group of channel that are nearby in space (modulo the radius issue). But here, you are creating one channel group per channel in your example code?

**Comment by holmescharles** [comment]
Each channel is on its own shank. These are individual electrodes in a 32-electrode semichronic array (https://www.graymatter-research.com/32-channel-microdrive-system-sc32/).

For multiple shanks, the spyking circus docs suggest either using separate channel groups or using a small radius value. I arbitrarily chose the former. Is there an advantage to using the latter?

**Comment by yger** [comment]
No, I was just wondering as I'm always going for the low radius solution. I'll try to make a patch for this behavior asap

**Comment by holmescharles** [comment]
Ah, I just remembered. The other reason I use multiple channel groups is because my "channel order" (the order in which I would prefer to think of the channels) is different from their order in the data. This is because of the mismatch in channel order between my microdrive and the INTAN headstage I use.

For example, channel (shank) 1 is actual the 8th channel in the data file. You can see the full order conversion in the probe file above.
I don't think there's a great way to handle this if I put them all in the same channel group.

Additionally, I use phy as my GUI, and this seems to interpret the channel group as the shank id the way I'd like to. It uses the data-file-order index as the channel id, but that's alright as long as the shanks are right. I haven't tried it, but my hunch is that if I put them all in the same channel group, then it would say they all had the same shank id and keep the data-file-order as their channel id.

**Comment by yger** [comment]
I've merged the ordering branch into master, everything seems to be working so far
