### ISSUE TITLE
34 Errors while executing the test suite

### ISSUE THREAD

**Issue by TheChymera** [spyking-circus/spyking-circus#165]
I am trying to package your software for Gentoo Linux. Installing and testing the package I get the following errors [build.log](https://github.com/spyking-circus/spyking-circus/files/3694849/build.log).

It also appears that the software depends on CUDA. Is that true? That would significantly limit the systems on which it can run. Is there any way to avoid this?

These are the dependencies I could extract from your `setup.py`:

```
RDEPEND="
	dev-python/mpi4py[${PYTHON_USEDEP}]
	dev-python/numpy[${PYTHON_USEDEP}]
	dev-python/cython[${PYTHON_USEDEP}]
	sci-libs/scipy[${PYTHON_USEDEP}]
	dev-python/matplotlib[${PYTHON_USEDEP}]
	dev-python/h5py[${PYTHON_USEDEP}]
	dev-python/colorama[${PYTHON_USEDEP}]
	dev-python/psutil[${PYTHON_USEDEP}]
	dev-python/tqdm[${PYTHON_USEDEP}]
	dev-python/blosc[${PYTHON_USEDEP}]
	dev-python/statsmodels[${PYTHON_USEDEP}]
	sci-libs/scikits_learn[${PYTHON_USEDEP}]
"
DEPEND="
	dev-python/setuptools[${PYTHON_USEDEP}]
"
```

**Comment by yger** [comment]
Both the cuda support and test suite are deprecated... So the software can
run without cuda, and (sadly) without a proper testsuite. Making new tests
is on the to do list

Le dim. 6 oct. 2019 à 22:54, Horea Christian <notifications@github.com> a
écrit :
