### ISSUE TITLE
Auto-generated params

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#171]
Just an FYI, the parameters file generated automatically (if you don't already have one) does not seem to be up to date. Its missing the merge_method parameter.

**Comment by yger** [comment]
Thanks for spotting that. Did you install recent versions with conda or pip?

**Comment by holmescharles** [comment]
I installed from the source.

**Comment by holmescharles** [comment]
I'm not sure this was fixed. I just did a git pull and I still don't see the merge_method parameter in the auto-generated file.

**Comment by yger** [comment]
Thanks for pointing that. This will be fixed in 0.8.7 asap
