### ISSUE TITLE
Question: What is the max file size, and can it sort channels independently?

### ISSUE THREAD

**Issue by yitongqi** [spyking-circus/spyking-circus#186]
General question:
1. What is the largest possible file size it can handle?
2. Can it sort channels independently without spatial information?

**Comment by yger** [comment]
1. There is no limit to the file size, but the longer the recording, the more problematic drifts might be. Recordings of up to 10h have been sorted without problems, and if you have very stable recordings, you can go for more
2. Yes, just set the spatial support accordingly (with a radius set to 0)

**Comment by yitongqi** [comment]
Thank you!
