### ISSUE TITLE
[Feature request] Peaks by channel

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#195]
I record with 32 channels. Usually, units have negative peaks, but seldomly, a unit will have a positive peak. I don't want to sort all of my channels with positive and negative peaks (I think this will generate too much junk). Could there be a way to pick which channels have positive peaks and which have negative?
I am imagining two lists, one for positive and one for negative. Then, you can list all the channels that have negative peaks in the former and all the channels that have positive peaks in the latter. If a channel appears in both lists, this could replicate the "both" peaks functionality.

**Comment by yger** [comment]
Well, this won't be very easy to implement internally, but I'll have a look. I guess meanwhile, the best is to use "both", at the cost of removing some templates at the end

**Comment by holmescharles** [comment]
If "both" is used, does that run the risk of splitting what should be a single cluster into two clusters?

On Fri, Jan 3, 2020 at 3:16 AM Pierre Yger <notifications@github.com<mailto:notifications@github.com>> wrote:

Well, this won't be very easy to implement internally, but I'll have a look. I guess meanwhile, the best is to use "both", at the cost of removing some templates at the end

**Comment by yger** [comment]
It could, but this is unlikely. Templates that would have both a positive and a negative peak will be found twice by the algorithms, but because they are the same up to a translation, they should be merged internally, so you should not have twice more templates

**Comment by holmescharles** [comment]
I see. Then things should be fine as is. I was mostly worried about mis-interpretation of the data.

On Tue, Jan 7, 2020 at 4:03 AM Pierre Yger <notifications@github.com<mailto:notifications@github.com>> wrote:

It could, but this is unlikely. Templates that would have both a positive and a negative peak will be found twice by the algorithms, but because they are the same up to a translation, they should be merged internally, so you should not have twice more templates
