### ISSUE TITLE
Automating the Meta-Merging GUI

### ISSUE THREAD

**Issue by brimcr** [spyking-circus/spyking-circus#197]
Thank you for this program, it has been very useful. In particular, we appreciate the addition of the Meta-Merging GUI. However, we have struggled to find a way to automate this manual selection of template pairs to merge and templates to delete. Is there a way to automatically do this such that we can let our analysis run overnight without the need to manually click on features in the Meta-Merging GUI? As of right now, we always reject the suggested merges (our probes are not dense enough to merge across channels) and delete the suggested false templates. Thank you.

**Comment by yger** [comment]
In fact, you just need to put a value in the [merging] section for the parameter auto_mode (default is 0.75). If a value is present, the GUI will not open. If, from what I understand, you only want to delete wrong templates and not do any merges, then put auto_mode = 1 (it will prevent merges).

**Comment by brimcr** [comment]
Thank you for your reply! Just to clarify, setting auto_mode = 1 will also delete the suggested false templates? Or does this only prevent merges?

**Comment by yger** [comment]
Yes, auto_mode = 1 will just prevent any merges. It will still remove noise if you have set remove_noise to True in the same section of the .params file

**Comment by brimcr** [comment]
I see, thank you so much!!
