### ISSUE TITLE
Installation error when installing `blosc`

### ISSUE THREAD

**Issue by alejoe91** [spyking-circus/spyking-circus#199]
Hei @yger 

Got this error when installing SC 0.9.0:

```
Collecting blosc
  Using cached blosc-1.8.3.tar.gz (809 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/alessio/.virtualenvs/expipe/bin/python3.6 /home/alessio/.virtualenvs/expipe/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nz2w1li8/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake ninja
       cwd: None
  Complete output (21 lines):
  Collecting setuptools
    Using cached setuptools-45.1.0-py3-none-any.whl (583 kB)
  Collecting wheel
    Using cached wheel-0.33.6-py2.py3-none-any.whl (21 kB)
  Collecting scikit-build
    Using cached scikit_build-0.10.0-py2.py3-none-any.whl (66 kB)
  Collecting cmake
    Using cached cmake-3.13.3-cp36-cp36m-manylinux1_x86_64.whl (15.9 MB)
  Collecting ninja
    Using cached ninja-1.9.0.post1.tar.gz (25 kB)
      ERROR: Command errored out with exit status 1:
       command: /home/alessio/.virtualenvs/expipe/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h6ti0t_t/ninja/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h6ti0t_t/ninja/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-h6ti0t_t/ninja/pip-egg-info
           cwd: /tmp/pip-install-h6ti0t_t/ninja/
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-h6ti0t_t/ninja/setup.py", line 7, in <module>
          from skbuild import setup
      ModuleNotFoundError: No module named 'skbuild'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/alessio/.virtualenvs/expipe/bin/python3.6 /home/alessio/.virtualenvs/expipe/lib/python3.6/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-nz2w1li8/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel scikit-build cmake ninja Check the logs for full command output.
```

A workaround was installing `scikit-build` and `cmake` before `blosc`:
`pip install scikit-build cmake`
`pip install blosc`

Anyone else had this issue?

**Comment by alejoe91** [comment]
@yger keep having this issue on windows, linux, and mac. Maybe you could add `scikit-build` and `cmake` to the requirements?

**Comment by yger** [comment]
Hum.... Weird, I don't see it, and the conda build are also done automatically on appveyor/travis without errors. I'll check that asap. You are installing from sources?

**Comment by yger** [comment]
I'll try to see if I can reproduce, and patch that and make a new release anyway: i'm still digging into the code to optimize as much as possible in order to be faster. Goal is to be finished for 1.0 release. Almost there!

**Comment by alejoe91** [comment]
I'm just running this:
```
sudo apt install libmpich-dev
pip install mpi4py
pip install spyking-circus --no-binary=mpi4py
```

**Comment by alejoe91** [comment]
do you recommend installing using conda?

**Comment by yger** [comment]
Most of the users are using it, but I'm not, and I never encountered the errors. I'll try to reproduce it and add the dependencies if needed, thanks for the hint

**Comment by alejoe91** [comment]
@yger after some debugging and digging I found it: I didn't have Cmake command line tools installed. Maybe you could just add that to the docs (this is for MacOS - I had to install CMake and add the binaries to the PATH)

**Comment by yger** [comment]
Ah ok, good to know. I'll add that to the docs. But you said you had the issue with windows, linux, and mac, no?

**Comment by alejoe91** [comment]
On Linux I fixed it by pip installing cmake and scikit-build. I can try to reproduce on a brand new environment. Same for windows (but that was probably related to missing build tools). I don't have a Windows machine at the moment but I'll ask someone else to test it.

**Comment by kurobaneHITOMI** [comment]
Emmmmm... I had this error in win10 when installing blosc using `pip install spyking-circus`. Here's the full report.
`Building wheels for collected packages: blosc
  Building wheel for blosc (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\ANACONDA3\envs\neuro\python.exe' 'D:\ANACONDA3\envs\neuro\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\10937\AppData\Local\Temp\tmprlmp07at'
       cwd: C:\Users\10937\AppData\Local\Temp\pip-install-74z9e5vg\blosc
  Complete output (162 lines):
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    No CMAKE_C_COMPILER could be found.

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/10937/AppData/Local/Temp/pip-install-74z9e5vg/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/10937/AppData/Local/Temp/pip-install-74z9e5vg/blosc/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  Not searching for unused variables given on the command line.
  CMake Error at CMakeLists.txt:2 (PROJECT):
    Generator

      Visual Studio 15 2017 Win64

    could not find any instance of Visual Studio.



  -- Configuring incomplete, errors occurred!
  See also "C:/Users/10937/AppData/Local/Temp/pip-install-74z9e5vg/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the NMake generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/10937/AppData/Local/Temp/pip-install-74z9e5vg/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/10937/AppData/Local/Temp/pip-install-74z9e5vg/blosc/_cmake_test_compile/build/CMakeFiles/CMakeError.log".
  Not searching for unused variables given on the command line.
  -- The C compiler identification is unknown
  CMake Error at CMakeLists.txt:3 (ENABLE_LANGUAGE):
    The CMAKE_C_COMPILER:

      cl

    is not a full path and was not found in the PATH.

    To use the JOM generator with Visual C++, cmake must be run from a shell
    that can use the compiler cl from the command line.  This environment is
    unable to invoke the cl compiler.  To fix this problem, run cmake from the
    Visual Studio Command Prompt (vcvarsall.bat).

    Tell CMake where to find the compiler by setting either the environment
    variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
    the compiler, or to the compiler name if it is in the PATH.


  -- Configuring incomplete, errors occurred!
  See also "C:/Users/10937/AppData/Local/Temp/pip-install-74z9e5vg/blosc/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/10937/AppData/Local/Temp/pip-install-74z9e5vg/blosc/_cmake_test_compile/build/CMakeFiles/CMakeError.log".


  --------------------------------------------------------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Ninja (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "Visual Studio 15 2017 Win64 v141" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "Visual Studio 15 2017 Win64 v141" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------



  --------------------------------------------------------------------------------
  -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator
  --------------------------------
  ---------------------------
  ----------------------
  -----------------
  ------------
  -------
  --
  --
  -------
  ------------
  -----------------
  ----------------------
  ---------------------------
  --------------------------------
  -- Trying "NMake Makefiles JOM (Visual Studio 15 2017 Win64 v141)" generator - failure
  --------------------------------------------------------------------------------

  ********************************************************************************
  scikit-build could not get a working generator for your system. Aborting build.

  Building windows wheels for Python 3.7 requires Microsoft Visual Studio 2017.
  Get it with "Visual Studio 2017":

    https://visualstudio.microsoft.com/vs/

  ********************************************************************************
  ----------------------------------------
  ERROR: Failed building wheel for blosc
Failed to build blosc
ERROR: Could not build wheels for blosc which use PEP 517 and cannot be installed directly`

I had used pip install cmake scikit-build. It seems I had not install vs2017 so I installed it, but the error still occurs. I would like to know what should I do?

**Comment by yger** [comment]
As said before, doing

pip install scikit-build cmake

Is not helping ?

**Comment by kurobaneHITOMI** [comment]
yeah I had used pip install cmake scikit-build. It seems I had not install vs2017 so I installed it too. But it doesnot help at all

**Comment by alejoe91** [comment]
Can you try to install [CMake](https://cmake.org/download/) as well?

**Comment by kurobaneHITOMI** [comment]
I installed cmake-3.17.0-rc3, but same still...

**Comment by alejoe91** [comment]
did you restart the terminal after installing visual studio and cmake?

**Comment by kurobaneHITOMI** [comment]
yes i did

**Comment by yger** [comment]
Humm.. I'll try to have a look tomorrow, but no guarantee, work is
complicated these days in France. Otherwise, try to use conda, this should
work

**Comment by larsemillarsen** [comment]
Perhaps a bit of a random fix, but I used to have the same error but fixed it by running 'conda install python-blosc' prior to installing spyking-circus.
