### ISSUE TITLE
`amp_limits` units

### ISSUE THREAD

**Issue by SaraMati** [spyking-circus/spyking-circus#200]
what is the scale and unit of the amp_limits parameter in the parameter file?

the params file I've been using is the one that came with the test data silico_0.params and in there the amp_limits = (0.3, 5) 

but in the current version of the [parameter configuration instruction](https://spyking-circus.readthedocs.io/en/latest/code/config.html#fitting) is (0.3, 30) 
I'd be better able to choose what is suitable for me if I know the units. is it in percentage of the template of the cluster? e.g. amplitude up to 30% of the template amplitude are accepted?

**Comment by yger** [comment]
This parameter is not used by default, as long as you have amp_auto set to True (default). This is only if you want to bypass the custom boundaries detected by the clustering
