### ISSUE TITLE
CircusParser and phy

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#207]
My data processing pipeline includes exporting data to Phy and merging clusters with that GUI. Is CircusParser able to access those cluster IDs or is it only able to access the original cluster IDs assigned by SpykingCircus?

Thanks!

**Comment by yger** [comment]
Sadly no. As soon as you convert your data to phy, and start using it, then you have to stick to it... However, we do have an experimental option called "deconverting" that you can try (using -m deconverting). The purpose of such a function is to bring back the phy data into the native SC format, such that there, maybe, the CircusParser function can work. But it has to be tested

**Comment by holmescharles** [comment]
Gotcha! Is there any reason to not just work with the Spyking circus matlab GUI then? Is there anything that Phy does exceptionally better? If not, perhaps its easier to just stay in Spyking Circus land.

**Comment by holmescharles** [comment]
I've decided to switch away from phy for now. Closing the issue. Thanks.
