### ISSUE TITLE
artifact timing proposal

### ISSUE THREAD

**Issue by c-wilson** [spyking-circus/spyking-circus#21]
I'd like to propose that we add a feature to allow the artifact times to be expressed in samples instead of msec. I think this is probably going to be more precise and, in my case, just as convenient. We're extracting our stimulation times from TTLs on our physiology acquisition system. It is super easy to just use these numbers in samples. I'm a bit concerned that rounding errors _might_ actually introduce problems when converting to msec.

Let me know, I can do a pull request if you agree!

**Comment by yger** [comment]
Sure, I agree that this would make much more sense. Go ahead if you want to
try a PR, otherwise I can do that. The only file to modify is filtering.py
I think

Best

Pierre

Le lun. 20 févr. 2017 à 00:24, Chris Wilson <notifications@github.com> a
écrit :

**Comment by yger** [comment]
I created a branch trig_unit where you can specify the unit of the trig times (either in ms or in timesteps). As soon as I'll done some tests, I'll merge that.

**Comment by yger** [comment]
I merged the branch, now you have the trig_unit option in the [triggers] section that is by default set to 'ms' but can be changed to 'timestep'. If so, then all times (artefacts and duration) should be given in timestep. In a near future, the default may be to switch to timestep, but for the time being, it left the default value to ms
