### ISSUE TITLE
Update params file [noedits] after completion

### ISSUE THREAD

**Issue by stephenwhitmarsh** [spyking-circus/spyking-circus#211]
Very small suggestion; 

Change the flags in [noedits] to TRUE only after successful completion.

Context:
If the filtering section breaks due to an error (e.g. not enough diskspace), no file is created, but the [noedits] section has already been set to TRUE, so that restarting will given an error (params file says that there is a filtered file, but there is not).

**Comment by yger** [comment]
This should already be the case, at least when overwrite is set to True. But I guess this is not your case here, so I'll double check as soon as our work with optimal amplitudes is done

**Comment by stephenwhitmarsh** [comment]
Ah, no, overwrite is not set to TRUE in my case (a new .dat file is
created, but then aborted). So that might be the issue.
In any case, it's just a small thing, so no worries.

Op vr 14 feb. 2020 om 16:13 schreef Pierre Yger <notifications@github.com>:
