### ISSUE TITLE
Getting "[WinError 2] The system cannot find the file specified" when trying to run the program and not sure how to proceed

### ISSUE THREAD

**Issue by ArchmageIlmryn** [spyking-circus/spyking-circus#223]
Hello,

(Sorry if this is a stupid question, my python knowledge is minimal) I've installed spyking-circus following the instructions on the website (am using anaconda with python 3.6 on win10), but when I attempt to run it on a (HDL5) file i get the error "[WinError 2] The system cannot find the file specified" immediately after the starting info is displayed, with the following traceback:

`  File "C:\Users\MEA\Anaconda3\envs\circus\Scripts\spyking-circus-script.py", line 11, in <module> load_entry_point('spyking-circus==0.9.2', 'console_scripts', 'spyking-circus')()`

  `File "C:\Users\MEA\Anaconda3\envs\circus\lib\site-packages\circus\scripts\launch.py", line 428, in main subprocess.check_call(mpi_args)`

  `File "C:\Users\MEA\Anaconda3\envs\circus\lib\subprocess.py", line 306, in check_call
    retcode = call(*popenargs, **kwargs)`

  `File "C:\Users\MEA\Anaconda3\envs\circus\lib\subprocess.py", line 287, in call
    with Popen(*popenargs, **kwargs) as p:`

  `File "C:\Users\MEA\Anaconda3\envs\circus\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)`

  `File "C:\Users\MEA\Anaconda3\envs\circus\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)`

`FileNotFoundError: [WinError 2] The system cannot find the file specified`

I at this point have no idea what the missing file is or where to check for it, any help is appreciated.

Thanks!

**Comment by yger** [comment]
MPI is installed? Because this looks like an installation error. But sadly,
I don't know enough to help. You tried to launch the program with the
command line? Did it manage to create a parameter file, or a log file?

Le mar. 3 mars 2020 à 14:22, ArchmageIlmryn <notifications@github.com> a
écrit :

**Comment by ArchmageIlmryn** [comment]
MPI is installed and added to path (that seems to have been done automatically when it installed. I'm not 100% it's set correctly but it seems to match the installation instructions:

<img width="442" alt="pathSetting" src="https://user-images.githubusercontent.com/61742277/75780465-b3e8b180-5d5b-11ea-858e-1e8a8a52d3c9.png">


I launched the program with the Anaconda prompt, it created a parameter file the first time I ran it. When running it again with the filled-out parameter file I ran into this problem, it happened after the initial "Informations" display. Where would I find log files if it created one?

**Comment by yger** [comment]
Next to the file, there should be a .log file. Can you send me the .params
at least, if no .log is around?

Le mar. 3 mars 2020 à 14:34, ArchmageIlmryn <notifications@github.com> a
écrit :

**Comment by ArchmageIlmryn** [comment]
Here is the .params file (had to change it to a .txt to upload it), as far as I can tell there is no .log file in the directory with the data + param files, so unless they default to being placed somewhere else there doesn't seem to be one. 

[2020-02-28T14-19-02WT-PN71-exp1.params.txt](https://github.com/spyking-circus/spyking-circus/files/4281549/2020-02-28T14-19-02WT-PN71-exp1.params.txt)

**Comment by ArchmageIlmryn** [comment]
A second reboot of my computer seems to have resolved it, thanks for the help and sorry to take up your time!
