### ISSUE TITLE
Python GUI and launcher fail with no error message

### ISSUE THREAD

**Issue by ArchmageIlmryn** [spyking-circus/spyking-circus#224]
Hello and sorry to bother you again,

The program works with the command prompt and MATLAB GUI, however when I try to run the python gui or spyking-circus-launcher nothing happens. There is no message displayed in the command prompt, the command simply seems to not do anything (the windows loading icon on the mouse cursor briefly displays, but that's it). I've installed via Anaconda on windows 10, and I have installed phy via the instructions here: https://spyking-circus.readthedocs.io/en/latest/GUI/launching.html

<img width="675" alt="GUIfail" src="https://user-images.githubusercontent.com/61742277/75787403-f6fc5200-5d66-11ea-91fb-986d0858eb01.png">

I haven't been able to find any log files either, I'm unsure in which directory they would end up being saved.

Thanks in advance for any help!

**Comment by yger** [comment]
Is phy installed in the same env as spyking-circus ? If so, then the
command circus-gui-python should work if data have been converted with the
converting step. For the matlab GUI, you need to be sure that Matlab is in
the path.
The log file should be next to your datafile, with the name my data.log
The preview or the result GUI are working?
(spyking-circus mydata.dat -r or -p)

Le mar. 3 mars 2020 à 15:56, ArchmageIlmryn <notifications@github.com> a
écrit :

**Comment by ArchmageIlmryn** [comment]
[2020-02-28T14-19-02WT-PN71-exp1.log](https://github.com/spyking-circus/spyking-circus/files/4287183/2020-02-28T14-19-02WT-PN71-exp1.log)

I found the .log file, but as far as I can tell it only contains logs of when I ran the algorithm in the command line.

The matlab GUI works fine, it's just the GUI launcher (the one that is supposed to open with 'spyking-circus-launcher') and the python GUI that don't work.

Phy is installed in the same environment, I also tried reinstalling phy with no results. 

The preview and result commands bring up the following in the Anaconda prompt but do not open any GUI: 

<img width="506" alt="-rResult" src="https://user-images.githubusercontent.com/61742277/75878902-a8a88b00-5e1a-11ea-985f-df0de745de0d.png">

**Comment by yger** [comment]
Can you try to do
>> conda upgrade qt matplotlib pyqt

**Comment by ArchmageIlmryn** [comment]
That partially fixed it, the launcher works now.

The python GUI opens, but it looks like this:

<img width="917" alt="GUIbroken" src="https://user-images.githubusercontent.com/61742277/75880517-bad7f880-5e1d-11ea-90bf-4524a819ff81.png">

**Comment by yger** [comment]
This, I'm afraid, is not a SpyKING CIRCUS bug anymore.... You need to look at the phy issues https://github.com/cortex-lab/phy/issues/957

**Comment by ArchmageIlmryn** [comment]
Ok, thank you for the help!
