### ISSUE TITLE
Tests still failing?

### ISSUE THREAD

**Issue by TheChymera** [spyking-circus/spyking-circus#234]
following up on a previous issue ( https://github.com/spyking-circus/spyking-circus/issues/165 ), while updating the Gentoo Linux package for your software, I have tried to check up on the test suite again.

I am executing the tests with `nosetests`.

And I get the following [build.log](https://github.com/spyking-circus/spyking-circus/files/4374189/build.log). This looks like a `qt` import error. I hope the package can be used without qt, am I right? :)

**Comment by yger** [comment]
The nosetests are not up to date, this is on the to-do list to update them.
So I fear they might not work. Regarding qt, while Spyking Circus could
theoretically be used without, this is a mandatory dependency since some
additional views/features are requesting it

**Comment by TheChymera** [comment]
Thanks :)
