### ISSUE TITLE
value error in algorithms.py and hangs

### ISSUE THREAD

**Issue by alexgonzl** [spyking-circus/spyking-circus#245]
Hi, 

Running into what looks like an edge-case error in version 0.9.6: 

```
/anaconda3/envs/spk/lib/python3.7/site-packages/circus/shared/algorithms.py", line 1055, in refine_amplitudes
    for values in list(neutral_values.values())
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```

I saw that this line is slightly different in 0.9.7, tried updating the code, but still get the same error:
```
/anaconda3/envs/spk/lib/python3.7/site-packages/circus/shared/algorithms.py", line 1055, in refine_amplitudes
    for values in neutral_values.values()
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate
```
execution hangs from here on both versions, assuming that is related to mpi.

I was able to patch this error by checking if bad_values was empty and assigning to a one element np.nan array: 
```
        if len(bad_values.values()) == 0:
            all_bad_values = numpy.array([numpy.nan])
        else:
            all_bad_values = numpy.concatenate([
                values
                for values in bad_values.values()
            ])
```
not elegant by any means, but didn't want to mess up some of the downstream code.

**Comment by yger** [comment]
Thanks for spotting that, I'll patch that. Indeed, this seems like a corner case
