### ISSUE TITLE
Error in .h5 file from MultiChannel Systems File 

### ISSUE THREAD

**Issue by Bilalgp** [spyking-circus/spyking-circus#247]
I am having trouble with the following error when trying to set the parameters file. I am using an .h5 file generated by the MCS DataManager Software. I think Barbara on the Google Groups was also having the same issue. I am not sure how to fix it 

![image](https://user-images.githubusercontent.com/26805330/80004723-af559500-8490-11ea-95ce-077c8c64a4a9.png)

**Comment by yger** [comment]
You need to specify where the data are saved in the .HDF5 file, i.e. what
is the key to access them (the h5_key parameter). Are you sure of your key?

Best

Pierre

**Comment by Bilalgp** [comment]
I used h5_key = Data in the [data] category in the .params file based on this

![image](https://user-images.githubusercontent.com/26805330/80013132-66a3d900-849c-11ea-9b81-192db93798c8.png)

Thanks

**Comment by yger** [comment]
I guess Data is not enough. To see where the data are, do
>> f['Data'].keys()
And explore the tree until you reach the data

**Comment by yger** [comment]
Is this fixed?

**Comment by Bilalgp** [comment]
I wasn't able to figure it out but I will close the ticket.

**Comment by yger** [comment]
So this means this is working, or you are giving up? Because this should be rather easy, as said, you just need to know in which "internal folder" of the HDF5 file the data are saved.
