### ISSUE TITLE
Questions: Need more clarity about export_pcs = 'some' 

### ISSUE THREAD

**Issue by bapungiri** [spyking-circus/spyking-circus#249]
What is the difference between 'some' and 'all' when exporting the data for phy. How many principal components are being exported ? Features for how many spikes are being exported ?

According to phy:
`pc_features.npy` - `[nSpikes, nFeaturesPerChannel, nPCFeatures]` single matrix giving the PC values for each spike. The channels that those features came from are specified in pc_features_ind.npy. E.g. the value at pc_features[123, 1, 5] is the projection of the 123rd spike onto the 1st PC on the channel given by pc_feature_ind[5].

But when using `export_pcs = 'some'`, the first dimension of `pc_features.npy` is `<<`  than `nSpikes`. However from the docmentation of spyking-circus, I got the impression that it exports features for all spikes but only reduces the number of principal components/features per channel.

For example when using `export_pcs= 'some'` for one of my dataset, the dimension for `pc_feature.npy` array is `(40000,5,80)` but size of 'spike_times.npy' is `(61101498,)`. And I believe because of this the Phy visualization shows a flat line in the feature view:
![phyfeature](https://user-images.githubusercontent.com/22163476/81509961-6dc04900-92dc-11ea-88e5-ee08248a3830.png)

**Comment by yger** [comment]
When you select "some", we only export the PCs for a fixed number of spikes randomly selected within each cluster. I think this default value is fixed to 500. So it means that you'll have at max 500*nb_clusters PCs.

**Comment by bapungiri** [comment]
At the moment this is not clear from the documentation, will be nice if this can be added for others to see.

**Comment by bapungiri** [comment]
It seems this could be RAM related (32 gb for my system). Do you think implementing parallel hdf5 will help ?

**Comment by yger** [comment]
I'll have a look, but as said, I do not encourage to export all PCs. This is useless, for several reasons: 
- seeing outliers does not mean they should be discarded, since they are likely to be overlapping spikes. 
- detouring manually clusters is not valid in a template-matching workflow. So exporting "some" only allows you to check the "quality" or the behavior of the algorithm, but not more.
- the size of the PCs exported can easily be larger than the data file itself (see your situation...)

**Comment by yger** [comment]
And no, parallel HDF5 should not help in this situation

**Comment by bapungiri** [comment]
Thanks for looking into this issue. Actually, we record for very long duration (> 16 hours), and sometimes encounter drift. Visualizing all the features helps in making the merging/splitting decisions.

**Comment by yger** [comment]
Yes, ok, but then maybe that exporting only "some" is sufficient to visualize your drifts. The problem, as you can see, is that the size of the array needed to export all PCs is huge.

**Comment by bapungiri** [comment]
Yeah I understand the limitations. But if you look at the image above, it's hard to infer the drift from the available features. 
Possible workaround for now: 
I can use the matlab-gui to delete obvious noisy templates. This can help reduce the size of the array being exported. But I am not sure if 'kill template' permanently deletes it. Would appreciate your thoughts on it.

**Comment by yger** [comment]
I would strongly encourage you to use the "merged" results as a starting point for your analysis (see documentation and the -e merged extension for converting and/or visualization). This should gives you refined results where templates are already partially merged and noisy ones are removed (you can tweak parameters of the [merging] section for your needs if you want). This should decrease the number of final templates. When you used the Matlab or the phy GUI, you do not affect the main results of the algorithms, but only saved versions.

**Comment by bapungiri** [comment]
Thanks for the advice. I did use the "merged", but that did not help much in reducing the number of templates. I used the matlab-gui to reduce the number of templates manually.
