### ISSUE TITLE
Phy GUI doesn't work

### ISSUE THREAD

**Issue by alison6696** [spyking-circus/spyking-circus#250]
Hey!
I have a problem. It all worked before with the same steps, but now when I try to run phy GUI (circus-gui-python path/mydata.extension), it gives an exception that the file is used by another program (No other programs are opened). It is the same at two seperated computers.
Also recently, couple of monthes ago smart search stopped to work: when it is set to true, it gives an error. 
Now I decided to delete and install Anaconda again on one of two available computers, but now I even can't run the program (spyking-circus path/mydata.extension) - it gives an error that MPI is installed not correctly, contact developers, or something like this. I tried to delete MPI and install again. To delete both MPI and Anaconda and install again, nothing helped. It would be great if I you can help me at least with one of this problems...

**Comment by alison6696** [comment]
So after everything when I try to run theprogram, it says: "Intel MPI may not be yet properly implemented: contact developers"

**Comment by yger** [comment]
Can you update the program with pip, and see if this works? This is a
packaging bug that we spotted in the latest release (0.9.7) for windows

>> pip install
https://github.com/spyking-circus/spyking-circus/archive/master.zip

**Comment by yger** [comment]
Regarding the other issue, I must have more details to understand what is happening. What is your input file data type, are you using the latest phy/phylib version?

**Comment by alison6696** [comment]
> Can you update the program with pip, and see if this works? This is a packaging bug that we spotted in the latest release (0.9.7) for windows pip install https://github.com/spyking-circus/spyking-circus/archive/master.zip --upgrade

Thanks a lot! It helped!
About other I'lltry to see now.

**Comment by alison6696** [comment]
About the smartsearch situation is following: when I run for the first time for the file, it is ok. But when I change the threshold and run it again, it gives an error: "IndexError: index 2 is out of bounds for axis 0 with size 2"

![Screenshot (19)](https://user-images.githubusercontent.com/58594682/82026740-75447100-9693-11ea-99fd-93146d4d846b.png)
![Screenshot (18)](https://user-images.githubusercontent.com/58594682/82026752-77a6cb00-9693-11ea-96c6-96e58590c7ac.png)

**Comment by yger** [comment]
If the datafile is not too large, can you send it to me by email (with the .params and .prb). Because I suspect you are hitting a corner case with very few spikes on some electrode.

**Comment by yger** [comment]
ah but wait, I think this bug has been fixed in 0.9.7. Can you again update? Sorry for that.... Since 0.9.2, we made quite a lot of changes to improve the run times/performances of the algorithms, and it looks like some corner cases were missed sometimes...

**Comment by yger** [comment]
This bug has been fixed in 0.9.9. I guess this is related to something reported by one other user, and only happening on some machine. Linked to shared memory pointers

**Comment by yger** [comment]
(I'm talking about the bug with the bad termination error. This is not really a bug, but rather a bad termination of the program. For the other problem you had, I don't know). But let me know if you still have an error
