### ISSUE TITLE
H5File has no attribute time_axis

### ISSUE THREAD

**Issue by stephfulton** [spyking-circus/spyking-circus#256]
Hi!

I'm trying to run an hdf5 file, but I get the following error:
![Screen Shot 2020-05-20 at 10 53 52 AM](https://user-images.githubusercontent.com/32069833/82461890-e2d41100-9a88-11ea-8500-729ba263f144.png)

I updated spyking-circus to 0.9.8 but that didn't help.

**Comment by yger** [comment]
What is the .params file? Did you specified the key h5_key in the [data] section to tell the software where the data are?

**Comment by stephfulton** [comment]
Here is the [data] section of the .params file. Everything else is the default value.

![Screen Shot 2020-05-20 at 12 16 36 PM](https://user-images.githubusercontent.com/32069833/82471502-c5a53f80-9a94-11ea-8541-11064a287d89.png)

I do get key related errors if I put a nonexistent key in the .params file, so I believe it's recognizing the key.

**Comment by yger** [comment]
Could it be the case that the data shape, at the location given by the h5_key, is a flat 1D array? If this is the case, then SC does not know how to deal with this with such a wrapper. urrently, it assumes HDF5 file are 2D or 3D arrays. Do you know the number of channels, and how exactly the data are saved?

**Comment by stephfulton** [comment]
Yes, the data is a 1D array. We'll try to change how the data is converted and see if that works! Thank you.

**Comment by yger** [comment]
Alternatively, I could easily make this wrapper able to handle 1D array, so I'll keep you updated as soon as this is done
