### ISSUE TITLE
problem in clustering step

### ISSUE THREAD

**Issue by benefron** [spyking-circus/spyking-circus#259]
Hi,
I am running the launcher on a .dat with no header info as RAW_Binary files.
The preview works well (even though the thr is not updated in the file when pressing the button but it is a minor issue ), and I see my channels.
FIltering and whitening also work.
But clustering returns the following error:
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 9604 RUNNING AT PC01235022
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
----------------------------  Error  -----------------------------
| Step "clustering" failed for reason Command '['mpiexec', '-np', '6', 'spyking-circus-subtask', 'clustering', 'C:\\Users\\lampllab\\Data\\Galvo\\16_03_20_1727\\continuous.dat', '6', '0', 'False', 'False']' returned non-zero exit status 4294967295.!
------------------------------------------------------------------

Thank you

**Comment by yger** [comment]
Can you send me the .log file? Because from this error, I can not say much

**Comment by benefron** [comment]
[continuous.log](https://github.com/spyking-circus/spyking-circus/files/4680643/continuous.log)
and this is the full output in the cmd:

Starting spyking circus at Tue May 26 10:39:10 2020.

Command line call:
spyking-circus C:/Users/lampllab/Data/Galvo/16_03_20_1727/continuous.dat --method clustering



##################################################################
#####           Welcome to the SpyKING CIRCUS (0.9.8)        #####
#####                                                        #####
#####              Written by P.Yger and O.Marre             #####
##################################################################


File          : C:\Users\lampllab\Data\Galvo\16_03_20_1727\continuous.dat
Steps         : clustering
Number of CPU : 6/12
Parallel HDF5 : False
Shared memory : True
Hostfile      : C:\Users\lampllab\spyking-circus\circus.hosts

##################################################################


-------------------------  Informations  -------------------------
| Number of recorded channels : 40
| Number of analyzed channels : 32
| File format                 : RAW_BINARY
| Data type                   : int16
| Sampling rate               : 30 kHz
| Duration of the recording   : 13 min 49 s 926 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 100 um
| Threshold crossing          : negative
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Using only 6 out of 12 local CPUs available (-c to change)
------------------------------------------------------------------
Searching isolated random spikes to sample amplitudes...
100%|####################################|[01:10<00:00, 35.08s/it]
Found 92316 spikes over 255996 requested
Estimating amplitudes distributions...
Smart Search of good isolated spikes for the clustering (1/3)...
100%|####################################|[01:17<00:00, 38.70s/it]
Found 87723 isolated spikes over 255996 requested (3513 rejected)
Computing density estimations...
Searching random spikes to refine the clustering (2/3)...
100%|####################################|[00:54<00:00, 27.09s/it]
Found 20538 spikes over 255996 requested
Refining density estimations...
Searching random spikes to refine the clustering (3/3)...
100%|####################################|[00:58<00:00, 29.07s/it]
Found 10249 spikes over 255996 requested
Refining density estimations...
Running density-based clustering...
100%|####################################|[00:09<00:00,  1.60s/it]
-------------------------  Informations  -------------------------
| Number of clusters found : 35
| Number of local merges   : 11 (method nd-bhatta, param 2)
------------------------------------------------------------------
Estimating the templates with the median-raw procedure ...
100%|####################################|[00:00<00:00,  9.97it/s]
-------------------------  Informations  -------------------------
| Templates on few channels only, cc_merge set to 1 automatically
------------------------------------------------------------------
Removing mixtures of templates...
100%|####################################|[00:00<00:00, 11.49it/s]
100%|####################################|[00:00<00:00, 32.35it/s]
-------------------------  Informations  -------------------------
| Number of global merges    : 0
| Number of mixtures removed : 0
------------------------------------------------------------------
Computing optimal amplitudes for the templates...
  0%|                                            |[00:00<?, ?it/s]Traceback (most recent call last):
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lampllab\.conda\envs\circus\Scripts\spyking-circus-subtask.exe\__main__.py", line 7, in <module>
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\scripts\subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\clustering.py", line 1696, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\shared\algorithms.py", line 958, in refine_amplitudes
    data = templates[j].dot(snippets)[0].astype(numpy.float32)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 363, in dot
    return self * other
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 517, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
Traceback (most recent call last):
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lampllab\.conda\envs\circus\Scripts\spyking-circus-subtask.exe\__main__.py", line 7, in <module>
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\scripts\subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\clustering.py", line 1696, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\shared\algorithms.py", line 958, in refine_amplitudes
    data = templates[j].dot(snippets)[0].astype(numpy.float32)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 363, in dot
    return self * other
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 517, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
Traceback (most recent call last):
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lampllab\.conda\envs\circus\Scripts\spyking-circus-subtask.exe\__main__.py", line 7, in <module>
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\scripts\subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\clustering.py", line 1696, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\shared\algorithms.py", line 958, in refine_amplitudes
    data = templates[j].dot(snippets)[0].astype(numpy.float32)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 363, in dot
    return self * other
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 517, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
Traceback (most recent call last):
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lampllab\.conda\envs\circus\Scripts\spyking-circus-subtask.exe\__main__.py", line 7, in <module>
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\scripts\subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\clustering.py", line 1696, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\shared\algorithms.py", line 958, in refine_amplitudes
    data = templates[j].dot(snippets)[0].astype(numpy.float32)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 363, in dot
    return self * other
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 517, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
  0%|                                            |[00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lampllab\.conda\envs\circus\Scripts\spyking-circus-subtask.exe\__main__.py", line 7, in <module>
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\scripts\subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\clustering.py", line 1696, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\shared\algorithms.py", line 958, in refine_amplitudes
    data = templates[j].dot(snippets)[0].astype(numpy.float32)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 363, in dot
    return self * other
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 517, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
Traceback (most recent call last):
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lampllab\.conda\envs\circus\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lampllab\.conda\envs\circus\Scripts\spyking-circus-subtask.exe\__main__.py", line 7, in <module>
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\scripts\subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\clustering.py", line 1696, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\circus\shared\algorithms.py", line 958, in refine_amplitudes
    data = templates[j].dot(snippets)[0].astype(numpy.float32)
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 363, in dot
    return self * other
  File "c:\users\lampllab\.conda\envs\circus\lib\site-packages\scipy\sparse\base.py", line 517, in __mul__
    raise ValueError('dimension mismatch')
ValueError: dimension mismatch
----------------------------  Error  -----------------------------
| Step "clustering" failed for reason Command '['mpiexec', '-np', '6', 'spyking-circus-subtask', 'clustering', 'C:\\Users\\lampllab\\Data\\Galvo\\16_03_20_1727\\continuous.dat', '6', '0', 'False', 'False']' returned non-zero exit status 1.!
------------------------------------------------------------------

Process exited normally


Thank you

**Comment by yger** [comment]
Arg. Thanks, this is helpful. Could you share with me the .dat file, with the .prb and the .params?

**Comment by yger** [comment]
The prb has a single shank?

**Comment by yger** [comment]
I suspect this is the error: I optimized the method without taking into account the possibility of several shanks... I'll have a look, sorry for the problem

**Comment by benefron** [comment]
The .dat is a large file.
I can share the .prb and .parmas
I have 2 shanks.
I wrote them down as 2 groups and wrote the distance.
I will try to right them as one group with a big x distance.


[parmas and prb.txt](https://github.com/spyking-circus/spyking-circus/files/4680776/parmas.and.prb.txt)

**Comment by yger** [comment]
The problem is with the two shanks, as said, this step was rewritten without taking this possibility into account. My bad. I'll fix that today in master and let you know. Meanwhile, you can rewrite the prb without the groups (with an artificially large distances between channels of the two groups)

**Comment by benefron** [comment]
I have ADC channels that I recorded shold I count them in the total_nb_channels in the .prb file or ignore them?

**Comment by yger** [comment]
Actually I just pushed a patch in master. Can you try to update and tell me if this works?
pip install --upgrade https://github.com/spyking-circus/spyking-circus/archive/master.zip

The ADC channels should be counted, yes, if they are written down in the binary file

**Comment by benefron** [comment]
I am getting a different error now:
Starting spyking circus at Tue May 26 11:30:36 2020.

Command line call:
spyking-circus C:/Users/lampllab/Data/Galvo/16_03_20_1727/continuous.dat --method clustering --cpu 8



##################################################################
#####           Welcome to the SpyKING CIRCUS (0.9.9)        #####
#####                                                        #####
#####              Written by P.Yger and O.Marre             #####
##################################################################


File          : C:\Users\lampllab\Data\Galvo\16_03_20_1727\continuous.dat
Steps         : clustering
Number of CPU : 8/12
Parallel HDF5 : False
Shared memory : True
Hostfile      : C:\Users\lampllab\spyking-circus\circus.hosts

##################################################################


-------------------------  Informations  -------------------------
| Number of recorded channels : 40
| Number of analyzed channels : 32
| File format                 : RAW_BINARY
| Data type                   : int16
| Sampling rate               : 30 kHz
| Duration of the recording   : 13 min 49 s 926 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 100 um
| Threshold crossing          : negative
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Using only 8 out of 12 local CPUs available (-c to change)
------------------------------------------------------------------
Searching isolated random spikes to sample amplitudes...
100%|####################################|[00:54<00:00, 27.05s/it]
Found 92297 spikes over 256000 requested
Estimating amplitudes distributions...
Smart Search of good isolated spikes for the clustering (1/3)...
100%|####################################|[00:51<00:00, 25.73s/it]
Found 87013 isolated spikes over 256000 requested (8668 rejected)
Computing density estimations...
Searching random spikes to refine the clustering (2/3)...
100%|####################################|[00:44<00:00, 22.14s/it]
Found 22243 spikes over 256000 requested
Refining density estimations...
Searching random spikes to refine the clustering (3/3)...
100%|####################################|[00:44<00:00, 22.39s/it]
Found 8522 spikes over 256000 requested
Refining density estimations...
Running density-based clustering...
100%|####################################|[00:07<00:00,  1.97s/it]
-------------------------  Informations  -------------------------
| Number of clusters found : 35
| Number of local merges   : 12 (method nd-bhatta, param 2)
------------------------------------------------------------------
Estimating the templates with the median-raw procedure ...
100%|####################################|[00:00<00:00,  7.96it/s]
-------------------------  Informations  -------------------------
| Templates on few channels only, cc_merge set to 1 automatically
------------------------------------------------------------------
Removing mixtures of templates...
100%|####################################|[00:00<00:00,  6.06it/s]
100%|####################################|[00:00<00:00, 15.73it/s]
-------------------------  Informations  -------------------------
| Number of global merges    : 0
| Number of mixtures removed : 0
------------------------------------------------------------------
Computing optimal amplitudes for the templates...
100%|####################################|[00:01<00:00,  2.58it/s]
100%|####################################|[00:00<00:00,  7.27it/s]
Pre-computing the overlaps of templates...
100%|####################################|[00:00<00:00, 12.35it/s]

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 10444 RUNNING AT PC01235022
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 20020 RUNNING AT PC01235022
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 5 PID 7068 RUNNING AT PC01235022
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
----------------------------  Error  -----------------------------
| Step "clustering" failed for reason Command '['mpiexec', '-np', '8', 'spyking-circus-subtask', 'clustering', 'C:\\Users\\lampllab\\Data\\Galvo\\16_03_20_1727\\continuous.dat', '8', '0', 'False', 'False']' returned non-zero exit status 4294967295.!
------------------------------------------------------------------

Process exited normally


[continuous.log](https://github.com/spyking-circus/spyking-circus/files/4680890/continuous.log)

**Comment by yger** [comment]
Then this is more annoying, since this is hard to debug here for me.... No way you can send me the .dat file, to reproduce/debug the error? This would be helpful for me. The only certainty here is that if you revert to 0.9.7, I guess these errors should not be there. This could be a temporary solution while you upload the file. As said, these errors come from optimizations performed recently, but ignoring the possibility of shanks...

pip install --upgrade https://github.com/spyking-circus/spyking-circus/archive/0.9.7.zip

**Comment by benefron** [comment]
Hi again,
I reran it with a .prb file ignoring the shanks and I get a new error:

Starting spyking circus at Tue May 26 15:00:59 2020.

Command line call:
spyking-circus C:/Users/lampllab/Data/Galvo/16_03_20_1727/continuous.dat --method filtering,whitening,clustering



##################################################################
#####           Welcome to the SpyKING CIRCUS (0.9.9)        #####
#####                                                        #####
#####              Written by P.Yger and O.Marre             #####
##################################################################


File          : C:\Users\lampllab\Data\Galvo\16_03_20_1727\continuous.dat
Steps         : filtering, whitening, clustering
Number of CPU : 6/12
Parallel HDF5 : False
Shared memory : True
Hostfile      : C:\Users\lampllab\spyking-circus\circus.hosts

##################################################################


-------------------------  Informations  -------------------------
| Number of recorded channels : 32
| Number of analyzed channels : 32
| File format                 : RAW_BINARY
| Data type                   : int16
| Sampling rate               : 30 kHz
| Duration of the recording   : 17 min 17 s 408 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 100 um
| Threshold crossing          : negative
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Using only 6 out of 12 local CPUs available (-c to change)
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Filtering has already been done
| Median over all channels has already been removed
------------------------------------------------------------------
Analyzing data to get whitening matrices and thresholds...
Found 30s without spikes for whitening matrices...
Because of whitening, need to recompute the thresholds...
Searching spikes to construct the PCA basis...
100%|####################################|[00:09<00:00,  3.22s/it]
Found 25596 waveforms over 25596 requested
-------------------------  Informations  -------------------------
| A basis with 5 dimensions has been built
------------------------------------------------------------------
Searching isolated random spikes to sample amplitudes...
100%|####################################|[00:58<00:00, 19.45s/it]
Found 118838 spikes over 255996 requested
Estimating amplitudes distributions...
Smart Search of good isolated spikes for the clustering (1/3)...
100%|####################################|[00:59<00:00, 19.74s/it]
Found 112775 isolated spikes over 255996 requested (4360 rejected)
Computing density estimations...
Searching random spikes to refine the clustering (2/3)...
100%|####################################|[00:44<00:00, 14.88s/it]
Found 27209 spikes over 255996 requested
Refining density estimations...
Searching random spikes to refine the clustering (3/3)...
100%|####################################|[00:38<00:00, 13.00s/it]
Found 2611 spikes over 255996 requested
Refining density estimations...
Running density-based clustering...
100%|####################################|[00:48<00:00,  8.11s/it]
-------------------------  Informations  -------------------------
| Number of clusters found : 57
| Number of local merges   : 18 (method nd-bhatta, param 2)
------------------------------------------------------------------
Estimating the templates with the median-raw procedure ...
100%|####################################|[00:00<00:00,  9.04it/s]
Removing 27 strongly shifted or noisy/mixture templates...
Merging similar templates...
100%|####################################|[00:00<00:00, 25.68it/s]
Removing mixtures of templates...
100%|####################################|[00:00<00:00, 25.91it/s]
100%|###################################|[00:00<00:00, 107.82it/s]
-------------------------  Informations  -------------------------
| Number of global merges    : 7
| Number of mixtures removed : 0
------------------------------------------------------------------
Computing optimal amplitudes for the templates...
100%|####################################|[00:00<00:00,  4.15it/s]
100%|####################################|[00:00<00:00,  8.21it/s]
Pre-computing the overlaps of templates...
100%|####################################|[00:00<00:00, 25.14it/s]

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 25744 RUNNING AT PC01235022
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 17340 RUNNING AT PC01235022
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 4124 RUNNING AT PC01235022
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
----------------------------  Error  -----------------------------
| Step "clustering" failed for reason Command '['mpiexec', '-np', '6', 'spyking-circus-subtask', 'clustering', 'C:\\Users\\lampllab\\Data\\Galvo\\16_03_20_1727\\continuous.dat', '6', '0', 'False', 'False']' returned non-zero exit status 4294967295.!
------------------------------------------------------------------

Process exited normally



[continuous.log](https://github.com/spyking-circus/spyking-circus/files/4682081/continuous.log)

[A2x16-50mm_oneGroup.txt](https://github.com/spyking-circus/spyking-circus/files/4682085/A2x16-50mm_oneGroup.txt)

**Comment by yger** [comment]
Looks like the same error to me. Again, don't know what is happening, so would be good if you could send me a .dat file. Maybe even by truncating yours, we could reproduce the problem?

**Comment by benefron** [comment]
How can I send you the .dat file?

**Comment by yger** [comment]
Dropbox ? Google Drive ? Wetransfer ?

**Comment by benefron** [comment]
what's your email

**Comment by yger** [comment]
pierre.yger@gmail.com

**Comment by benefron** [comment]
sent it to you via dropbox.
Thank you very much

**Comment by yger** [comment]
I got your data, but are you sure they are properly loaded? You have only 32 channels in the data (what is the x40 in the .params file). Because from the preview, I am not sure you are seeing proper spikes there

**Comment by yger** [comment]
But still, I'll see if I can reproduce your error

**Comment by yger** [comment]
(I am fairly sure the data are not properly loaded, btw, and this could be the reason of the crash here). The waveforms in continuous.basis.hdf5 does not look like anything normal

**Comment by benefron** [comment]
I have 8 ADC channels on the data

**Comment by yger** [comment]
Ok, but then this is problematic, since the code do not know that. You must have said in the .prb file total_nb_channels = 40. Problem here is that since is has been filtered, data are completly messed up now

**Comment by yger** [comment]
But having said that, on my laptop, the code run without problems. Templates do not look like spikes, since data are wrong, but I have no crash. So I'll try to understand what is happening for you. You are using Linux/Win/Mac? Which python version?

**Comment by benefron** [comment]
I am running it on windows.
python version 3.7

**Comment by yger** [comment]
This is very strange. The error is appearing with a clean install, and a fresh start (remove the results folder continuous first) ?

**Comment by benefron** [comment]
I ran it with the correct prb. files. The one I sent you had the mistake with the amount of channels

**Comment by yger** [comment]
I just also tried by setting total_nb_channels = 40 in the .prb you send me. Indeed, data looks much better, and now I do have spikes. But still no errors, the code is running smoothly, sadly for us :-(

**Comment by benefron** [comment]
reran everything on a new copy of the data and still the same thing happens.
I will try again tomorrow. maybe I will reinstall spyking circus and see if it helps.
Thanks

**Comment by yger** [comment]
Otherwise, we should plan a small debugging session maybe via Teamviewer such that I can reproduce the problem. Or will try to install it myself with a windows VM tomorrow and see if it helps to reproduce the problem. Sorry for that

**Comment by benefron** [comment]
Good morning
reinstalled clean installation and it is still not working
:(

**Comment by yger** [comment]
Do you have teamviewer installed? Could I remotly access the machine to have a look (if so, we can discuss that by emails). Otherwise, wait till I install a VM to try to reproduce the problem

**Comment by yger** [comment]
I just set up a fresh conda environment in a Virtual Machine with Windows 10, python 3.7, and I can not reproduce the error, the code works :(

**Comment by yger** [comment]
Here is the list of the packages. I installed the env as said in the website, by first doing
conda install -c intel mpi4py
Then
conda install -c spyking-circus spyking-circus

[conda.txt](https://github.com/spyking-circus/spyking-circus/files/4687979/conda.txt)

**Comment by benefron** [comment]
I am reinstalling python and anaconda and will re try it

**Comment by benefron** [comment]
Still not working. I don't know. do you want to try and take control of my computer?

**Comment by yger** [comment]
I could, yes, near 2.30 ? I have teamviewer, so you an send me a login

**Comment by benefron** [comment]
14:30 which clock?

**Comment by yger** [comment]
Paris time? meaning in 30min for me ?

**Comment by benefron** [comment]
Works for me thanks. I'll send you the details

**Comment by benefron** [comment]
ID: 1 243 645 674
password: 9y8q5e

**Comment by yger** [comment]
I got the credentials, but I deleted the post to hide them

**Comment by benefron** [comment]
thanks

**Comment by yger** [comment]
I am asked to prompt ont other password, displayed on your screen... Can you send it to me by email?
