### ISSUE TITLE
MPI not implemented properly

### ISSUE THREAD

**Issue by AABBASI89** [spyking-circus/spyking-circus#261]
Hello developers,

I am getting the following error while running spyking circus. I am pretty new to this software, kindly share some insights which can help me resolve this error. 

![image](https://user-images.githubusercontent.com/36443035/83560368-fa6cba00-a4ca-11ea-89ad-914f98c5cef6.png)

**Comment by yger** [comment]
Sure. You just need to install the latest version from the master branch
using the command

 pip install
https://github.com/spyking-circus/spyking-circus/archive/master.zip
 --upgrade

Best

Pierre

**Comment by AABBASI89** [comment]
Thank you Pierre for your swift reply. That has resolved that issue. Now I am getting a different error during the whitening step which I will post in a seperate thread.
