### ISSUE TITLE
Whitening failed non zero exit code

### ISSUE THREAD

**Issue by AABBASI89** [spyking-circus/spyking-circus#262]
Hey developers,
Now spiking circus is giving me this error (see below). It looks like it has something to do with the zero based indexing. I have 32 channels which are arranged in 32xnSamps npy file. The sorting worked fine during the filtering step and only crashed during the whitening step. Please help!

![image](https://user-images.githubusercontent.com/36443035/83570407-d5804300-a4da-11ea-8006-404163934ad5.png)

**Comment by yger** [comment]
Could you send me the .prb file, to see if this is correct?

**Comment by yger** [comment]
Could it be that you gave the list of channels starting at 1 and not at 0, in the .prb?

**Comment by AABBASI89** [comment]
Thank you Pierre for your reply. Yes the issue was 1 based channel numbering in the .prb file. Changing to 0 based numbering fixed the issue.
