### ISSUE TITLE
NPY file not supported by MATLAB and Phy GUI

### ISSUE THREAD

**Issue by AABBASI89** [spyking-circus/spyking-circus#263]
My data file is of .npy format. When I want to view results of my spike sorting using either MATLAB or Phy GUI I get the following warnings. In which format my data should be so that it is accepted by MATLAB and Phy GUI. 

![image](https://user-images.githubusercontent.com/36443035/83678722-09b73a80-a593-11ea-96ac-61b9d46698ae.png)

![image](https://user-images.githubusercontent.com/36443035/83678806-2a7f9000-a593-11ea-99fd-dcc9e48d1690.png)

**Comment by yger** [comment]
The GUI can only display the raw data if the file format is raw_binary. But you can still use them to view templates, spike times, cross correlogram, isis...

**Comment by AABBASI89** [comment]
Thanks for the clarification. Also why am I seeing only a single waveform for each cluster. See the screenshot below. 

![image](https://user-images.githubusercontent.com/36443035/83683507-5d795200-a59a-11ea-9bac-279876a7f6b3.png)

**Comment by yger** [comment]
You see the template. If there is only one channel, it means that the template was only localized on a single channel (no signal around). Assuming your electrodes are nearby (less than 100um apart), you should however see some templates covering multiple channels.

**Comment by AABBASI89** [comment]
Then, how can I see all the waveforms?

**Comment by yger** [comment]
Only if the GUI can read the raw data, I.e. if your file format is raw_binary. These waveforms are informative, but not crucial to the visualization: if a spike is fitted, by construction of the algorithm, the raw data should look like the template.
