### ISSUE TITLE
Tetrode sorting. Template only on one channel

### ISSUE THREAD

**Issue by AABBASI89** [spyking-circus/spyking-circus#264]
I am trying to perform tetrode spike sorting using spyking circus. Here is my channel prb file:

total_nb_channels = 32
radius            = 100
channel_groups = {
0: { 'channels': [7, 5, 3, 6],
     'geometry': {7: (20.0, 0.0),
                  5: (0.0, 20.0),
                  3: (-20.0, 0.0),
                  6: (0.0, -20.0)},
     'graph': []},
1: { 'channels': [4, 2, 23, 21],
     'geometry': {4: (220.0, 0.0),
                  2: (200.0, 20.0),
                  23: (180.0, 0.0),
                  21: (200.0, -20.0)},
     'graph': []},
2: { 'channels': [19, 22, 20, 18],
     'geometry': {19: (420.0, 0.0),
                  22: (400.0, 20.0),
                  20: (380.0, 0.0),
                  18: (400.0, -20.0)},
     'graph': []},
3: { 'channels': [16, 17, 0, 1],
     'geometry': {16: (620.0, 0.0),
                  17: (600.0, 20.0),
                  0: (580.0, 0.0),
                  1: (600.0, -20.0)},
     'graph': []},      
4: { 'channels': [15, 14, 31, 30],
     'geometry': {15: (820.0, 0.0),
                  14: (800.0, 20.0),
                  31: (780.0, 0.0),
                  30: (800.0, -20.0)},
     'graph': []},
5: { 'channels': [28, 26, 24, 29],
     'geometry': {28: (1020.0, 0.0),
                  26: (1000.0, 20.0),
                  24: (980.0, 0.0),
                  29: (1000.0, -20.0)},
     'graph': []},                                             
6: { 'channels': [27, 25, 12, 10],
     'geometry': {27: (1220.0, 0.0),
                  25: (1200.0, 20.0),
                  12: (1180.0, 0.0),
                  10: (1200.0, -20.0)},
     'graph': []},                                              
7: { 'channels': [8, 13, 11, 9],
     'geometry': {8: (1420.0, 0.0),
                  13: (1400.0, 20.0),
                  11: (1380.0, 0.0),
                  9: (1400.0, -20.0)},
     'graph': []},                                        
               
}

In my experiments I am using this Neuronexus probe
![image](https://user-images.githubusercontent.com/36443035/84235468-be2cf100-aaaa-11ea-92c5-e4c89abdcbaa.png)

Now my issue is that the algorithm is not giving me four waveforms/templates for a single tetrode. How do I resolve this issue?

**Comment by yger** [comment]
What do you mean exactly? The code is working, and you have templates at the end, but you are worried that they are not defined on 4 channels? Templates are defined on channels where you have information, so it is perfectly fine if some of them are defined on less than 4 channels..

**Comment by AABBASI89** [comment]
Thank you for your reply. Now the visualization works with the Phy GUI.
