### ISSUE TITLE
Bug - Negative channels

### ISSUE THREAD

**Issue by holmescharles** [spyking-circus/spyking-circus#265]
I just realized my new probe file was using channels from -1 to 30 instead of 0 to 31.
Spyking circus did not catch this. It ran and found spikes.
Once I realized I had a channel -1, I checked the preview GUI and saw it was indeed displaying a channel with "-1" as the channel number.
My guess is that python is interpreting this channel as "the last channel in the array", and thus not raising an error.

**Comment by yger** [comment]
Thanks for spotting that, I'll fix it

**Comment by yger** [comment]
This should be fixed in the master branch
