### ISSUE TITLE
Export non-normalized spike amplitudes to Phy

### ISSUE THREAD

**Issue by stephenwhitmarsh** [spyking-circus/spyking-circus#273]
For the purpose of visualizing several templates, and e.g. decided to merge or not, it would be very helpful to compare non-normalized amplitudes over time (i.e. "Template" option in Amplitude view in Phy). Currently, SC exports only normalized (to template) amplitudes. An option to "de-normalize" the amplitudes before exporting would be very helpful.

**Comment by yger** [comment]
Phy computes the amplitude with respect to the raw data, isn't it? You can switch the views by pressing the A key while in the AmplitudeView

**Comment by stephenwhitmarsh** [comment]
Great, thanks, that works indeed, albeit a bit slow. Closing issue :)
