### ISSUE TITLE
spike_times.npy contents when sorting tetrodes 

### ISSUE THREAD

**Issue by GulatiLab** [spyking-circus/spyking-circus#276]
We are using spiking circus for offline spike sorting of tetrode recordings. We just want to clarify whether the time stamps for a given cluster in the spike_times.npy file are from a single channel of the tetrode or from all four channels. If they are from all four channels then what is the way to segregate it?

**Comment by yger** [comment]
The spike times are for a given template, i.e. the spatio temporal motif triggered by the neuron when it is firing an action potential. Quite often, this template can be defined on several channels. So to answer your question, a spike time is for a template/neuron, whose template can cover an arbitrary number of channels (depending of the cell morphology, position, ...)

**Comment by GulatiLab** [comment]
Thank you for the quick reply. So in the picture below, my template fits four channels of the tetrode, which makes sense but how do it get the spike times from a single channel (if I am really interested in that channel). 
So just to give you an example, cluster 81 in the image below says channel 3 but the template fits all four channels like it should for a tetrode, now if I understood well, according to you the spike times should be from all four channels. So how can I get the spike times just from channel 3?
Another unrelated question, why my amplitude column is 0.00 when clearly there are single units identified by the algorithm? Is it because of some display issue?
Looking forward to your reply. Thanks
![screenshot](https://user-images.githubusercontent.com/51457490/88315950-e2940400-cccb-11ea-8497-485cadb15cb5.png)

**Comment by yger** [comment]
Your template is covering 4 channels. So it means that each time the neuron spikes, you have an event triggered on the 4 channels simultaneously. Therefore, when you say "get the spike times from a single channel", it does not really make sense. The channel column, in phy, only tells you the channel where your template is peaking the most: this is just an indication of where, most likely, the soma of the cell is. But again, spike times are associated to templates, and not to channels.

Regarding the 0 in the amplitude column, again, this is strange, and most likely this is a phy bug. I'll see if I can reproduce it. Phy, in theory, should write here the minimal value of your template, on the channels where it is peaking the most. This is also just an indication of how big the waveforms are.

**Comment by GulatiLab** [comment]
Yes each time the neuron spikes the event's are triggered on 4 channels simultaneously, but to calculate the firing rate of that neuron you will only take into consideration one spike out of four. That's why we are interested in getting the spike from a single channel, or from the channel located closer to the soma. 
Regarding the amplitude, it will be good to have those those template values, does it has to do with the my params file or map file? I have attached those files here, just in case if you need them. Thanks for your help. 
[params.zip](https://github.com/spyking-circus/spyking-circus/files/4979804/params.zip)
