### ISSUE TITLE
endianness and open ephys...

### ISSUE THREAD

**Issue by beOn** [spyking-circus/spyking-circus#28]
If I run open ephys data that I _know_ contains clear spikes through spyking circus, then look at the results in either gui, the spike templates look too "sharp." Instead of the familiar waveform, I see very narrow negative-going spikes. I've seen something similar out of other sorting packages (klustakwik) when I've forgotten that the samples are big endian. It looks like endianness is handled really well within openephys.py (and its superclass), but *something* is going on. I'm posting this here in case it jogs someone's memory, but will do some more digging on my own today.

**Comment by yger** [comment]
This is possible, and the best for me to troubleshoot that would be to get
proper data in openephys file format. Do you have a not-too-big file you
could share, with the .params and .prb ?

Best

Pierre

2017-03-28 15:46 GMT+02:00 Ben Acland <notifications@github.com>:

**Comment by beOn** [comment]
Hmm... my individual files are all pretty big, and the full sessions are
multi-GB. I could just copy the header and first 5 minutes or so of a file
I know to have great SNR, but it'd need a phony .openephys file to look
like a full session. Would it be unacceptably lazy of me to send a single
.continuous file, an example .params, and a .prb file for a single
electrode? If it'd help, I can make the phony .openephys file as well, but
want to ensure that I do this in the laziest way that'll get you what you
need.

**Comment by yger** [comment]
I think that sending me the .continuous for a single electrode is fine, 
the point is simply to see spikes, and ensure data are correctly 
loaded/processed

Best

Pierre

**Comment by beOn** [comment]
Here ya go!


[144_CH1.continuous.zip](https://github.com/spyking-circus/spyking-circus/files/876317/144_CH1.continuous.zip)

**Comment by yger** [comment]
Thanks, but in fact, I though you were going to give me a .openephys file
with only one channel (and thus only one .continuous). I may need a bit
more than that to properly understand what the problem is. Because so far,
correct me if I am wrong, but the preview does show valid traces, no? So
maybe you could give the corresponding .openephys with only one
.continuous, and your .params/.prb

Best

Pierre

2017-03-28 18:15 GMT+02:00 Ben Acland <notifications@github.com>:

**Comment by beOn** [comment]
I could've been more clear – it's not the preview, but the waveforms that
appear in phy or Matlab (i.e. circus-gui-python) after running the
algorithm.

**Comment by beOn** [comment]
I'll get you another file once I am out of bed.

**Comment by beOn** [comment]
[example_files.zip](https://github.com/spyking-circus/spyking-circus/files/886870/example_files.zip)

**Comment by yger** [comment]
Thanks for that, and sorry for the delay. I had a look to the file you sent me, and here is what I can see in the "result" mode of the software

![openephys](https://cloud.githubusercontent.com/assets/1672447/25659852/ffc4ee02-3009-11e7-8510-4fce371074e3.png)

What is wrong with such a waveform? It looks rather fine to me, isn't it?

**Comment by beOn** [comment]
Hmm, yes, that's gorgeous. I was running into trouble in phy, specifically. Does everything look ok for you there, too?

**Comment by beOn** [comment]
(And did you leave everything the same in the .params file?)

**Comment by yger** [comment]
I did not changed the .params that was in the examples_files.zip archive. I simply launched the code. Regarding phy, I'm not sure to follow your point: phy is not able to display .openephys traces, so you should only be able to see the mean templates in the Waveform view (and no TraceView). Can you send me a screenshot of the problem?

**Comment by beOn** [comment]
I'm out of office for a bit (just had a baby yesterday), but I meant the
waveforms. I'll grab some screenshots for you soon.

Ben

**Comment by beOn** [comment]
D'oh - sorry not to've gotten back to this sooner.
