### ISSUE TITLE
threshold for spike detection in preview mode

### ISSUE THREAD

**Issue by SaraMati** [spyking-circus/spyking-circus#281]
in the preview mode, when visualizing the threshold, it seems that a suitable threshold should be around 35, screenshot attached (35 is when the dotted line is above the noise level)
![image](https://user-images.githubusercontent.com/12663563/91670035-b9933a00-eae7-11ea-899b-0998caf4940f.png)

isn't this the spike detection threshold in the detection phase of the algorithm? if so, isn't this value the lamda parameter which will be times MAD to make the threshold for each electrode? so \lamda = 6 to 8 should be enough. 
should I trust the preview mode and set spike_thresh = 35 in the params file, or keep it to 8?

**Comment by yger** [comment]
I'll double check, but clearly for most of the data 6-8 should be more than enough. Maybe there is a visual error here, or a gain mismatch. What is your file format and param file?

**Comment by SaraMati** [comment]
file format is raw binary (.raw), gain is defined in the param file as gain = 0.113636
