### ISSUE TITLE
Adding option to reference groups of channels with different reference channels

### ISSUE THREAD

**Issue by benefron** [spyking-circus/spyking-circus#288]
Hi Pierre,
As I asked in the mail. 
Will it be possible to add option to subtract different reference channels for different channel groups.
For example:
channel group: [1,2,3,4,6,7] Reference: Ch 2 (or remove median of all the channels in the group).
channel group: [5,8,9] Reference: ch 9 (or remove median of only channels in the group).

Thank you,
Ben

**Comment by yger** [comment]
Sure, easy to do. I'll make a branch for that. What would be the best syntax for that. I suggest we use the shanks for that, in the probe definition. For example, if we say remove_median = True, then it should be done PER shanks. And for the ground, I would suggest a syntax like
common_ground = {1 : ground_id_shank_1, 2 : ground_id_shank_2}. Would that work for you?

**Comment by benefron** [comment]
I had some trouble before working with the shanks. But I can try. In my data it wasn't always per shank but I can build the file so it will be separated to shanks.
Also maybe if this is done through the prb file than maybe the common reference can accept a list for each shank.

**Comment by yger** [comment]
I'm on it in in the branch multiple grounds. This is much easier to use the shanks in order to distinguish groups of channels that should be considered/processed separatly. So this is the way I'll follow. In this branch, remove_median will only work WITHIN shanks, and grounds could be specified per shanks with a dictionnary. I'll finish testing and this should be good to merge

**Comment by yger** [comment]
If you know how to install a branch, can I ask you to try the one I just made (multiple_grounds), and let me know if you are happy with it? #289

**Comment by benefron** [comment]
Never did it before,
I can check how to do it.
Thanks

**Comment by benefron** [comment]
I am sorry I didn't really understand how to branch and what it means

**Comment by yger** [comment]
You should type
pip install https://github.com/spyking-circus/spyking-circus/archive/multiple_grounds.zip --user

This will install the multiple_grounds branch instead of the master one. Then try to play with, and if you are happy let me know, such that I could merge it into master.

**Comment by benefron** [comment]
It returns an error that the repository doesn't exist

**Comment by benefron** [comment]
sorry it is working. something was wrong with the line I ran

**Comment by yger** [comment]
As said, in this branch, common median across channels is only removed WITHIN each shanks, and you can provide one ground channel per shanks (see the .params file for the syntax). This should be what you asked for

**Comment by benefron** [comment]
Do you have an example for prb file with shanks. I am getting an error reading my prb file

**Comment by benefron** [comment]
It is working. There is a problem with the threshold now. Even with no referencing the threshold is very very low. the default of 6 is 6 times higher than the needed threshold. When doing referencing of a single channel it becomes lower than 0.5 which is not possible to work with.

**Comment by yger** [comment]
Do you have a gain in the data? What is the file format you are using? If not too big, can you share it with me?

**Comment by yger** [comment]
Just be sure to properly delete any previous results (whitening, ...) in order to not interfere with new results
