### ISSUE TITLE
GPU not detected

### ISSUE THREAD

**Issue by rtraghavan** [spyking-circus/spyking-circus#290]
Spyking circus does not detect the GPU currently running on my computer. 

OS: Ubuntu 18.04
GPU: NVIDIA 980 Ti
CUDA: Toolkit 9.1 
Matlab: 2018b (cuda version compatible)

I have verified that matlab and python can recognize/use the GPU, and nvidia-smi and nvcc --version both execute without problems. 

Any ideas how to fix this? Is it something to do with the MPI host file or is that only for CPU recognition.

**Comment by yger** [comment]
SpyKING CIRCUS is not making use of GPU anymore, so this is normal... We made the choice to focus on multi CPU, in order to improve the scaling for thousands of channels
