### ISSUE TITLE
Error during fitting

### ISSUE THREAD

**Issue by sshanbhag** [spyking-circus/spyking-circus#291]
Hello,
I'm having an issue running on MacOS. Things seem to work until later in the fitting process and I get an error (see output below).

-------------------------  Informations  -------------------------
| Number of global merges    : 3
| Number of mixtures removed : 0
------------------------------------------------------------------
Computing optimal amplitudes for the templates...
100%|████████████████████████████████████|[00:12<00:00,  2.90it/s]
100%|████████████████████████████████████|[00:02<00:00,  5.55it/s]
Pre-computing the overlaps of templates...
100%|████████████████████████████████████|[00:03<00:00,  4.87it/s]
Traceback (most recent call last):
  File "/Developer/anaconda3/envs/circus/bin/spyking-circus-subtask", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus==1.0.0', 'console_scripts', 'spyking-circus-subtask')())
  File "/Developer/anaconda3/envs/circus/lib/python3.6/site-packages/circus/scripts/subtask.py", line 55, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/Developer/anaconda3/envs/circus/lib/python3.6/site-packages/circus/__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/Developer/anaconda3/envs/circus/lib/python3.6/site-packages/circus/fitting.py", line 155, in main
    tmp = templates[i, :].toarray().reshape(n_e, n_t)
AttributeError: 'numpy.ndarray' object has no attribute 'toarray'
----------------------------  Error  -----------------------------
| Step "fitting" failed for reason Command '['mpiexec', '-f', '/Users/sshanbhag/spyking-circus/circus.hosts', '-np', '1', 'spyking-circus-subtask', 'fitting', '/Users/sshanbhag/Work/Data/TestData/exports/1429/1429_20200707_01_01_2942_BBN.bin', '1', '0', 'False', 'False']' returned non-zero exit status 1.!

**Comment by yger** [comment]
Sorry for that. This is because of the collect_all mode, that was forgotten. This is now fixed in the master branch, or simply turn off this option

**Comment by sshanbhag** [comment]
Okay, thank you. I’ll either pull in the changes from github or change the option setting. I’m just getting started using the software and was concerned it was an issue with mpich.
