### ISSUE TITLE
question about streams

### ISSUE THREAD

**Issue by rtraghavan** [spyking-circus/spyking-circus#292]
When you enable spyking circus to process multiple streams does it simply concatenate the data together into one file and run the algorithm across it, or does it do something more complex. I ask because I have a number of files that I previously concatenated into one single raw binary file that I am wondering if I send in this concatenated file, or should I send files in separately. Thank you

**Comment by yger** [comment]
Nothing more complicated. Virtually, all the files are concatenated, and this is about it
