### ISSUE TITLE
Traces in Preview Window when using dead_channels

### ISSUE THREAD

**Issue by s-steinberg** [spyking-circus/spyking-circus#312]
I have 32-channel data (saved as .dat file with int16).
The preview window shows the traces properly by default.
![no_dead_ch](https://user-images.githubusercontent.com/74106307/98447426-fcdfd980-2124-11eb-8e05-7ab51cd4f3db.png)

The above screen shot is a spike in 3 channels, in this case channels [20, 21, 22], of the same tetrode.
However, if I set `[detection] dead_channels`, in this case channels [0, 1, 2, 3, 12, 23, 31], the same traces at the same time as above look odd in the preview window. 
![with_dead_ch](https://user-images.githubusercontent.com/74106307/98447494-7bd51200-2125-11eb-8be4-1bd04ded4385.png)

Specifically, polarity of ch 21 (middle) is flipped, scaling of ch 22 (top) is decreased, and the trace shape of ch 20 (bottom) looks different.

Would this affect only the preview window visualization, or also the sorting results (data are not properly loaded)?

Thank you for your time.

**Comment by yger** [comment]
keep in mind that the data are whitened, so maybe that by removing some dead channels, you are changing the whitening matrix, and thus this shape of your data. I'm surprised to see that the change is so drastic, but maybe this is because of the removed channels. You said the data are already filtered. Did you removed the median over channels or not? Again, if you suspect something strange, best is to share your data, such that I could quickly check the quality.

**Comment by s-steinberg** [comment]
Thank you for reply.
As I also did in #311, here is the link to my data.
https://1drv.ms/u/s!AixpdTh0kn8rgas2KKR4780GSUU_dg?e=wuOkdY

**Comment by yger** [comment]
With the master branch, and your .params (thus with the dead channels selected), I can not reproduce what you are seeing. My view looks like your first plot, without any polarity switch

**Comment by yger** [comment]
With all channels
![all_channels](https://user-images.githubusercontent.com/1672447/98466465-e6db2300-21cf-11eb-9b0b-59a5dba59c06.png)

With your selection
![selection](https://user-images.githubusercontent.com/1672447/98466467-e93d7d00-21cf-11eb-807d-ea33958fbc3e.png)

**Comment by s-steinberg** [comment]
Thank you very much. I thought I was at the latest commit on the master branch. However I uninstalled and reinstalled spyking-circus, and then my preview window shows as yours. I'm still having a problems in #311 but this issue is solved. Thank you again.

**Comment by s-steinberg** [comment]
By the way, `conda install -c conda-forge -c intel -c spyking-circus spyking-circus` as in the documentation will install spyking-circus-1.0.0. Therefore I did `pip install git+git://github.com/spyking-circus/spyking-circus@master`.

**Comment by yger** [comment]
Yes, normal, 1.0.1 has not been pushed to conda packages yet. This is the good way to install the software and be in sync with master.
