### ISSUE TITLE
Conversion of brw file to numpy array

### ISSUE THREAD

**Issue by robotechnics** [spyking-circus/spyking-circus#316]
Sorry, this is not an issue with this excellent package, just a question.
What is the best way to read a .brw file and convert it to a numpy array?.
I just want to convert a .brw file that contains the dead pixels of a CMOS sensor into an image (.tif for example).

The .brw file can be accessed here:  https://drive.google.com/file/d/1QI9dnjO92Ij05NhqNKvwfcLfb34uquUn/view?usp=drivesdk
Thank you very much in advance for your help.

**Comment by yger** [comment]
Not sure to understand what do you want... You want to turn a 3D matrix (the 2D array and the data in time) to an image?
