### ISSUE TITLE
Excessive memory use with peaks = both

### ISSUE THREAD

**Issue by sv-bio** [spyking-circus/spyking-circus#321]
Dear Pierre,

Could you help me to solve an issue with excessive memory use when parameter "peaks" is set to either "both" or "positive"? In this case 20+ Gb RAM is consumed and program terminates with the error  

| Step "clustering" failed for reason Command '['mpiexec', '-np', '4', 'spyking-circus-subtask', 'clustering', '/Path/To/My/Recordings/recording.h5', '4', '0', 'False', 'False']' returned non-zero exit status 9.!

or

| Step "whitening" failed for reason Command '['mpiexec', '-np', '2', 'spyking-circus-subtask', 'whitening', 'Path/To/My/Recordings/recording.h5', '2', '0', 'False', 'False']' returned non-zero exit status 1.!

When it is set to "negative" approx. 6.2 Gb RAM is used at worst and sorting goes smoothly. At the same time, log file tells that the number of positive spikes in my recording is about 100 times less e.g. 50 positive vs. 5000 negative / channel. What could be the reason and how would you suggest to overcome it?

OS: Debian 10
Spyking Circus: 1.0.4
recording length: 22 min
number of channels: 32
sampling rate: 30000 Hz

Sincerely,
Stan

**Comment by yger** [comment]
Sure, I'll have a look. It should work with previous version I guess, such as 1.0. And meanwhile, does it work it you add sort_waveforms = False in the [whitening] section of the .params file?

**Comment by yger** [comment]
Actually, I can not really reproduce the problem here. Is the dataset too big to be shared?

**Comment by sv-bio** [comment]
Dear Pierre,

I truncated my data set to 2.1 Gb (5 min recording) in an attempt to complete sorting with "both" and ran SC again. On the graph below you can see memory usage with either "both" or "negative"  settings. See also log file of "both" analysis to time match them.

![image](https://user-images.githubusercontent.com/58944642/100523408-ffc86a00-31b8-11eb-926c-03e497d35f7f.png)

[test_neg_pos.log](https://github.com/spyking-circus/spyking-circus/files/5611064/test_neg_pos.log)

It turns out that excess of usage starts with the following:
2020-11-28 12:45:04,797 DEBUG    [circus.clustering] Computing density estimations...

As you requested I've sent you the link to this fragment of recording via e-mail.

Thank you for help.
Stan

**Comment by yger** [comment]
Thanks for reporting, there was indeed a bug introduced in 1.0.4 for positive peaks. This has been patched in master (or you can avoid it by setting use_barycenter=False in [detection]. I also improved the HDF5 file wrapper, such that you can now read/write non-sorted channels mappings (assuming you are willing to accept overwriting in the hdf5 file). I'll keep digging to see how the memory usage behaves

**Comment by sv-bio** [comment]
Dear Pierre,
I set use_barycenter=False and memory usage decreased from 20 Gb to about 13 Gb. So I think this was in part an issue. By the way, do you think installation of HDF5 as you described in the [user manual](https://spyking-circus.readthedocs.io/en/latest/introduction/hdf5.html) will help to further resolve issue?
Sincerely,
Stan

**Comment by yger** [comment]
Actually, detecting both peak (positive and negative) should use twice more memory. So this is about right, isn't it? Regarding your HDF5 file, this is only useful if your hdf5 file have data NOT compressed, and will only speed up the filtering step (because all nodes will be able to write simultaneously). So I don't think this is a game changer here
