### ISSUE TITLE
bug/suggestion for automerge phase

### ISSUE THREAD

**Issue by SaraMati** [spyking-circus/spyking-circus#322]
currently, when two or more template with high similarity (and on the same electrode) get correctly merged, it creates a cluster with high refractory period violation, meaning there is usually a large peak in 0 or 1 ms bin of the autocorrelation. This is because the two or three templates got fitted to the same spikes, so we have spike times that are slightly different (<1 ms) and all of them are counted after merge. Can a line be added to the auto merge code to only select the spike time of the template with the best fit (i.e. lowest residue) to each spike if the spike time differences is less than 1 ms (of course, if the templates are all on the same electrode) ? 

this is an example of such fitting
![image](https://user-images.githubusercontent.com/12663563/100551626-dc9cc980-324f-11eb-97a8-f621c7d657fc.png)

and this is the autocorrelogram of the merged cluster 
![image](https://user-images.githubusercontent.com/12663563/100551889-a3fdef80-3251-11eb-8687-65a397e81d5c.png)

I know that in the main phase of sorting, the logic is that the spike is a sum of those templates. But in the auto merging phase, if the algorithm sees that there is more than 0.95 similarity (for example) and decides to merge those two clusters, there is no reason to keep both spike times when the difference is less than 1 ms and clearly it was one individual spike that got fitted to both.

**Comment by SaraMati** [comment]
in other words: the argument that a waveform such as the one above is a sum of two templates is always valid. but, if in the merging phase, the algorithm decides to merge those two templates, then there is no reason for it to keep both spike times! it should only keep the spike time of the template with the least residual.

**Comment by yger** [comment]
I agree, and I'll try to fix that in the meta merging GUI. If two templates are merged, then nearby spikes should be fused, if I understand correctly

**Comment by yger** [comment]
This has been done in master, with the clean_merging flag. If set to True, while merging a pair of templates, all spikes that are "duplicated", i.e. less than 0.5ms apart are clean, and only one is kept
