### ISSUE TITLE
ValueError hangs during filtering

### ISSUE THREAD

**Issue by MonkeyMetke** [spyking-circus/spyking-circus#326]
I'm encountering a bizarre inconsistent error during the filtering phase (first 2 sets of a batch ran to completion, later ones failed. Data formats+params are identical). 

The following Error appears during filtering (see attached SCerr_Traceback.txt):
[SCerr_Traceback.txt](https://github.com/spyking-circus/spyking-circus/files/5660525/SCerr_Traceback.txt)
_ValueError: could not broadcast input array from shape (57600000) into shape (0)_

The 57600000 is the size of the 30-sec chunks for my 64ch 30kHz RHD data. The error is thrown for each separate chunk during filtering. A concatenated binary file *_all_sc is successfully created in target folder (Overwrite is off), but the program hangs and never progresses past. 

Below are debug files for exemplar sets that Hang or Run to completion
[Archie_hangs.txt](https://github.com/spyking-circus/spyking-circus/files/5660593/Archie_hangs.txt)
[Archie_runs.txt](https://github.com/spyking-circus/spyking-circus/files/5660594/Archie_runs.txt)

Initial testing suggests I can bypass the error by manually changing no_edits Filtering to True and re-running, but it is unclear whether the results are complete/reliable. 
The fact that the binary output is created and manually proceeding past makes me think there's something obvious/silly I'm missing here. Any advice/assistance would be appreciated.

**Comment by yger** [comment]
Before going further, can you upgrade SC to latest version (1.0.6). This should be easy via pip or conda. Just because I made some fix in the RHD wrapper in 1.0.4, and maybe this solves your issue

**Comment by yger** [comment]
(if not too big, otherwise, please share the data/params/prb, since I do not use RHD myself...)

**Comment by MonkeyMetke** [comment]
The update doesn't seem to have helped, it just changed from a ValueError that hangs to a full Error with a non-zero exit status (see attached). 
[Archie_testErr.txt](https://github.com/spyking-circus/spyking-circus/files/5669086/Archie_testErr.txt)

Once again a concatenated binary *_all_sc file is successfully created. It is the exact same size as the one created before the update, but may be empty/corrupt (when I try the previous trick of manually updating the 'Started' noedits to 'True' it now errors out saying no templates are found)

Below are attached the params, probe. The prb was designed to have all nodes far enough to be independent (our array does not allow for spatial information about relative electrode positions).
[Archie_params.txt](https://github.com/spyking-circus/spyking-circus/files/5669149/Archie_params.txt)
[indep_grid64prb.txt](https://github.com/spyking-circus/spyking-circus/files/5669195/indep_grid64prb.txt)

The rhd file itself it too large (>1GB) but I am uploading to a Gdrive and will add a link to it as soon as it completes

**Comment by MonkeyMetke** [comment]
A Drive location with a few exemplar RHD files
https://drive.google.com/drive/folders/1kccC2QnyrYYQgUemb9Q7l4rlNMb-EEfC?usp=sharing

**Comment by yger** [comment]
Great. Can you also provide me a .prb mapping?

>

**Comment by yger** [comment]
The RHD wrapper is pretty basic, so I guess you must record something not handled by our current implementation. Is there somehting in the .rhd that makes it special. Are you recording extra values beside the channels?

**Comment by MonkeyMetke** [comment]
The file "indep_grid64prb.txt" in the above comment is the probe file (converted to txt, github refused to upload as a .prb)
https://github.com/spyking-circus/spyking-circus/files/5669195/indep_grid64prb.txt

We have parallel recording of digital TTL timing data and an analog behavioral signal, stored within the RHD as board_dig_in_data and board_adc_data, respectively.
The only other thing I can think of is that we process 2 subsets of data recorded discontinuously (same day/session but with some time between). Though the Circus has thus far dealt with and properly ordered/concatenated these files without issue.

**Comment by yger** [comment]
You mean that you were able to process such files with older version of the software? Because some other users complained about the RHD wrapper, and I made changes in version 1.0.4. Maybe this fixed one issue by creating one other.... So if you know what to do, please take the old version of the rhd wrapper https://github.com/spyking-circus/spyking-circus/blob/1.0.3/circus/files/rhd.py and copy it in the circus/files/ folder, erasing the old one. Let me know if this solves your issue

**Comment by yger** [comment]
This should be fixed in Master. At least, the RHD file you gave me is now loaded
