### ISSUE TITLE
Not all nodes can read/write the data file. Check path?

### ISSUE THREAD

**Issue by abhijithkrishnan93** [spyking-circus/spyking-circus#327]
I was using circus till yesterday. I re-installed it and the all nodes cant read/write error comes. I did a fresh conda install.
Running on fedora.

**Comment by yger** [comment]
Version is then the latest (1.0.6), and what is the .params? Are you sure you are in the right folder, launching it the way you used to launched it?

**Comment by abhijithkrishnan93** [comment]
I cant run on newer files. I tried to generate the params file by spyking-circus Data/data.dat and then the error came. 
On the older files (ones which have already been launched on once) it is working. I can still do spyking-circus Data_old/data.dat -r.
