### ISSUE TITLE
Check DISPLAY variable error

### ISSUE THREAD

**Issue by s-steinberg** [spyking-circus/spyking-circus#328]
Using version 1.0.6+5, preview mode can not be used. Apparently it's because I do not have DISPLAY variable in os.environ (Windows 10).
Could it be solved?

**Comment by yger** [comment]
I just made a patch in the master branch, the views should be back in windows. Let me know if this works

**Comment by s-steinberg** [comment]
Yes, it works! Thanks a lot.

**Comment by oibtech001** [comment]
Using version 1.1.0 with anaconda on mac, error: Preview mode can not be used, check DISPLAY variable
