### ISSUE TITLE
Error using rhd

### ISSUE THREAD

**Issue by restrepd** [spyking-circus/spyking-circus#337]
Hi Pierre,

I tried circus with the data from your manuscript, and I really like it! I then tried to run spyking-circus path/mydata.rhd using INTAN rhd data and I get this error reading the rhd data:

File "/Users/restrepd/anaconda3/envs/circus/lib/python3.6/site-packages/circus/files/rhd.py", line 312, in read_chunk
    local_chunk[:, count:count + t_slice] = self.data[block_slice].reshape(self.nb_channels, t_block_slice)[:, (s0-s):(s1-s)]
ValueError: cannot reshape array of size 1306 into shape (16,81)
----------------------------  Error  -----------------------------
| Step "whitening" failed for reason Command '['mpiexec', '-np', '8', 'spyking-circus-subtask', 'whitening', '/Users/restrepd/Documents/Projects/CaMKII_analysis/Spike_analysis/6251853931acetoethylben_180625_102911/6251853931acetoethylben_180625_102911.rhd', '8', '0', 'False', 'False']' returned non-zero exit status 1.!
------------------------------------------------------------------

I looked into the code, and in line 312 rhd.py has a problem assigning the rhd data to local_chunk. 

Thanks for your help.

Diego

**Comment by yger** [comment]
Can you try to use the file https://github.com/spyking-circus/spyking-circus/blob/1.0.3/circus/files/rhd.py and erase the one you have in /Users/restrepd/anaconda3/envs/circus/lib/python3.6/site-packages/circus/files/rhd.py. 
Let me know if this solves the problem. I made changes to the RHD wrapper because, for some users, there was some errors, but it seems that this is just creating new problems....

**Comment by restrepd** [comment]
Hi Pierre,

Thank you for the quick response. I tried the code you sent and I still get the error:


  File "/Users/restrepd/anaconda3/envs/circus/lib/python3.6/site-packages/circus/files/datafile.py", line 484, in get_data

    return self.read_chunk(idx, chunk_size, padding, nodes), self.t_start + idx*chunk_size

  File "/Users/restrepd/anaconda3/envs/circus/lib/python3.6/site-packages/circus/files/rhd.py", line 310, in read_chunk

    local_chunk[:, count:count + t_slice] = self.data[block_slice].reshape(self.nb_channels, t_block_slice)[:, (s0-s):(s1-s)]

ValueError: cannot reshape array of size 1306 into shape (16,81)

----------------------------  Error  -----------------------------

| Step "whitening" failed for reason Command '['mpiexec', '-np', '8', 'spyking-circus-subtask', 'whitening', '/Users/restrepd/Documents/Projects/CaMKII_analysis/Spike_analysis/6251853931acetoethylben_180625_102911/6251853931acetoethylben_180625_102911.rhd', '8', '0', 'False', 'False']' returned non-zero exit status 1.!

------------------------------------------------------------------

I played with the rhd.py code by forcing it to read chunks that are a length that can be read from rhd (multiples of self.SAMPLES_PER_RECORD=60). See my modifications in line 311 of the file in this link:

https://www.dropbox.com/s/hjxpf4ubn5fcjx7/rhd.py?dl=0

With this code circus does run, but it yields waveforms that are square (image enclosed). Likely what I am doing is truncating the records causing circus to identify some square wave forms.

However, I think that modifying the code along these lines may be a way to solve the problem. What I should do is to assign the correct residual length of data to local_chunk in line 328. Does this make sense?

By the way, when I subtract one channel as a reference channel I get an additional error in write_chunk, and you will see the change I made in the code in line 365. However, I get the same square waves.

Incidentally, my rhd data are not the best, but when I process it with wave_clus I do get normal looking wave forms.

I hope this helps. I am newbie for python, but I have done a lot of programming in MATLAB in the past. I use wave_clus, but I would like to migrate to circus/python.

Best regards,

Diego



Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
If the RHD file is not too big, can you share it with me (alongside with the .params and .prb)? It will help to troubleshoot...

**Comment by restrepd** [comment]
Here it is:

https://www.dropbox.com/sh/u2wv0w4swrf9zp3/AADPW8uNCkwW5hTLm8DwPNQ5a?dl=0

If this is too big (2.87 Gbytes) I will find a shorter file.

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Fine, no problem with the file size, I'll have a look as soon as possible

**Comment by yger** [comment]
Actually, the file you gave me has already been filtered, am I right? And because the wrapper for RHD seems to be buggy, can you send me the raw file, without filtering?

**Comment by restrepd** [comment]
Hi Pierre,

That file was the file that was saved by INTAN without software fitters. The recording was hardware filtered 1 Hz – 3 kHz. I will look at the settings using my MATLAB rhd wrapper.

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
ok, perfect then, this is what I need! I'll try to debug the RHD wrapper asap

**Comment by yger** [comment]
Actually, INTAN v2 should work with master, but your file is v1, so I'll investigate (I'm not an intan expert here as you can guess)

**Comment by restrepd** [comment]
I would be glad to help because I have a lot of experience with those files in MATLAB.

D

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yger** [comment]
Actually, when using the RHD wrapper in python, what do the data look like? Because on my machine, this looks like crap. So are you sure this is not possible the file has been filtered (onsite by Spyking circus) and thus corrupted? In your .params, I can see that filtered and remove median flags are set to True, so an attempt has been made. If so, back to my question concerning the raw data, unaltered. But if you can open this file nicely with MATLAB, please send me the script

**Comment by restrepd** [comment]
Yes, the way they save the data is a pain. It has to be read in chunks of self.SAMPLES_PER_RECORD. It would be easier if they had a raw sequence of int16.

Here is my Matlab code in case it helps (sorry about the syntax, I learned to program with algol/fortran using for loops!). In this code I read “trials” of 9 seconds (which_protocol==1). In the drta_read_Intan_RHD2000_header I figure the blocks of records I have to read for each trial (see line 340). Then I use these offsets in drgGetTraceDataRHD to read the blocks for each trial (drtaGetTraceDataRHD.m, line 60).

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Nothing is attached :-(. I'm well aware of the format, with non contiguous blocks, and I used the scripts from here (http://intantech.com/downloads.html?tabSelect=Software&yPos=0). The one for python, provided by the manufacturer, is not able to correcly display your data, this is why I suspect something could be wrong. I'll try the one with MATLAB

**Comment by restrepd** [comment]
Here is the first second of the data:

https://www.dropbox.com/s/hyp3poq1xixw60u/from_circus.csv?dl=0

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
My computer removed the file because it was csv. Here is a link:
https://www.dropbox.com/s/hyp3poq1xixw60u/from_circus.csv?dl=0
D

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
I got the csv, and I can see the traces, thanks. But I was talking about your MATLAB script :-)

**Comment by restrepd** [comment]
The MATLAB script code does look like crap, but it works beautifully (lol!). But taking it out of context makes it difficult to use.

Here is the context where I use the code successfully:

https://github.com/restrepd/drta

D

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
Here is a smaller rhd file with decent spikes:

https://www.dropbox.com/s/x7qphjetf14nuir/MsFControl_251386_10302020_201030_170030.rhd?dl=0

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
I've tried the MATLAB toolbox also, and same as python, data looks like crap (http://intantech.com/downloads.html?tabSelect=Software&yPos=0). Your script is launched on the file you uploaded in the Dropbox? How can it be then that the "official" RHD wrapper can not read it? Please double check the upload, since as said, SC may have altered the file if launched with a faulty wrapper...

**Comment by restrepd** [comment]
My code is taken directly from the INTAN MATLAB RHD file reader (Version 2.01, October 13, 2017):

http://intantech.com/downloads.html?tabSelect=Software&yPos=0

Here is a snapshot of the data read with drta for the new rhd file I sent after filtering for spikes (500 to 3000 Hz):

https://www.dropbox.com/s/x7qphjetf14nuir/MsFControl_251386_10302020_201030_170030.rhd?dl=0

And a snapshot of the raw data read with drta and with the download of INTAN software (downloaded 5 minutes ago, electrode 6). They are identical.

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
Merci!

D

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
I can see nice spikes with the master branch in the new file you sent me, so I guess my patch is working! Please upgrade the software with git (if you know how to do that), otherwise copy paste the rhd.py file, and it should work. The file you uploaded first (2.9Go) is likely to be corrupted then

**Comment by restrepd** [comment]
Great!

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
Hi Pierre,

I do not know how to git there. Do I just go to site_packages, do git init and then git pull with your circus url?

At any rate since I did not know how to do it I went the long way and deleted the conda environment and re-installed circus. Yet, I still get square waveforms when I process the file with the nice spikes ☹.

Here is a snapshot.

Any hints?

Thanks!

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Reinstalling circus will not change anything, since conda only installed the last RELEASED version, and not the cutting edge files from the master branch. To do so, in your conda env, try
>> pip install --upgrade Https://GitHub.com/spyking-circus/spyking-circus/archive/master.zip

Then start with the fresh new file you sent me (and not the one that has the square waveforms, since SChas corrupted it)

**Comment by restrepd** [comment]
Thanks, I will try this today.

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
Hi Pierre,

I upgraded as you indicated below, I deleted all files and brought in the original rhd file with the nice spikes, I used a new .params file enclosed. I get no templates. Any hints?


(circus) restrepd@diegoreeposmbp2 probes % spyking-circus /Users/restrepd/Documents/Projects/UNO/MsF_251386_10302020/MsFControl_251386_10302020_201030_170030.rhd



##################################################################

#####             Welcome to the SpyKING CIRCUS              #####

#####                      (0+unknown)                       #####

#####             Written by P.Yger and O.Marre              #####

##################################################################





File          : /Users/restrepd/Documents/Projects/UNO/MsF_251386_10302020/MsFControl_251386_10302020_201030_170030.rhd

Steps         : filtering, whitening, clustering, fitting, merging

Number of CPU : 8/16

Parallel HDF5 : False

Shared memory : True

Hostfile      : /Users/restrepd/spyking-circus/circus.hosts



##################################################################





-------------------------  Informations  -------------------------

| Number of recorded channels : 16

| Number of analyzed channels : 16

| File format                 : RHD

| Data type                   : uint16

| Sampling rate               : 20000 Hz

| Duration of the recording   : 20 min 46 s 248 ms

| Width of the templates      : 3 ms

| Spatial radius considered   : 50 um

| Threshold crossing          : negative

------------------------------------------------------------------

-------------------------  Informations  -------------------------

| Using only 8 out of 16 local CPUs available (-c to change)

------------------------------------------------------------------

Filtering with a Butterworth filter (order 3) in [300, 9500] Hz

100%|████████████████████████████████████|[00:13<00:00,  2.31s/it]

Analyzing data to get whitening matrices and thresholds...

Found 30s to compute the whitening matrix...

Because of whitening, need to recompute the thresholds...

Searching spikes to construct the PCA basis...

100%|████████████████████████████████████|[00:09<00:00,  4.83s/it]

Found 3361 waveforms over 12800 requested

-------------------------  Informations  -------------------------

| A basis with 5 dimensions has been built

------------------------------------------------------------------

Searching isolated random spikes to sample amplitudes...

100%|████████████████████████████████████|[00:41<00:00, 41.14s/it]

Found 13610 spikes over 128000 requested

Estimating amplitudes distributions...

Smart Search of good isolated spikes for the clustering (1/3)...

100%|█████████████████████████████████|[00:00<00:00, 15887.52it/s]

Found 13610 isolated spikes over 128000 requested (0 rejected)

Computing density estimations...

Searching random spikes to refine the clustering (2/3)...

100%|████████████████████████████████████|[00:41<00:00, 41.08s/it]

Found 11975 spikes over 128000 requested

Refining density estimations...

Searching random spikes to refine the clustering (3/3)...

100%|████████████████████████████████████|[00:40<00:00, 40.50s/it]

Found 8937 spikes over 128000 requested

Refining density estimations...

Running density-based clustering...

100%|██████████████████████████████████|[00:00<00:00, 5526.09it/s]

-------------------------  Informations  -------------------------

| Number of clusters found : 0

| Number of local merges   : 0 (method nd-bhatta, param 2)

| Not enough spikes gathered: -put safety_space=False?

|                             -remove smart_search?

------------------------------------------------------------------

Estimating the templates with the median-raw procedure ...

100%|███████████████████████████████████|[00:00<00:00, 380.00it/s]

-------------------------  Informations  -------------------------

| Number of global merges    : 0

| Number of mixtures removed : 0

------------------------------------------------------------------

Computing optimal amplitudes for the templates...

  0%|                                            |[00:00<?, ?it/s]

100%|████████████████████████████████████|[00:00<00:00,  4.84it/s]

Pre-computing the overlaps of templates...

100%|███████████████████████████████████|[00:00<00:00, 694.94it/s]

No templates present. Redo clustering?

----------------------------  Error  -----------------------------

| No results file found: either no templates found or no fitting

------------------------------------------------------------------

(circus) restrepd@diegoreeposmbp2 probes %

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Ok, but at least, when you do 

>> spyking-circus mydata.rhd -p 

do you see normal traces, don't you? I'll double check on my side then, with your small example

**Comment by yger** [comment]
But the file you gave me is strange, at least loaded by SC. While it claims that it lasts 20min, all channels are full of 0s after 63s. Is it normal? Is it a bug of the wrapper or of the file itself?
How did you export the data? Because 0s will mess around with the software, as you are observing...

**Comment by restrepd** [comment]
Hi Pierre,

That is a problem with SC reading the rhd file. Here is the end of the file read with my drta code (20 minutes after the start). I bet the problem is that rhd files have digital input intertwined (mostly zeros). Indeed this file saves digital data with sync from FLIR cameras and digital input from another program.

Take a look at my code that reads separately the amplifier channels, the adc channels and the digital input channels:


    %Read amplifier channels

    if (num_amplifier_channels > 0)

        fseek(fid,handles.draq_d.offset_start_ch(i),'bof');

        amplifier_data(:, amplifier_index:(amplifier_index + num_samples_per_data_block - 1)) = fread(fid, [num_samples_per_data_block, num_amplifier_channels], 'uint16')';

    end



    if (num_board_adc_channels > 0)

        fseek(fid,handles.draq_d.offset_start_adc(i),'bof');

        board_adc_data(:, board_adc_index:(board_adc_index + num_samples_per_data_block - 1)) = fread(fid, [num_samples_per_data_block, num_board_adc_channels], 'uint16')';

    end



    if (num_board_dig_in_channels > 0)

        fseek(fid,handles.draq_d.offset_start_dig(i),'bof');

        board_dig_in_raw(board_dig_in_index:(board_dig_in_index + num_samples_per_data_block - 1)) = fread(fid, num_samples_per_data_block, 'uint16');

    end



    amplifier_index = amplifier_index + num_samples_per_data_block;

    board_adc_index = board_adc_index + num_samples_per_data_block;

    board_dig_in_index = board_dig_in_index + num_samples_per_data_block;


By the way, this time SC did process the file because when I read the rhd file it has today’s date and it is already filtered.

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
Yes, I do see for the first second the spikes in spyking-circus mydata.rhd -p, but the GUI does not allow me to change the “set time” to see what SC finds at say 1200 seconds…

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
To set time in the preview mode, you just need to do

>> spyking-circus mydata.rhd -p -s XX

Where XX is the t_start

**Comment by restrepd** [comment]
Great! I see at that point it becomes zero. It should not.

D

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
Thanks, in SC the traces become zero at 63 sec. With drta they last to the end of the session (20 mins).

D

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Please upgrade again, I think I solved the issue with the wrapper. Now I can see everything, and the sorting works :-)

**Comment by restrepd** [comment]
Dear Pierre,

I am still having the same problem. When I run spyking-circus path/ /MsF_251386_10302020/MsFControl_251386_10302020_201030_170030.rhd -p -s 63
I get a truncated plot shown in the image enclosed. I placed import pdb; pdb.set_trace() in line 390 of rhd.py. The problem is that for some reason the for loop only goes to count = 960, it does not fill local_chunk for the full 24000 points.

Indeed, CS stops there. When I run the full spyking-circus path/ /MsF_251386_10302020/MsFControl_251386_10302020_201030_170030.rhd I get no templates and if I then open the file with my code (drta) the record is filtered up to trial 7 (each trial is 9 sec, 7x9=63), and after that it is not filtered indicating that CS stops processing slightly after 63 seconds. The problem must be that for some reason self.data is not getting the input correctly.

Thanks!

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Have you upgraded again with the pip command? Because I solved the problem yesterday, and it should work. If not, then either you have a conflicting install, either be sure that the file circus/files/rhd.py is the same as the one here https://github.com/spyking-circus/spyking-circus/blob/master/circus/files/rhd.py
(the key point is L304, to have len(self.data) instead of self.size)

**Comment by restrepd** [comment]
Hi Pierre,

I did upgrade, but let me double check carefully.

Merci,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Assuming your install did not change, check the file /Users/restrepd/anaconda3/envs/circus/lib/python3.6/site-packages/circus/files/rhd.py, and see L304 if it has the change I mentioned or not. AND be also sure you start again with a fresh new file, because, again, SC has altered it when you did your sorting. So use the original raw file

**Comment by mstimberg** [comment]
Just as a general comment (I can't help at all with the actual issue). If you install from master with the following command instead of the one ending in `.../archive/master.zip` then spyking-circus will know its version number and you can check it against the latest commit on master to be sure you have the correct version (only works if you have `git` installed):
```bash
$ pip install --upgrade git+git://github.com/spyking-circus/spyking-circus.git
```
E.g. right now it should display `1.0.6+21.g464af58f` as its version (21st commit after the 1.0.6, git commit hash `464af58f`), and you can check here that this is indeed the latest commit: https://github.com/spyking-circus/spyking-circus/commits/master

**Comment by restrepd** [comment]
Thanks! The problem was that the rhd.py file had not been updated.

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by yger** [comment]
Thanks Marcel for pointing that out, I'll stop to recommend using the pip syntax without git. I just find it convenient since most is the windows users do not have git installed, but here I have no excuse 👍

**Comment by restrepd** [comment]
Hi Pierre,

I wanted to thank you for your help.

Could you send me the instructions on how to update SC with git? I do use git, so you do not need to send detailed instructions on how to set it up. Also, the MATLAB GUI is not working, and I do not find .bash_profile or .bashrc in the circus env. Should I make a new file with one of those names and save somewhere in the circus env?

I like phy, but I would like to also use the MATLAB GUI (I do not find a % refractory period in phy).

Best regards,

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420

**Comment by restrepd** [comment]
Never mind about the question on how to launch the matlab GUI. My Mac is macOS BigSur, and I had to edit .zshrc.

It is working now.

Diego

Diego Restrepo, PhD
Professor of Cell and Developmental Biology
https://www.restrepolab.org/
University of Colorado Anschutz Medical Campus
Department of Cell and Developmental Biology
MS 8108
Bldg RC1 South, Room L18-11119
12801 E 17th Ave
Aurora, CO 80045

Tel: 303-724-3405
Fax:303-724-3420
