### ISSUE TITLE
Can't get through first step of Quickstart

### ISSUE THREAD

**Issue by slceto** [spyking-circus/spyking-circus#338]
Hi,

I am trying to get started with SC but I am not able to follow the Quickstart guide, as in the first step it says to run `>> spyking-circus.py path/mydata.extension`, but there is no such .py file in the directory (I get a 'spyking-circus.py' is not recognized error). When I try just running the algorithm with `spyking-circus path\mydata.extension` (with my specific path and nwb file) I get this:

```Traceback (most recent call last):
  File "C:\Users\slcet\anaconda3\envs\circus\Scripts\spyking-circus-script.py", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus==1.0.6', 'console_scripts', 'spyking-circus')())
  File "C:\Users\slcet\anaconda3\envs\circus\Scripts\spyking-circus-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\importlib_metadata\__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "C:\Users\slcet\anaconda3\envs\circus\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\circus\scripts\launch.py", line 20, in <module>
    import h5py
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed: The specified procedure could not be found.
```

I installed following the conda instructions on Windows 10, and spyking-circus 1.0.6 appears in my circus environment when I do `conda list`. I'm pretty new to Python, so I may have missed some implied step, but any help would be greatly appreciated!

**Comment by yger** [comment]
Looks like a package is not properly installed. Can you type

>> conda install h5py ?

I'll try to have a look, but the command to launch the software (assuming it is properly installed) is

>> spyking-circus YOURDATAFILE

**Comment by slceto** [comment]
Thanks for the quick replay. I tried both the install and upgrade commands and it says `All requested packages already installed`, and I get the same ImportError as before when running `spyking-circus MYDATAFILE`.

In my conda list, the full line is
`spyking-circus 1.0.6 py36_0 spyking-circus`

**Comment by yger** [comment]
This is too modern. You should have a 2.xx version
Try to force such a version. Maybe with

conda install -c anaconda h5py

Otherwise remove h5py, install it with such a command, and then reinstall spyking-circus if needed (it might be automatically removed when removing h5py)

I'll see the exact procedure on windows, but I guess this is the problem

**Comment by yger** [comment]
Did you manage to solve your issue? Because here, in fact, on Win10 with a fresh install, everything works smoothly even with h5py 3.XX

**Comment by yger** [comment]
These are my lines for h5py
h5py                      3.1.0           nompi_py36hf359dfe_100    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge

If you do not have the same, try
>> conda install h5py hdf5 -c conda-forge

**Comment by slceto** [comment]
Yes, I had the same lines for h5py and hdf5 in mine. I tried to do the ` -c anaconda h5py` but it gave me an unauthorized certificate error. I'm doing a clean install of Anaconda now, so I'll try again from scratch.

When I did the `(circus) >> conda install -c intel mpi4py` step I didn't get any message, so I ended up installing spyking-circus without downloading and installing the Microsoft MPI. I did install the MPI after spyking-circus, but maybe doing it out of order messed things up.

**Comment by slceto** [comment]
Okay so after reinstalling Anaconda I now get a different error

```Traceback (most recent call last):
  File "C:\Users\slcet\anaconda3\envs\circus\Scripts\spyking-circus-script.py", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus==1.0.6', 'console_scripts', 'spyking-circus')())
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\pkg_resources\__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\pkg_resources\__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\pkg_resources\__init__.py", line 2447, in load
    return self.resolve()
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\pkg_resources\__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\circus\scripts\launch.py", line 30, in <module>
    from circus.shared.files import data_stats
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\circus\shared\__init__.py", line 1, in <module>
    import matplotlib
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\matplotlib\__init__.py", line 205, in <module>
    _check_versions()
  File "C:\Users\slcet\anaconda3\envs\circus\lib\site-packages\matplotlib\__init__.py", line 190, in _check_versions
    from . import ft2font
ImportError: DLL load failed: The specified module could not be found.```

**Comment by yger** [comment]
You followed exactly the steps described here https://spyking-circus.readthedocs.io/en/latest/introduction/windows.html ?
You are using Win10, and send the the full details of your conda list in the circus environment. But this is strange then, I never saw such error... Sorry for that

**Comment by slceto** [comment]
Yes, I followed the same steps with the exception that I already had the Microsoft MPI installed from the previous attempt. Here is my full env list:

```# packages in environment at C:\Users\slcet\anaconda3\envs\circus:
#
# Name                    Version                   Build  Channel
blosc                     1.21.0               h0e60522_0    conda-forge
ca-certificates           2020.12.5            h5b45459_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
certifi                   2020.12.5        py36ha15d459_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py36he2d232f_2    conda-forge
freetype                  2.9                      vc14_4  [vc14]  intel
h5py                      3.1.0           nompi_py36hf359dfe_100    conda-forge
hdf5                      1.10.6          nompi_he0bbb20_101    conda-forge
icc_rt                    2020.3                intel_311    intel
icu                       64.2                 he025d50_1    conda-forge
impi_rt                   2021.1.1               intel_88    intel
intel-openmp              2020.3             h57928b3_311    conda-forge
intelpython               2021.1.1                      1    intel
jpeg                      9d                   h8ffe710_0    conda-forge
kiwisolver                1.3.1            py36he95197e_1    conda-forge
libblas                   3.9.0                     7_mkl    conda-forge
libcblas                  3.9.0                     7_mkl    conda-forge
liblapack                 3.9.0                     7_mkl    conda-forge
libpng                    1.6.36                   vc14_2  [vc14]  intel
matplotlib                3.1.1                    py36_2    intel
mkl                       2020.4             hb70f87d_311    conda-forge
mkl_fft                   1.2.0            py36h4f3e613_1    conda-forge
mpi4py                    3.0.0                    py36_6    intel
numpy                     1.17.5           py36hc71023c_0    conda-forge
openssl                   1.1.1i               h8ffe710_0    conda-forge
pandas                    1.1.5            py36he38d939_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pip                       20.3.3           py36haa95532_0
psutil                    5.8.0            py36h68aa20f_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py36h6538335_4    conda-forge
pyreadline                2.1             py36h9f0ad1d_1002    conda-forge
python                    3.6.12               h5500b2f_2
python-blosc              1.10.1           py36h2c819d0_0    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
qt                        5.9.7                h506e8af_3    conda-forge
scipy                     1.3.1            py36ha68da19_2    intel
setuptools                51.1.2           py36haa95532_4
sip                       4.19.8           py36h6538335_0
six                       1.15.0             pyh9f0ad1d_0    conda-forge
spyking-circus            1.0.6                    py36_0    spyking-circus
sqlite                    3.33.0               h2a8f88b_0
statsmodels               0.12.1           py36h6434af4_2    conda-forge
tcl                       8.6.9           vc14he774522_27  [vc14]  intel
tk                        8.6.9            vc14h57a849e_8  [vc14]  intel
tqdm                      4.56.0             pyhd8ed1ab_0    conda-forge
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py36h7fe50ca_0
zlib                      1.2.11               h62dcd97_4

**Comment by yger** [comment]
Can you do 
>> conda upgrade matplotlib -c anaconda

**Comment by slceto** [comment]
The upgrade seemed to get me a bit further, but now I get a red text error saying `Not all nodes can read/write the data file. Check path?` I also tried `spyking-circus help -i` to check that my nwb file was still supported and it actually gave the same red text error.

**Comment by yger** [comment]
Ok, so now this is (almost) working! Concerning nwb, I never used such file format. My understanding is that this is simply an hdf5 file with a special structure, but this has never been tested by SC. The error message you are facing therefore simply states that the probe or file path are wrong, or maybe the NWB wrapper/syntax (possible since never tested). Do you have a small test file you could provide as nwb to help me understand how this is structured?

**Comment by slceto** [comment]
Okay, so the recordings were acquired with a NeuroNexus Smartbox Pro, which produces xdat files. I used their Allego software to convert to the nwb format, and it generated two files that are linked below. I've been using the .nwb file only in my attempts to run SC

https://drive.google.com/file/d/19YDgtc1Kk1BatGXRxXPokAHtSdJuB90U/view?usp=sharing

I do wonder why the `spyking-circus help -i` command doesn't work, as it seems that would be independent of whatever file type I'm trying to sort.

**Comment by slceto** [comment]
[demo_probe_A4x8.zip](https://github.com/spyking-circus/spyking-circus/files/5835398/demo_probe_A4x8.zip)

(my probe file)

**Comment by yger** [comment]
Sadly, I am not able to open the .nwb with h5py, or even with the nwb python wrapper. Looks like something is not correct, at least the file is not a valid hdf5 file (while it should...). Are you able to load it with a command line, and if so how?

**Comment by yger** [comment]
And regarding the help command, you are right, a bug has been introduced, I'll fix that asap

**Comment by slceto** [comment]
As I only converted the file to nwb to try to run SC on it, I hadn't tried doing anything else with it. I just added the pynwb package and tried to validate the file, and it gave me this error: `OSError: Unable to open file (bad object header version number)`.

I'll have to do some more digging to figure out what is going on, and I'll see tomorrow if I can get some test data from in other formats to run now that the I can at least initiate the algorithm. Thanks for all your help thus far!

**Comment by slceto** [comment]
I did manage to get one of the ground truth data files to run all the way through SC and phy, so that was good. 

Still haven't gotten my NWB files to work. NeuroNexus said there is a known issue with the conversion of their files to NWB that will be fixed soon. I guess the original issue of not being able to run the algorithm at all can be closed, though.
