### ISSUE TITLE
Qt error during conda installation (Windows)

### ISSUE THREAD

**Issue by dimokaramanlis** [spyking-circus/spyking-circus#339]
Hi,

I am trying to install SpykingCircus in a Windows 10 PC with Anaconda (conda version 4.9.2). However, package installation doesn't finish because of the following error:

"...
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'conda-forge::qt-5.9.7-h506e8af_3'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::qt-5.9.7-h506e8af_3
location of failed script: ~\Anaconda3\envs\circus\Scripts\.qt-post-link.bat
"
Do you know what might be the issue?

**Comment by yger** [comment]
Sadly not, never encountered such as issue. Using google, I can see that such an error seems to be related to matplotlib and qt. Maybe try in the env

>> conda install matplotlib numpy

and if this is working, then after

>> conda install -c conda-forge -c intel -c spyking-circus spyking-circus

**Comment by dimokaramanlis** [comment]
Thanks for the quick reply! 

I didn't follow the Windows-specific tutorial for installation initially, that was the problem that is now solved! Later, I encountered the same issue as https://github.com/spyking-circus/spyking-circus/issues/338, but it was solved by following the information there.
