### ISSUE TITLE
Problem with clustering 

### ISSUE THREAD

**Issue by cmarneffe** [spyking-circus/spyking-circus#348]
Hello, 
I try to run spyking-circus over a .dat file but I get this error :

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 3000 RUNNING AT P-TMULLE-STU14
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 12292 RUNNING AT P-TMULLE-STU14
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 12108 RUNNING AT P-TMULLE-STU14
=   EXIT STATUS: -1 (ffffffff)
| Step "merging" failed for reason Command '['mpiexec', '-np', '4', 'spyking-circus-subtask', 'merging', 'F:\\Clustering\\Gluk2_awake\\2020-09-22\\CM_200922_151440\\amplifier.dat', '4', '0', 'False', 'None']' returned non-zero exit status 4294967295.!

It was working on similar files but it suddenly shows this error and I do not understand why. Here is the log file : 
[amplifier.log](https://github.com/spyking-circus/spyking-circus/files/6151185/amplifier.log)

Could you please help? 

Thank you in advance, 

CM

**Comment by sv-bio** [comment]
One of our Windows 10 machines have exact same termination code. Although it does not affect anything, how did you solve it?

**Comment by cmarneffe** [comment]
I am also working on windows 10. I attributed that error to the location from which I was reading the file: from a network while I was usually working from an external drive. I closed the issue because I thought this was it but actually I got that error again this morning. I am  not sure that it doesn't affect the clustering: it also make the conversion step very long. 

Any other input on this matter would be great.
CM

**Comment by yger** [comment]
I'll have a look. Based on the logs, the error is happening at the end, as a bad termination of the program, but indeed this should not affect anything since this is not a real "crash", but rather a improper handling of the exit. I guess this can be fixed, so I'll dig asap

**Comment by sv-bio** [comment]
I've read somewhere that it could be related to backslashes that are used in Windows. One could try forward slashes in file path.
