### ISSUE TITLE
Reading numpy file

### ISSUE THREAD

**Issue by m-bellv** [spyking-circus/spyking-circus#352]
Hello,

I am trying to use the python GUI for Spyking. The software with which I collected my recordings is not an acceptable file format that is readable by Spyking, so I created a .npy file containing a dict which has a str class array of electrophysiological data as well as a float class value titled sampling_rate.

When I try running this file with Spyking I keep getting the error:
The parameters for NUMPY file format are:
| 
| -- sampling_rate -- <class 'float'> [** mandatory **]

Despite the fact that I have the sampling_rate saved as a float class. I'm not sure why this isn't working.
Is there an example of how to save a .npy file to include the data as well as sampling frequency in a way that will be readable with Spyking?

**Comment by yger** [comment]
Spyking circus can read a numpy array, but only if the array is a 2D matrix with nb_channels rows and nb_timesteps. The sampling_rate field should be provided in the .params file, in the [data] section
sampling_rate = 20000 for example
