### ISSUE TITLE
How to deal with large amplitude noise in waveform cluster

### ISSUE THREAD

**Issue by Tywang-720** [spyking-circus/spyking-circus#356]
Hi there!

**I just had a test run ,the results are nice for an auto-sorting software, but I see some large noises polluting waveforms**
Please see the picture below. It's happening on a wide scale.
![0512-large noise](https://user-images.githubusercontent.com/82949092/117964283-01937d80-b354-11eb-9786-22aa94c869f3.png)

The noises are probably results from the licking activity of the mouse. Since they have different amplitudes across channels, I found they are difficult to reference out. 

**Is there any built-in function of SpykingCircus that could mark these obvious noise as invalid?** To my surprise Phy2 doesn't seem to have such function like Offlinesorter (user could draw a line in the window and reject every waveform that gets crossed with that line, please tell me if I'm wrong).

**Perhaps I could do this curation on my own, it would be of great help if there're some example MATLAB or Python scripts** that show how to load the shape of every waveform in each cluster, and then save the results back to Phy format.

**Or, is there some specific parameters of SpykingCircus that could be adjusted to make these results better?**

Here's my parameters for the picture above. I didn't change much from the default settings. The probe has 8 shanks and 128 channels.

Thanks in advance! Any advice would be appreciated.

[data]
file_format    = MDA           # Can be raw_binary, openephys, hdf5, ... See >> spyking-circus help -i for more info
stream_mode    = None       # None by default. Can be multi-files, or anything depending to the file format
mapping        = E:/C57009d1L12.prb           # Mapping of the electrode (see http://spyking-circus.rtfd.org)
suffix         =           # Suffix to add to generated files, if needed
overwrite      = True       # Filter or remove artefacts on site (if write access is possible). Data are duplicated otherwise
parallel_hdf5  = True       # Use the parallel HDF5 feature (if available)
output_dir     =            # By default, generated data are in the same folder as the data.

sampling_rate = 30000
dtype_offset = auto
data_offset = 0
gain = 0

[detection]
radius         = auto       # Radius [in um] (if auto, read from the prb file)
N_t            = 3          # Width of the templates [in ms]
spike_thresh   = 6          # Threshold for spike detection
peaks          = both   # Can be negative (default), positive or both
dead_channels  =            # If not empty or specified in the probe, a dictionary {channel_group : [list_of_valid_ids]}

[filtering]
cut_off        = 300, auto  # Min and Max (auto=nyquist) cut off frequencies for the band pass butterworth filter [Hz]
filter         = True       # If True, then a low-pass filtering is performed
remove_median  = False      # If True, medians over all channels within shanks are substracted (movement artifacts)
common_ground  =            # If you want to use channels as ground within shanks {channel_group : ground_channel}

[triggers]
trig_file      =            # External stimuli to be considered as putative artefacts [in trig units] (see documentation)
trig_windows   =            # The time windows of those external stimuli [in trig units]
trig_unit      = ms         # The unit in which times are expressed: can be ms or timestep
clean_artefact = False      # If True, external artefacts induced by triggers will be suppressed from data
dead_file      =            # Portion of the signals that should be excluded from the analysis [in dead units]
dead_unit      = ms         # The unit in which times for dead regions are expressed: can be ms or timestep
ignore_times   = False      # If True, any spike in the dead regions will be ignored by the analysis
make_plots     = 'jpg'           # Generate sanity plots of the averaged artefacts [Nothing or None if no plots]

[whitening]
spatial        = True       # Perform spatial whitening
max_elts       = 1000       # Max number of events per electrode (should be compatible with nb_elts)
nb_elts        = 0.8        # Fraction of max_elts that should be obtained per electrode [0-1]
output_dim     = 5          # Can be in percent of variance explain, or num of dimensions for PCA on waveforms

[clustering]
extraction     = median-raw # Can be either median-raw (default) or mean-raw
sub_dim        = 10         # Number of dimensions to keep for local PCA per electrode
max_elts       = 10000      # Max number of events per electrode (should be compatible with nb_elts)
nb_elts        = 0.8        # Fraction of max_elts that should be obtained per electrode [0-1]
nb_repeats     = 3          # Number of passes used for the clustering
smart_search   = True       # Activate the smart search mode
merging_method = nd-bhatta  # Method to perform local merges (distance, dip, folding, nd-folding, bhatta, nd-bhatta)
merging_param  = default    # Merging parameter (see docs) (3 if distance, 0.5 if dip, 1e-9 if folding, 2 if bhatta)
sensitivity    = 3          # Single parameter for clustering sensitivity. The lower the more sensitive
cc_merge       = 0.95       # If CC between two templates is higher, they are merged
dispersion     = (5, 5)     # Min and Max dispersion allowed for amplitudes [in MAD]
fine_amplitude = True       # Optimize the amplitudes and compute a purity index for each template
make_plots     = jpg           # Generate sanity plots of the clustering [Nothing or None if no plots]

[fitting]
amp_limits     = (0.3, 5)   # Amplitudes for the templates during spike detection [if not auto]
amp_auto       = True       # True if amplitudes are adjusted automatically for every templates
collect_all    = False      # If True, one garbage template per electrode is created, to store unfitted spikes
ratio_thresh   = 0.9        # Ratio of the spike_threshold used while fitting [0-1]. The lower the slower
mse_error      = False      # If True, RMS is collected over time, to assess quality of reconstruction

[merging]
erase_all      = True       # If False, a prompt will ask you to remerge if merged has already been done
cc_overlap     = 0.75       # Only templates with CC higher than cc_overlap may be merged
cc_bin         = 2          # Bin size for computing CC [in ms]
default_lag    = 5          # Default length of the period to compute dip in the CC [ms]
auto_mode      = 0.75       # Between 0 (aggressive) and 1 (no merging). If empty, GUI is launched
remove_noise   = True       # If True, meta merging will remove obvious noise templates (weak amplitudes)
noise_limit    = 0.75       # Amplitude at which templates are classified as noise
sparsity_limit = 0          # Sparsity level (in percentage) for selecting templates as putative noise (in [0, 1])
time_rpv       = 5          # Time [in ms] to consider for Refraction Period Violations (RPV) (0 to disable)
rpv_threshold  = 0.02       # Percentage of RPV allowed while merging
merge_drifts   = True       # Try to automatically merge drifts, i.e. non overlapping spiking neurons
drift_limit    = 1          # Distance for drifts. The higher, the more non-overlapping the activities should be
clean_merging  = False      # When templates are merged, automatically remove spike duplicated (less than 0.5ms appart)

[converting]
erase_all      = True       # If False, a prompt will ask you to export if export has already been done
export_pcs     = prompt     # Can be prompt [default] or in none, all, some
export_all     = False      # If True, unfitted spikes will be exported as the last Ne templates
sparse_export  = True       # For recent versions of phy, and large number of templates/channels
prelabelling   = False      # If True, putative labels (good, noise, best, mua) are pre-assigned to neurons
rpv_threshold  = 0.05       # Percentage of RPV allowed while labelling neurons as good neurons

[validating]
nearest_elec   = auto       # Validation channel (e.g. electrode closest to the ground truth cell)
max_iter       = 200        # Maximum number of iterations of the stochastic gradient descent (SGD)
learning_rate  = 1.0e-3     # Initial learning rate which controls the step-size of the SGD
roc_sampling   = 10         # Number of points to estimate the ROC curve of the BEER estimate
test_size      = 0.3        # Portion of the dataset to include in the test split
radius_factor  = 0.5        # Radius factor to modulate physical radius during validation
juxta_dtype    = uint16     # Type of the juxtacellular data
juxta_thresh   = 6          # Threshold for juxtacellular detection
juxta_valley   = False      # True if juxta-cellular spikes are negative peaks
juxta_spikes   =            # If none, spikes are automatically detected based on juxta_thresh
filter         = True       # If the juxta channel need to be filtered or not
make_plots     = png        # Generate sanity plots of the validation [Nothing or None if no plots]

[extracting]
safety_time    = 1          # Temporal zone around which spikes are isolated [in ms]
max_elts       = 1000       # Max number of collected events per templates
output_dim     = 5          # Percentage of variance explained while performing PCA
cc_merge       = 0.975      # If CC between two templates is higher, they are merged
noise_thr      = 0.8        # Minimal amplitudes are such than amp*min(templates) < noise_thr*threshold

[noedits]
filter_done    = True              #!! AUTOMATICALLY EDITED: DO NOT MODIFY !!
artefacts_done = False      # Will become True automatically after removing artefacts
median_done    = False      # Will become True automatically after removing common median
ground_done    = False      # Will become True automatically after removing common ground

**Comment by yger** [comment]
First, if you are dealing with in vivo data, I would suggest to activate the option remove_median, to remove the common movement artefacts across channels. This means that you'll have to refilter your data :-). I guess this could get rid of those artefacts

Once this is done, keep in mind that template matching based sorters do not work like OfflineSorter. You can not "throw away" outliers because they are resolving overlapping spikes, thus what you think is an outlier may actually be a spike + something else. Of course, here, I am not sure. But the take home message is that detouring manually clusters in the feature space is something you want to avoid as much as possible, because it does not make sense with overlapping spikes

**Comment by Tywang-720** [comment]
Dear Pierre:

Thanks for the reply!

I just tried setting "remove_median = True"(and refilter the original data), but sadly that doesn't seem to help in my case :(
(below are results in same channel after remove median is done. In fact, I might say this slightly worsens the situation)

![0513-large noise after median removed](https://user-images.githubusercontent.com/82949092/118093421-fd249e80-b3ff-11eb-8966-9ea0dc764e84.png)

On the other hand, I rethought about this issue, and I do agree with you that these noises are more likely to be spike + something else: since they are left in the cluster after all the template-matching is done, there should be a reason. So we may reluctantly live with it for now.

By the way, what do you think if we treat animal licking like stimulation, provide licking time in "dead_file", thus tell SpykingCircus to ignore the data around licking time? 

Below is an example of licking noise during recording(the large vertical lines). The noise is roughly 10Hz or more  on average.  I'm worrying if we do this, data could be over-fragmented and we may risk losing all the spikes during this bursting-licking period.

![Lick noise example](https://user-images.githubusercontent.com/82949092/118098072-0c0e4f80-b406-11eb-8d94-b5f6fc3702cd.png)

**Comment by Tywang-720** [comment]
One more thing: I want to try the common ground functionality, but I got some error saying "ValueError: zero-size array to reduction operation maximum which has no identity
Process exited with exit code 15"

Could you take a look at my settings? 

I want to use channel 0 as common ground and set:

common_ground  =  {1:0}   

probe file is:



total_nb_channels = 128
radius            = 200

channel_groups = {
    1: {
        'channels': list(range(128)),
        'graph' : [],
        'geometry': {
        0: [150,0],
        1: [0,63],
        2: [0,189],
        3: [450,882],
        4: [150,126],
        5: [300,0],
        6: [0,315],
        7: [450,0],
        8: [150,252],
        9: [300,126],
        10: [0,441],
        11: [450,126],
        12: [150,63],
        13: [300,252],
        14: [0,567],
        15: [450,252],
        16: [300,378],
        17: [150,189],
        18: [450,378],
        19: [0,693],
        20: [300,504],
        21: [150,315],
        22: [450,504],
        23: [0,819],
        24: [300,63],
        25: [150,441],
        26: [450,630],
        27: [0,945],
        28: [300,189],
        29: [150,567],
        30: [450,756],
        31: [0,882],
        32: [300,315],
        33: [450,63],
        34: [150,693],
        35: [300,441],
        36: [0,756],
        37: [450,189],
        38: [150,819],
        39: [300,567],
        40: [0,630],
        41: [450,315],
        42: [150,945],
        43: [300,693],
        44: [0,504],
        45: [450,441],
        46: [150,882],
        47: [300,819],
        48: [450,567],
        49: [0,378],
        50: [300,945],
        51: [150,756],
        52: [450,693],
        53: [0,252],
        54: [300,882],
        55: [150,630],
        56: [450,819],
        57: [0,126],
        58: [300,756],
        59: [150,504],
        60: [450,945],
        61: [0,0],
        62: [300,630],
        63: [150,378],
        64: [1050,63],
        65: [750,567],
        66: [900,189],
        67: [900,315],
        68: [1050,189],
        69: [600,693],
        70: [900,63],
        71: [750,441],
        72: [1050,315],
        73: [600,567],
        74: [900,441],
        75: [750,315],
        76: [1050,441],
        77: [600,441],
        78: [900,567],
        79: [750,189],
        80: [600,315],
        81: [1050,567],
        82: [750,63],
        83: [900,693],
        84: [600,189],
        85: [1050,693],
        86: [750,693],
        87: [900,819],
        88: [600,63],
        89: [1050,819],
        90: [750,819],
        91: [900,945],
        92: [600,945],
        93: [1050,945],
        94: [750,945],
        95: [900,882],
        96: [600,882],
        97: [750,882],
        98: [1050,882],
        99: [600,756],
        100: [900,756],
        101: [750,756],
        102: [1050,756],
        103: [600,630],
        104: [900,630],
        105: [750,630],
        106: [1050,630],
        107: [600,504],
        108: [900,504],
        109: [750,504],
        110: [1050,504],
        111: [600,378],
        112: [750,378],
        113: [900,378],
        114: [600,252],
        115: [1050,378],
        116: [750,252],
        117: [900,252],
        118: [600,126],
        119: [1050,252],
        120: [750,126],
        121: [900,126],
        122: [600,0],
        123: [1050,126],
        124: [600,819],
        125: [750,0],
        126: [1050,0],
        127: [900,0]
        }
    }
}

**Comment by sv-bio** [comment]
Hi,
I use this script to remove artefacts by just pressing a hot key (it uses Mahalanobis distance to clean up outliers; check how to plug scripts to Phy2 on their web site):

```
`
from phy import IPlugin, connect
import numpy as np
import logging

logger = logging.getLogger('phy')

class Mahalanobis_Distance(IPlugin):
    def attach_to_controller(self, controller):
        @connect
        def on_gui_ready(sender, gui):
            # @controller.supervisor.actions.add(shortcut='alt+x')
            @controller.supervisor.actions.add(shortcut='alt+x', prompt=True, prompt_default=lambda: 6)
            def MahalanobisDist(thres_in):

                def MahalanobisDistCalc(X, Y):
                    rx = X.shape[0]
                    cx = X.shape[1]
                    ry = Y.shape[0]
                    cy = Y.shape[1]

                    m = np.mean(X, axis=0)
                    M = np.tile(m,(ry,1))
                    C = X - np.tile(m,(rx,1))
                    Q, R = np.linalg.qr(C)
                    ri,ri2,ri3,ri4 = np.linalg.lstsq(np.transpose(R),np.transpose(Y-M))
                    d = np.transpose(np.sum(ri*ri, axis=0)).dot(rx-1)
                    return d

                cluster_ids = controller.supervisor.selected
                spike_ids = controller.supervisor.clustering.spikes_in_clusters(cluster_ids)
                data = controller.model._load_features()
                data3 = data.data[spike_ids]
                data2 = np.reshape(data3,(data3.shape[0],data3.shape[1]*data3.shape[2]))

                if data2.shape[0] < data2.shape[1]:
                    logger.warn("Error: Not enought spikes in the cluster!")
                    return

                MD = MahalanobisDistCalc(data2,data2)
                threshold = thres_in**2
                outliers = np.where(MD > threshold)[0]
                outliers2 = np.ones(len(spike_ids),dtype=int)
                outliers2[outliers] = 2
                logger.info("Outliers detected: %d.", len(outliers))
                controller.supervisor.actions.split(spike_ids,outliers2)
`
```
Best,
Stan
P.S. This code is a compilation from several sources

**Comment by Tywang-720** [comment]
> Hi,
> I use this script to remove artefacts by just pressing a hot key (it uses Mahalanobis distance to clean up outliers; check how to plug scripts to Phy2 on their web site):
> 
> ```
> `
> from phy import IPlugin, connect
> import numpy as np
> import logging
> 
> logger = logging.getLogger('phy')
> 
> class Mahalanobis_Distance(IPlugin):
>     def attach_to_controller(self, controller):
>         @connect
>         def on_gui_ready(sender, gui):
>             # @controller.supervisor.actions.add(shortcut='alt+x')
>             @controller.supervisor.actions.add(shortcut='alt+x', prompt=True, prompt_default=lambda: 6)
>             def MahalanobisDist(thres_in):
> 
>                 def MahalanobisDistCalc(X, Y):
>                     rx = X.shape[0]
>                     cx = X.shape[1]
>                     ry = Y.shape[0]
>                     cy = Y.shape[1]
> 
>                     m = np.mean(X, axis=0)
>                     M = np.tile(m,(ry,1))
>                     C = X - np.tile(m,(rx,1))
>                     Q, R = np.linalg.qr(C)
>                     ri,ri2,ri3,ri4 = np.linalg.lstsq(np.transpose(R),np.transpose(Y-M))
>                     d = np.transpose(np.sum(ri*ri, axis=0)).dot(rx-1)
>                     return d
> 
>                 cluster_ids = controller.supervisor.selected
>                 spike_ids = controller.supervisor.clustering.spikes_in_clusters(cluster_ids)
>                 data = controller.model._load_features()
>                 data3 = data.data[spike_ids]
>                 data2 = np.reshape(data3,(data3.shape[0],data3.shape[1]*data3.shape[2]))
> 
>                 if data2.shape[0] < data2.shape[1]:
>                     logger.warn("Error: Not enought spikes in the cluster!")
>                     return
> 
>                 MD = MahalanobisDistCalc(data2,data2)
>                 threshold = thres_in**2
>                 outliers = np.where(MD > threshold)[0]
>                 outliers2 = np.ones(len(spike_ids),dtype=int)
>                 outliers2[outliers] = 2
>                 logger.info("Outliers detected: %d.", len(outliers))
>                 controller.supervisor.actions.split(spike_ids,outliers2)
> `
> ```
> 
> Best,
> Stan
> P.S. This code is a compilation from several sources

Much Thanks Stan.

I tried set up this plugin, and I do receive a prompt about MahalanobisDist value (default 6) when I press Alt + X, which I believe is proof that it's correctly installed.

But then an error message appears in Phy GUI saying "Error when executing action MahalonobisDist." , without any more information.

Do you have similar experience?

**Comment by yger** [comment]
Phy is only loading a subset of the waveforms, thus the clouds you are looking at are only a portion of all the spikes. Removing outliers there do not give any guarantee you are removing everything, is it?

**Comment by yger** [comment]
Regarding the licking artefacts, since they do not seem to be reproducible, you can only use the dead times to remove these times from the analysis. The other option, i.e. to make a median artefact and subtract it from the raw data while filtering will not make anything. I am not really afraid of using dead times, except that it will be a bit tedious to set up in order to extract all these time windows. You might loose some spikes at the border of these intervals, but not that much I guess.

The other question is "are these strong artefact negligible" w.r.t. the number of real spikes. Because if not, they can affect a bit the clustering, preventing the code from selecting real spikes but instead these high value peaks. However, I presume this is not the case. 
The last option would be to have a threshold in SC such that event higher than it would not be considered, either for clustering or for fitting, because we would immediately assume they are garbage. I guess this can easily be implemented

**Comment by Tywang-720** [comment]
> Regarding the licking artefacts, since they do not seem to be reproducible, you can only use the dead times to remove these times from the analysis. The other option, i.e. to make a median artefact and subtract it from the raw data while filtering will not make anything. I am not really afraid of using dead times, except that it will be a bit tedious to set up in order to extract all these time windows. You might loose some spikes at the border of these intervals, but not that much I guess.
> 
> The other question is "are these strong artefact negligible" w.r.t. the number of real spikes. Because if not, they can affect a bit the clustering, preventing the code from selecting real spikes but instead these high value peaks. However, I presume this is not the case.
> The last option would be to have a threshold in SC such that event higher than it would not be considered, either for clustering or for fitting, because we would immediately assume they are garbage. I guess this can easily be implemented

Thanks for your suggestion Pierre！

I'm going to set up deadtime by recorded lick time, since I'm running out of options.
 
I guess one possible downfall of this approach is that the lick time recorded by the lickometer may not fully cover the lick noise in the recording file (incomplete capture or bad synchrony). So it would be convenient to have an amplitude threshold option in future versions of SC :) For now, I need to try my luck at the dead time approach.

Regarding to the noises after autosorting, through close inspection I now believe much of them are simply large artefacts that resemble spikes in a way (but with unreasonably huge amplitudes and sharp shapes), so we still need to remove them.

These noises could cause big problems in KiloSort3 as they affect event detection and cause misalignment of sorted clusters(waveforms are aligned to big noise and cut in half).  This doesn't happen to SpykingCircus for what I could see for now, and I tend to believe a proper amplitude threshold could solve this.

**Comment by sv-bio** [comment]
Hi Tywang-720,
Feel free to download the script I just posted above as a txt file. In case if it does not work, open IPython console in Phy2 and run it line-by-line to spot an error.
Best,
Stan

**Comment by Tywang-720** [comment]
Update:

A gif is uploaded here to show how noise and true spike looks like.

Interestingly this cluster is considered to have a high purity by the program.

![noisy cluster 20210519](https://user-images.githubusercontent.com/82949092/118794767-7c1c4a00-b8cc-11eb-85f3-777559b17e39.gif)

**Comment by Tywang-720** [comment]
Update:

The dead period approach failed for me, because too much data need to be abandoned to pick clean these artefacts, and that is not affordable.

Seems the only option left is to have an amplitude threshold during event detection. My data are large and I cann't export all the   PCs to Phy.

**Comment by sv-bio** [comment]
Hi,
The other way to sort this out would be to change the number of data points shown in feature space to see them all (it's slow though), followed by outlining the clusters and getting rid of this noise. I have the same issue and these outliers are easy to spot as they stand far away from the rest of the cluster in feature space. Below is the plugin for it. What you are asking about selecting outliers in the Waveform window has been also implemented as a plugin for Phy2 (search for it in their forum on Git), but didn't work in my hands.

[number_of_spikes.txt](https://github.com/spyking-circus/spyking-circus/files/6514408/number_of_spikes.txt)

**Comment by Tywang-720** [comment]
> Hi,
> The other way to sort this out would be to change the number of data points shown in feature space to see them all (it's slow though), followed by outlining the clusters and getting rid of this noise. I have the same issue and these outliers are easy to spot as they stand far away from the rest of the cluster in feature space. Below is the plugin for it. What you are asking about selecting outliers in the Waveform window has been also implemented as a plugin for Phy2 (search for it in their forum on Git), but didn't work in my hands. You could also re-cluster problematic clusters with e.g. K-means. In this case artefacts will be put to a separate cluster, that you can mark as noise (see #343 ). But, I agree with Pierre, that some sort of thresholding would be a better bet.
> 
> [number_of_spikes.txt](https://github.com/spyking-circus/spyking-circus/files/6514408/number_of_spikes.txt)

Thanks Stan.

I somehow get the Mahalanobis plugin working for me, but not this Kmeans plugin (seems they are not correctly loaded.)

The previous one worked in some cases, but failed in others, though various thresholds have been tried.

 I guess it's because my data face much heavier pollution from noise after sorting, and spikes and noise clusters are not always well separated.

Here's some examples:

Success case:

![M-distance plugin A](https://user-images.githubusercontent.com/82949092/119119536-dc8ec100-ba5d-11eb-9922-ba3fdb3ed905.png)

Failure case:
Note interestingly in this case we would expect an easy separation, but somehow it failed...
![M-distance plugin B](https://user-images.githubusercontent.com/82949092/119119642-f5977200-ba5d-11eb-8a12-a205b117976b.png)

Nevertheless, thanks for your kind help! I've gained much knowledge (though still not enough) in this.

Regarding to the selecting outlier plugin in Phy, are you sure there is one？ I saw your question there in last November and Cyrille said there was no such function available.

**Comment by sv-bio** [comment]
Hi,

To do reclustering you need:
1) install **sklearn** package into the same environment where you've installed Phy2.
2) run this plugin (attach it the same way as the others; K-means clustering in this case, but you can choose any other method): 

```
from phy import IPlugin, connect
import numpy as np
from sklearn.cluster import KMeans
import logging
logger = logging.getLogger('phy')

class CustomSplitPlugin(IPlugin):
    def attach_to_controller(self, controller):
        @connect
        def on_gui_ready(sender, gui):

            @controller.supervisor.actions.add(shortcut='s', prompt=True, prompt_default=lambda: 5)

            def custom_split(num_clus):

                cluster_ids = controller.supervisor.selected
                spike_ids=controller.supervisor.clustering.spikes_in_clusters(cluster_ids)
                data = controller.model._load_features()
                data3 = data.data[spike_ids]
                data2 = np.reshape(data3,(data3.shape[0],data3.shape[1]*data3.shape[2]))
                labels=KMeans(n_clusters=num_clus, init='k-means++', n_init=200, max_iter=500,  algorithm='full').fit_predict(data2)
                assert spike_ids.shape == labels.shape
                controller.supervisor.actions.split(spike_ids, labels)
```

**Comment by Tywang-720** [comment]
> Hi,
> 
> 1. I usually set 6-10 SDs, not 3.
> 2. I also have irrelevant noise in the clusters, that has nothing to do with wave shape. No idea, where it comes from:
>    before "cleaning"
>    ![image](https://user-images.githubusercontent.com/58944642/119155824-3c846800-ba5c-11eb-972d-26a3762e63d0.png)
> 
> After:
> ![image](https://user-images.githubusercontent.com/58944642/119155872-4b6b1a80-ba5c-11eb-85b3-1c00b2af5552.png)
> 
> 1. To do reclustering you need:
> 
> * install **sklearn** package into the same environment where you've installed Phy2.
> * run this plugin (attach it the same way as the others; K-means clustering in this case, but you can choose any other method):
> 
> ```
> from phy import IPlugin, connect
> import numpy as np
> from sklearn.cluster import KMeans
> import logging
> logger = logging.getLogger('phy')
> 
> class CustomSplitPlugin(IPlugin):
>     def attach_to_controller(self, controller):
>         @connect
>         def on_gui_ready(sender, gui):
> 
>             @controller.supervisor.actions.add(shortcut='s', prompt=True, prompt_default=lambda: 5)
> 
>             def custom_split(num_clus):
> 
>                 cluster_ids = controller.supervisor.selected
>                 spike_ids=controller.supervisor.clustering.spikes_in_clusters(cluster_ids)
>                 data = controller.model._load_features()
>                 data3 = data.data[spike_ids]
>                 data2 = np.reshape(data3,(data3.shape[0],data3.shape[1]*data3.shape[2]))
>                 labels=KMeans(n_clusters=num_clus, init='k-means++', n_init=200, max_iter=500,  algorithm='full').fit_predict(data2)
>                 assert spike_ids.shape == labels.shape
>                 controller.supervisor.actions.split(spike_ids, labels)
> ```

Thank you!

I'm now using a rather crude way to deal with these noise:

After reading in raw data, and do common median reference by probe shank, I found data baseline have returned to zero, and lick noise could be removed with an amplitude threshold.

In the picture below, x axis is timestamp (20s data for 30kHz sampling), y axis is amplitude, I mark all the timestamp with amplitude above 1000 as noise, and force the data to be 0.  

![2021525-134212](https://user-images.githubusercontent.com/82949092/119445634-b1f37f80-bd5f-11eb-805f-711845f65ce0.png)

After that I feed these denoised data to SC as raw data, and found sorting results are greatly improved, at least it looks like that way. Though I'm not totally sure about possible side effects, I think I could proceed with my analyses with this solution for now.

The remaining noise didn't pose much threat to clustering now, and I could use these Phy plugins to further curate them. 

Cheers and Thanks again！

**Comment by Tywang-720** [comment]
> Hi,
> 
> 1. I usually set 6-10 SDs, not 3.
> 2. I also have irrelevant noise in the clusters, that has nothing to do with wave shape. No idea, where it comes from:
>    before "cleaning"
>    ![image](https://user-images.githubusercontent.com/58944642/119155824-3c846800-ba5c-11eb-972d-26a3762e63d0.png)
> 
> After:
> ![image](https://user-images.githubusercontent.com/58944642/119155872-4b6b1a80-ba5c-11eb-85b3-1c00b2af5552.png)
> 
> 1. To do reclustering you need:
> 
> * install **sklearn** package into the same environment where you've installed Phy2.
> * run this plugin (attach it the same way as the others; K-means clustering in this case, but you can choose any other method):
> 
> ```
> from phy import IPlugin, connect
> import numpy as np
> from sklearn.cluster import KMeans
> import logging
> logger = logging.getLogger('phy')
> 
> class CustomSplitPlugin(IPlugin):
>     def attach_to_controller(self, controller):
>         @connect
>         def on_gui_ready(sender, gui):
> 
>             @controller.supervisor.actions.add(shortcut='s', prompt=True, prompt_default=lambda: 5)
> 
>             def custom_split(num_clus):
> 
>                 cluster_ids = controller.supervisor.selected
>                 spike_ids=controller.supervisor.clustering.spikes_in_clusters(cluster_ids)
>                 data = controller.model._load_features()
>                 data3 = data.data[spike_ids]
>                 data2 = np.reshape(data3,(data3.shape[0],data3.shape[1]*data3.shape[2]))
>                 labels=KMeans(n_clusters=num_clus, init='k-means++', n_init=200, max_iter=500,  algorithm='full').fit_predict(data2)
>                 assert spike_ids.shape == labels.shape
>                 controller.supervisor.actions.split(spike_ids, labels)
> ```

Thank you!

I'm now using a rather crude way to deal with these noise:

After reading in raw data, and do common median reference by probe shank, I found data baseline have returned to zero, and lick noise could be removed with an amplitude threshold.

In the picture below, x axis is timestamp (20s data for 30kHz sampling), y axis is amplitude, I mark all the timestamp with amplitude above 1000 as noise, and force the data to be 0.  

![2021525-134212](https://user-images.githubusercontent.com/82949092/119445634-b1f37f80-bd5f-11eb-805f-711845f65ce0.png)

After that I feed these denoised data to SC as raw data, and found sorting results are greatly improved, at least it looks like that way. Though I'm not totally sure about possible side effects, I think I could proceed with my analyses with this solution for now.

The remaining noise didn't pose much threat to clustering now, and I could use these Phy plugins to further curate them. 

Cheers and Thanks again！
