### ISSUE TITLE
ValueErrors during estimation of the amplitudes

### ISSUE THREAD

**Issue by Tywang-720** [spyking-circus/spyking-circus#357]
Hi Pierre:

Some new error begins to haunt me.

**It happens when the program computing optimal amplitudes for the templates, and seems to stably occur with various** **parameter settings.**

I'm aware that this issue has been mentioned before:
 https://github.com/spyking-circus/spyking-circus/issues/347
 but the solution there doesn't seem to work for me.

The whole message would read like:

##################################################################
##################################################################

File          : E:\Test\d001.mountainsort\comngnd0\d001.group0.mda
Steps         : filtering, whitening, clustering, fitting, merging
Number of CPU : 20/20
Parallel HDF5 : False
Shared memory : True
Hostfile      : C:\Users\720 Recording\spyking-circus\circus.hosts

##################################################################

-------------------------  Informations  -------------------------
| Number of recorded channels : 128
| Number of analyzed channels : 128
| File format                 : MDA
| Data type                   : int16
| Sampling rate               : 30000 Hz
| Duration of the recording   : 22 min 25 s 540 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 200 um
| Threshold crossing          : positive and negative
------------------------------------------------------------------
Filtering with a Butterworth filter (order 3) in [300, 14250] Hz
Channels {1: 0} are used as reference channels in respective shanks
100%||[02:31<00:00, 37.94s/it]3.27s/it]7.48s/it]8.45s/it]?, ?it/s]
Analyzing data to get whitening matrices and thresholds...
Found 19.5223s to compute the whitening matrix...
Because of whitening, need to recompute the thresholds...
Searching spikes to construct the PCA basis...
100%||[00:41<00:00, 10.48s/it]1.09s/it]1.08s/it]4.19s/it]?, ?it/s]
Found 164100 waveforms over 204800 requested
Searching isolated random spikes to sample amplitudes...
100%||[01:05<00:00, 16.45s/it]8.03s/it]9.90s/it]3.06s/it]?, ?it/s]
Found 364638 spikes over 2048000 requested
Estimating amplitudes distributions...
Smart Search of good isolated spikes for the clustering (1/3)...
100%||[01:08<00:00, 17.09s/it]8.85s/it]9.73s/it]3.66s/it]?, ?it/s]
Found 358224 isolated spikes over 2048000 requested (48246 rejected)
Computing density estimations...
Searching random spikes to refine the clustering (2/3)...
100%||[00:52<00:00, 13.10s/it]4.38s/it]6.15s/it]7.07s/it]?, ?it/s]
Found 44596 spikes over 2048000 requested
Refining density estimations...
Searching random spikes to refine the clustering (3/3)...
100%||[00:49<00:00, 12.42s/it]4.01s/it]5.49s/it]6.20s/it]?, ?it/s]
Found 934 spikes over 2048000 requested
Refining density estimations...
Running density-based clustering...
100%||[00:35<00:00,  5.03s/it]s/it]s/it]s/it]s/it]s/it]s/it]?it/s]
-------------------------  Informations  -------------------------
| Number of clusters found : 356
| Number of local merges   : 28 (method nd-bhatta, param 2)
| Not enough spikes gathered: -put safety_space=False?
|                             -remove smart_search?
------------------------------------------------------------------
Estimating the templates with the median-raw procedure ...
100%||[00:01<00:00,  3.94it/s]it/s]it/s]it/s]it/s]it/s]0<?, ?it/s]
Removing 5 strongly shifted or noisy/mixture templates...
Merging similar templates...
100%||[00:14<00:00,  2.09s/it]s/it]s/it]s/it]s/it]s/it]0<?, ?it/s]
Removing mixtures of templates...
100%||[00:06<00:00,  1.04it/s]s/it]s/it]s/it]s/it]it/s]0<?, ?it/s]
100%||[00:00<00:00, 84.68it/s]1it/s]             |[00:00<?, ?it/s]
-------------------------  Informations  -------------------------
| Number of global merges    : 122
| Number of mixtures removed : 0
------------------------------------------------------------------
**Computing optimal amplitudes for the templates...**
100%||[00:12<00:00,  1.04s/it]/s]/s]it]/s]it]/s]it]it]it]it]it]/s]
100%||[00:00<00:00, 12.54it/s]Traceback (most recent call last):s]
  File "C:\Anaconda\envs\phy2\Scripts\spyking-circus-subtask-script.py", line 33, in <module>
    sys.exit(load_entry_point('spyking-circus==1.0.7', 'console_scripts', 'spyking-circus-subtask')())
  File "C:\Anaconda\envs\phy2\lib\site-packages\circus\scripts\subtask.py", line 54, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "C:\Anaconda\envs\phy2\lib\site-packages\circus\__init__.py", line 23, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "C:\Anaconda\envs\phy2\lib\site-packages\circus\clustering.py", line 1803, in main
    normalization=templates_normalization, debug_plots=debug_plots
  File "C:\Anaconda\envs\phy2\lib\site-packages\circus\shared\algorithms.py", line 1321, in refine_amplitudes
    max_amp = 1.25*very_good_values.max()
  File "C:\Anaconda\envs\phy2\lib\site-packages\numpy\core\_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
**ValueError: zero-size array to reduction operation maximum which has no identity**

(The value error is thrown for 20 times because there's 20 CPU used)

I tried setting "max_amplitude = auto to "clustering" section of *.params file" but that doesn't work for me.

It has been mentioned that using an older "algorithms.py" could prevent this problem, but I'm not sure what to do, and the possible side effects.

**Comment by Tywang-720** [comment]
I'm still working on the test data in the last noise issue.

SpykingCircus could finish the job on the original settings, but run into this value error when I :

1. trying to use common ground with common_ground = {1,0}
2. or trying to reduce radius from 200 to 100. 

My probe is 8 shank 128 channel, with 150 μm between shank and 63μm between channels on the same shank.

Hope these information would be helpful. 
Probe file:
[C57009d1L12.txt](https://github.com/spyking-circus/spyking-circus/files/6478318/C57009d1L12.txt)

**Comment by yger** [comment]
This error (the max_amplitude) has been fixed in the master branch, so this should go away if you install SC from git. Or if you don't know if you do

>> pip install http://github.com/spyking-circus/spyking-circus/archive/master.zip --upgrade

You should have a weird version number (except if you use git), but at least no error anymore. And as soon as 1.0.8 will be released, you can go back to normal install (via pip/conda)

**Comment by yger** [comment]
Just also to be clear, the error when you are using the common_ground or reducing the radius is always the same, i.e. the one mentioned here triggered during the estimation of the amplitudes? If yes, then everything should be solved. If not, then please let me know when do the other errors appear

**Comment by Tywang-720** [comment]
> Just also to be clear, the error when you are using the common_ground or reducing the radius is always the same, i.e. the one mentioned here triggered during the estimation of the amplitudes? If yes, then everything should be solved. If not, then please let me know when do the other errors appear

Thank you Pierre ! 

 I can confirm that thus error is gone after the upgrade is applied. Cheers!

**By now I only see this error during estimation of amplitudes.** Should it appear again, I'll let you know.

**Comment by Tywang-720** [comment]
> Just also to be clear, the error when you are using the common_ground or reducing the radius is always the same, i.e. the one mentioned here triggered during the estimation of the amplitudes? If yes, then everything should be solved. If not, then please let me know when do the other errors appear

**I found another different error during the estimation of the amplitudes:**
**ValueError: x and y should have a same length**

I need to mention that I just reinstalled spyking circus via pip(v 1.0.8) in a new environment. Because I ran into trouble after recent Anaconda updates (nothing could be launched from Anaconda navigator), and made a mess of original environments during my attempts to fix it.

The whole message could be found here:
[Error message  tywang 20210519.txt](https://github.com/spyking-circus/spyking-circus/files/6506924/Error.message.tywang.20210519.txt)

The parameter file could be found here:
[d001.group0.params.txt](https://github.com/spyking-circus/spyking-circus/files/6506967/d001.group0.params.txt)

Other notes: this error appears when I'm trying to use a longer dead time setting:
 I could finish the sorting with abandoning 30ms around licking event(pre 15 post 15), and I do observe a drop in the artefacts I mentioned in another issue. But when I use longer dead time (60ms around licking), this error occurs.

I also noticed that the information says "Not enough spikes gathered: -put safety_space=False?"
I guess this might be related to the error.

**Comment by Tywang-720** [comment]
Update: 

After radius increased back to 200, I could use longer dead period (100ms) now.

**Comment by yger** [comment]
To be honest, I think we do not have explicit match for spikes that would fall at the border of the dead periods. So this is our fault, and I'll need to patch that quickly. Thanks for the report, I'll dig into that asap, since in your case from what I understand, increasing the dead periods lead to errors (weird and meaning that spikes/events are, sometimes, by bad luck, taken at the borders)

**Comment by Tywang-720** [comment]
> To be honest, I think we do not have explicit match for spikes that would fall at the border of the dead periods. So this is our fault, and I'll need to patch that quickly. Thanks for the report, I'll dig into that asap, since in your case from what I understand, increasing the dead periods lead to errors (weird and meaning that spikes/events are, sometimes, by bad luck, taken at the borders)

Thank you ! Just to mention, at this moment I'm not really sure whether dead period or radius setting is more important to this error, maybe both. And I recalled now I have seen this “ x and y should have a same length” error before I started to use dead period.
