### ISSUE TITLE
Problem with spase_export to Phy2

### ISSUE THREAD

**Issue by Tywang-720** [spyking-circus/spyking-circus#359]
Sorry if I'm raising this question at wrong place.

I saw some of my results and believe the cluster should be assigned to channels with more obvious waveform shapes, but the program says otherwise.

(In the picture below, ch 1、5、7、11 could be better candidate from what I see, but instead ch 0 is chosen)
![Wrong best channel assignment](https://user-images.githubusercontent.com/82949092/119616507-44b11e80-be33-11eb-84bf-1359041e995d.png)

Is is a Spyking-circus issue or a Phy2 issue？Any quick fixation?

Thanks!

**Comment by yger** [comment]
No problem. Actually phy2 has its own internal way of selecting the channel, as the one where the minimal value is reached (I think). SC does not provide this info...

**Comment by Tywang-720** [comment]
> No problem. Actually phy2 has its own internal way of selecting the channel, as the one where the minimal value is reached (I think). SC does not provide this info...

Good to know ! Thanks!

**Comment by Tywang-720** [comment]
Hi Pierre:

I found that by setting "sparse_export" to False, Phy could find the correct channel (most suitable waveform). Maybe it's similar to the issue you have mentioned before : https://github.com/cortex-lab/phy/issues/1014?

![Wrong best channel assignment cured](https://user-images.githubusercontent.com/82949092/119757019-f05f7a80-bed6-11eb-8e4f-bcd673224bf6.png)

Not sure if this should be fixed at Phy or SC end, but better to mention it here.

I also found that by setting "sparse_export" to False, Phy shows more related channels for same unit.

**Comment by Tywang-720** [comment]
By the way, I'm using phy TemplateGUI v2.0b2.dev, and phylib v2.3a0. Spyking-Circus is 1.0.8.

**Comment by yger** [comment]
I still think this is a phy problem. If you set sparse export to True, templates are given to phy as sparse data structures, which is much faster to display for large arrays. Also, you see really only the channels that are really belonging to the templates found by SC. If set to False, phy find the peak channel for the template, but arbitrarily decide to colorcode 16 channels around it. So this might bias some curation choices. For example, even if a template is rather bad in SC, because defined on one channel, it will look in phy like it has many channels (with sparse export set to False). I'll double check, but best is to see with Cyril rossant

**Comment by Tywang-720** [comment]
> I still think this is a phy problem. If you set sparse export to True, templates are given to phy as sparse data structures, which is much faster to display for large arrays. Also, you see really only the channels that are really belonging to the templates found by SC. If set to False, phy find the peak channel for the template, but arbitrarily decide to colorcode 16 channels around it. So this might bias some curation choices. For example, even if a template is rather bad in SC, because defined on one channel, it will look in phy like it has many channels (with sparse export set to False). I'll double check, but best is to see with Cyril rossant

Thanks for the explanation！ I also begin to realize that some channels are unnecessarily involved with sparse export set to false.

Still, the location of unit is of great concern to us, so we may still use

**Comment by Tywang-720** [comment]
> I still think this is a phy problem. If you set sparse export to True, templates are given to phy as sparse data structures, which is much faster to display for large arrays. Also, you see really only the channels that are really belonging to the templates found by SC. If set to False, phy find the peak channel for the template, but arbitrarily decide to colorcode 16 channels around it. So this might bias some curation choices. For example, even if a template is rather bad in SC, because defined on one channel, it will look in phy like it has many channels (with sparse export set to False). I'll double check, but best is to see with Cyril rossant

Thanks for the explanation!
I also begin to realize that some channels are unnecessarily involved.
Still, to us. the importance of unit spatial location outweighs possible curation bias, so we have to use the older data structure for now.
I also reported this in Phy issues, but it seems Cyril is working on something else and stops respond to phy issues for quite a while.
Nevertheless, thanks for your advice! I'll keep it in mind.
