### ISSUE TITLE
Problem with spyking circus folder: SC via Spikeinterface raises this error: Exception(spykingcircus_folder, " is not a spyking circus folder")

### ISSUE THREAD

**Issue by jonasort** [spyking-circus/spyking-circus#360]
Dear Pierre, dear all,

first thank you so much for spyking circus, it works really well for me thus far.

For some reason I get the error above now. I use SC on 256 MEA files via the Spikeinterface framework. Running the sorter that way worked before without a problem, but the last days this problem occured. To my best knowledge no dependencies are deprecated.

![image](https://user-images.githubusercontent.com/20641371/120461616-6f065d00-c39a-11eb-99df-7a70cbf48e9c.png)
It creates the basis, clusters and templates, but raises the error before the results are saved.

I attach the log as well.
There it says:
| Step "clustering" failed for reason Command '['mpiexec', '-np', '10', 'spyking-circus-subtask', 'clustering', 'D:\\MEA_DATA_Aachen\\ANALYZED\\20210510_cortex_div4\\_output_Spikesorting_02062021_cortex_div4_hCSF_ID039_nodrug_spont_1_spikesorting\\sorted_sec_0-130\\recording.npy', '10', '0', 'False', 'False']' returned non-zero exit status 1.!

[spykingcircus.log](https://github.com/spyking-circus/spyking-circus/files/6583634/spykingcircus.log)

Any hints and help are highly appreciated,
cheers!

**Comment by yger** [comment]
Thanks for the feedback. This error has been fixed in the last release 1.0.8 (and thus master branch). Let me know if updating your install works

**Comment by jonasort** [comment]
Dear Pierre, yes that did the job! Merci beaucoup.
