### ISSUE TITLE
how to get numeric values if ISI

### ISSUE THREAD

**Issue by Hugues1273** [spyking-circus/spyking-circus#362]
Dear all, dear Pierre, 

thank you again past help! Now everything is working and I was able to clean artifacts from my data!

Now I would like to get numeric values for ISI (I got the grah using the matlab GUI)  or the mean amplitude of spikes. Therefore I looked for on the documentation and found the following script which seems to be exactly what I need:

`tmpfile        = 'yourdata/yourdata.templates.hdf5';
templates_size = double(h5read(tmpfile, '/temp_shape'));
N_e = templates_size(2);
N_t = templates_size(1);
temp_x = double(h5read(tmpfile, '/temp_x') + 1);
temp_y = double(h5read(tmpfile, '/temp_y') + 1);
temp_z = double(h5read(tmpfile, '/temp_data'));
templates = sparse(temp_x, temp_y, temp_z, N_e*N_t, templates_size(3));
templates_size = [templates_size(1) templates_size(2) templates_size(3)/2];
temp_i = full(reshape(templates(:, tmpnum), N_t, N_e);
imshow(temp_i)`

link of the script = https://spyking-circus.readthedocs.io/en/latest/advanced/analysis.html

However, this script fails at the line temp_i as matlab dont find what is tmpnum. Therefore I tried to look for but I were unable to find to what "tmpnum" corresponds. Is it the number of rows of the array (2048 for me)? I tried to understand the logic but I m too beginner, I m so sorry, I guess my question is not an expert question, I m desperate for that!

Thank you again for your help!!

Hugues

**Comment by yger** [comment]
No problem

tmpnum is the number of the template (and thus the cell) you want to look
at. It should be a number then

Best

Pierre
