### ISSUE TITLE
Step clustering failed

### ISSUE THREAD

**Issue by Tywang-720** [spyking-circus/spyking-circus#365]
Hi there: 

I recently got one piece of data that failed at clustering. Please take a look:)

Spyking-circus is already at newest version.

##################################################################
##################################################################

File          : E:\Denoised\C57#010\d010\d010.group0.CMR1AmpThres1000.mda
Steps         : filtering, whitening, clustering, fitting, merging
Number of CPU : 20/20
Parallel HDF5 : False
Shared memory : True
Hostfile      : C:\Users\720 Recording\spyking-circus\circus.hosts

##################################################################

-------------------------  Informations  -------------------------
| Number of recorded channels : 128
| Number of analyzed channels : 128
| File format                 : MDA
| Data type                   : int16
| Sampling rate               : 30000 Hz
| Duration of the recording   : 32 min 52 s 891 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 200 um
| Threshold crossing          : negative
------------------------------------------------------------------
[33m-------------------------  Informations  -------------------------
[33m| Filtering has already been done
[37m------------------------------------------------------------------
[37mAnalyzing data to get whitening matrices and thresholds...
[37mFound 22.272s to compute the whitening matrix...
[37mBecause of whitening, need to recompute the thresholds...
[37mSearching spikes to construct the PCA basis...
100%|████████████████████████████████████|[00:44<00:00,  8.94s/it]
[37mFound 102375 waveforms over 102400 requested
[33m-------------------------  Informations  -------------------------
[33m| A basis with 5 dimensions has been built
[37m------------------------------------------------------------------
[37mSearching isolated random spikes to sample amplitudes...
100%|████████████████████████████████████|[01:36<00:00, 19.32s/it]
[37mFound 483393 spikes over 1024000 requested
[37mEstimating amplitudes distributions...
[37mSmart Search of good isolated spikes for the clustering (1/3)...
100%|████████████████████████████████████|[02:38<00:00, 31.62s/it]
[37mFound 412303 isolated spikes over 1024000 requested (841388 rejected)
[37mComputing density estimations...
[37mSearching random spikes to refine the clustering (2/3)...
100%|████████████████████████████████████|[01:28<00:00, 17.60s/it]
[37mFound 249842 spikes over 1024000 requested
[37mRefining density estimations...
[37mSearching random spikes to refine the clustering (3/3)...
100%|████████████████████████████████████|[01:26<00:00, 17.27s/it]
[37mFound 165097 spikes over 1024000 requested
[37mRefining density estimations...
[37mRunning density-based clustering...
100%|████████████████████████████████████|[00:23<00:00,  3.39s/it]
[33m-------------------------  Informations  -------------------------
[33m| Number of clusters found : 150
[33m| Number of local merges   : 72 (method nd-folding, param 1e-09)
[37m------------------------------------------------------------------
[37mEstimating the templates with the median-raw procedure ...
100%|████████████████████████████████████|[00:02<00:00,  3.39it/s]
[37mRemoving 6 strongly shifted or noisy/mixture templates...
[33m-------------------------  Informations  -------------------------
[33m| Templates on few channels only (2), cc_merge set to 1 automatically
[37m------------------------------------------------------------------
[37mRemoving mixtures of templates...
100%|████████████████████████████████████|[00:00<00:00,  8.68it/s]
100%|███████████████████████████████████|[00:00<00:00, 256.06it/s]
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 9448 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 4120 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 2 PID 9832 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 3 PID 18296 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 4 PID 736 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 5 PID 9100 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 6 PID 16388 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 7 PID 17092 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 8 PID 3940 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 9 PID 3984 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 10 PID 17492 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 11 PID 9352 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 12 PID 3048 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1073741819 (c0000005)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 13 PID 16944 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 14 PID 15312 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 15 PID 15540 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 16 PID 16780 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 17 PID 11552 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 18 PID 16504 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 19 PID 11292 RUNNING AT DESKTOP-1F5675O
=   EXIT STATUS: -1 (ffffffff)
===================================================================================
----------------------------  Error  -----------------------------
| Step "clustering" failed for reason Command '['mpiexec', '-np', '20', 'spyking-circus-subtask', 'clustering', 'E:\\Denoised\\C57#010\\d010\\d010.group0.CMR1AmpThres1000.mda', '20', '0', 'False', 'False']' returned non-zero exit status 4294967295.!
------------------------------------------------------------------

Log is here, nothing informative.
[d010.group0.CMR1AmpThres1000.log](https://github.com/spyking-circus/spyking-circus/files/7233214/d010.group0.CMR1AmpThres1000.log)

Channel map is here.
[C57010d1L12578.txt](https://github.com/spyking-circus/spyking-circus/files/7233223/C57010d1L12578.txt)

Params is here
[d010.group0.CMR1AmpThres1000.txt](https://github.com/spyking-circus/spyking-circus/files/7233227/d010.group0.CMR1AmpThres1000.txt)

If more information is needed please let me know.

Thanks!

**Comment by Tywang-720** [comment]
Well, I ran the same parameter again and somehow the error disappears.

Guess this bug is random.

**Comment by Tywang-720** [comment]
More concerning is :

sometimes the bug : "BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES" is not thrown 20 times (I have 20 cores), and the program proceeds as if everything is normal.

Does that means in that case, any cells in that failed processes are lost for some random reason?

**Comment by yger** [comment]
Having less error messages than number of cores is not an issue. Strange that the bug is random, but you are not "losing" any cells in this process. Let me know if you have such an error too often,and I'll investigate more in depth

**Comment by Tywang-720** [comment]
> Having less error messages than number of cores is not an issue. Strange that the bug is random, but you are not "losing" any cells in this process. Let me know if you have such an error too often,and I'll investigate more in depth

That's reassuring. Thanks for the explanation. 

As of now this doesn't seem to happen too often ( ~5% percent of my data files), and I think I can close this for now :)
