### ISSUE TITLE
File giverandomname.dat not found

### ISSUE THREAD

**Issue by beOn** [spyking-circus/spyking-circus#37]
Using phycontrib 1.0.15, circus 0.5.7, and python 2.7 or 3.5, I get the following after calling circus-gui-python Continuous_Data.openephys:

```bash
-------------------------  Informations  -------------------------
| File format openephys is not supported by phy. TraceView disabled
------------------------------------------------------------------
06:58:21 [I] messages:49          File format openephys is not supported by phy. TraceView disabled
-------------------------  Informations  -------------------------
| Gain of 0.195 is not supported by phy. Expecting a scaling mismatch
------------------------------------------------------------------
06:58:21 [I] messages:49          Gain of 0.195 is not supported by phy. Expecting a scaling mismatch
-------------------------  Informations  -------------------------
| Launching the phy GUI...
------------------------------------------------------------------
06:58:21 [I] messages:49          Launching the phy GUI...
06:58:22 [W] gui:264              Error while loading data: File giverandomname.dat not found.
06:58:38 [E] cli:39               An error has occurred (RuntimeError): context could not be created
```

Am I missing some obvious step, or is this a known issue... or can you give any beta that might speed up debugging?

**Comment by yger** [comment]
You are not missing anything. You can not view openphys raw data in phy,
but the GUI should be able to launch anyway and show templates/spike times.
I'll have a look asap,

Best

Le jeu. 6 juil. 2017 à 14:14, Ben Acland <notifications@github.com> a
écrit :

**Comment by yger** [comment]
Actually, I can not reproduce the bug. The 'giverandomname.dat' value is simply because when a file format is not supported by phy (as openephys), we need to pass a random/false name to the 'dat_path' field as such a field can not be empty. By doing so, phy sees that such the file does not exist (hopefully you do not have a file randomfilename.dat !), and then it should launch and automatically disable the TraceView and some features of the Waveform View. I'm testing here, and this is working with latest phy/phycontrib from git. I'll test with various install to try to see if I can reproduce it

**Comment by beOn** [comment]
And I will test with the latest phy/phycontrib.

**Comment by beOn** [comment]
Hm... the error message didn't appear after changing to the github versions of phy/phycontrib, but the UI never materialized. Setting up a local installation to see if I can repro. In the meanwhile, here's my conda environment, JIC it helps:

```yaml
name: spykpi
channels:
- spyking-circus
- conda-forge
- defaults
dependencies:
- colorama=0.3.9=py35_0
- mpi4py=2.0.0=py35_2
- mpich=3.2=4
- psutil=5.2.1=py35_0
- tqdm=4.14.0=py35_0
- cairo=1.14.8=0
- cycler=0.10.0=py35_0
- cython=0.25.2=py35_0
- decorator=4.0.11=py35_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- h5py=2.7.0=np111py35_0
- harfbuzz=0.9.39=2
- hdf5=1.8.17=1
- ipython=6.1.0=py35_0
- ipython_genutils=0.2.0=py35_0
- jedi=0.10.2=py35_2
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libxml2=2.9.4=0
- matplotlib=1.5.1=np111py35_0
- mkl=2017.0.3=0
- numpy=1.11.3=py35_0
- openssl=1.0.2l=0
- pango=1.40.3=1
- path.py=10.3.1=py35_0
- pcre=8.39=1
- pexpect=4.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=9.0.1=py35_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.14=py35_0
- ptyprocess=0.5.1=py35_0
- pygments=2.2.0=py35_0
- pyparsing=2.1.4=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.3=1
- python-dateutil=2.6.0=py35_0
- pytz=2017.2=py35_0
- qt=4.8.7=4
- readline=6.2=2
- scikit-learn=0.18.1=np111py35_1
- scipy=0.19.0=np111py35_0
- setuptools=27.2.0=py35_0
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.2=py35_0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- xz=5.2.2=1
- zlib=1.2.8=3
- spyking-circus=0.5.7=py35_0
- pip:
  - certifi==2017.4.17
  - chardet==3.0.4
  - click==6.7
  - cudamat==0.3circus
  - idna==2.5
  - ipython-genutils==0.2.0
  - joblib==0.11
  - klusta==3.0.16
  - klustakwik2==0.2.6
  - phy==1.0.9
  - phycontrib==1.0.15
  - prompt-toolkit==1.0.14
  - requests==2.18.1
  - urllib3==1.21.1
  - vispy==0.4.0
```

**Comment by beOn** [comment]
Ack... embarassing. Run locally with the most recent phy/phycontrib releases, I still get the error, but the UI then launches as expected. With the most recent master branch of phy and phycontrib, I don't get the error, but the UI doesn't launch. Weird, but not reportworthy. Sorry for the goose chase.

**Comment by beOn** [comment]
Annnd the UI wasn't launching initially because I was calling phy over ssh... which is known not to work >.<.
