### ISSUE TITLE
Problems using raster plot option in SortingGUI

### ISSUE THREAD

**Issue by IsaacMMMM** [spyking-circus/spyking-circus#371]
I had problems using the raster plot option in the Matlab-Gui. I received this error message: 

```
Error using histc
Edge vector must be monotonically non-decreasing.

Error in SortingGUI>find_spikes_for_raster2 (line 1495)
[~, fr_repeat] = histc( spk_time, rep_times);
```

When I checked the matlab code, I found that the error comes due to a function called `find_spikes_for_raster2` in the 1489 line of the `SortingGUI.m`

- The problem could be solved by replacing this `rep_times(:)` to this  `sort(rep_times(:))` in line 1493. 

- Another way to resolve it is by replacing the calling of the function `find_spikes_for_raster2` with another function called `find_spikes_for_raster` in line 1514. 

Hope I could help if someone is having the same problem.

**Comment by yger** [comment]
Thanks for the tip, will see if I can reproduce the error, and make a patch
