### ISSUE TITLE
Template width

### ISSUE THREAD

**Issue by m-bellv** [spyking-circus/spyking-circus#392]
Hello,

I'm interested in looking at the average trough to peak width for spikes within a cluster. I thought I might be able to find this information from the .clusters-merged.hdf5 file, by considering all the spikes across electrode channels for each cluster, however, I am finding that the total number of independent clusters in this file is significantly less (about half) of the number of templates that are reported in the result-merged.hdf5 file.

I have also tried looking at the templates-merged.hdf5 file, which does have the same number of templates as in the result-merged file, however these templates are sometimes noisy and don't give a distribution across spikes from the cluster. In addition, it is at times unclear where the detected spike occurs temporally within the template as well as which is the preferred electrode channel for the template to look at. 

Is there any place where the template information is stored in a similar way to the clusters-merged file, with time location across electrode channels?

Thanks,
Monica

**Comment by m-bellv** [comment]
Is it the case that the cluster labels within the cluster-merged['cluster_i'] are unique between channels? And the the clusters labelled -1 are dropped from the total number in local_clusters? This then matches the number of clusters to the number of temp_i in the result-merged.hdf5 file

**Comment by yger** [comment]
Yes, the labels are unit between channels, and -1 are dropped from the
total number in local_cluster

Let me know how I can help

**Comment by m-bellv** [comment]
I am able to compute the trough to peak with this information, thank you
