### ISSUE TITLE
Spike detection error

### ISSUE THREAD

**Issue by soucyjr** [spyking-circus/spyking-circus#393]
Using spikeinterface to run spykingcircus in a docker (also tried locally) and spikes are not being accurately detected in my maxwell data set. See image. Any insights/suggestions? I'm using the default sorter parameters and applying these filters to the data:

```
sub_recording_f = spre.bandpass_filter(sub_recording, freq_min=300, freq_max=6000)
sub_recording_cmr = spre.common_reference(sub_recording_f, reference='global', operator='median')
```

![image](https://github.com/spyking-circus/spyking-circus/assets/158186080/a94b5c17-9059-435e-a241-7c30783a1edb)

**Comment by yger** [comment]
This is clearly not normal. Can you try to convert the data to float32 while filtering? Add dtype="float32" to your bandpass filter arguments. Otherwise, maybe make a small slice of the recording and share it to me, but this peak detection should work

**Comment by yger** [comment]
Ok, can you let me know what is your whole analysis script? And you are using Spyking Circus 1 (from docker), but you could also try to use spykingcircus 2 (included in SpikeInterface as a beta version), via the si.run_sorter() command

si.set_global_job_kwargs(n_jobs=0.8)
res = si.run_sorter('spykingcircus2', recording_cmr, output_folder='maxwell', verbose=True)

**Comment by soucyjr** [comment]
I thought I had it working last night, but today it seems I am unable to reproduce my result using spykingcircus1. Something that I noticed is I am unable to run spykingcircus1 in the docker unless I first run an installed copy of spykingcircus1. Spykingcircus2 is working correctly after I updated the data type to float32.

Here is my full script (haven't yet figured out all the modules):

```
import matplotlib.pyplot as plt
from pprint import pprint

import spikeinterface.core as si
import spikeinterface.extractors as se
import spikeinterface.preprocessing as spre
import spikeinterface.sorters as ss
import spikeinterface.postprocessing as spost
import spikeinterface.qualitymetrics as sqm
import spikeinterface.exporters as sexp
import spikeinterface.comparison as scmp
import spikeinterface.curation as scur
import spikeinterface.sortingcomponents as sc
import spikeinterface.widgets as sw

#global_job_kwargs = dict(n_jobs=4, chunk_duration="1s")
#si.set_global_job_kwargs(**global_job_kwargs)
si.set_global_job_kwargs(n_jobs=0.8)

recording = se.read_maxwell('explant.raw.h5')
print(recording)

probe = recording.get_probe()

from probeinterface.plotting import plot_probe

_ = plot_probe(probe)

channel_ids = recording.channel_ids
act_channels = [432, 372, 164, 168, 324, 124, 316, 132, 152, 156, 416, 356, 
                328, 276, 212, 256, 196, 484, 300, 200, 444, 172, 308, 268, 312, 428, 204, 
                288, 236, 116, 504, 16, 228, 264, 500, 216, 492, 284, 240, 140, 296, 280, 244]
act_channels = [str(a) for a in act_channels]
act_recording = recording.channel_slice(act_channels)

fs = recording.sampling_frequency
#sub_recording = act_recording.frame_slice(start_frame=int(fs * 60 * 2), end_frame=int(fs * 60 * 3))
sub_recording = act_recording
sub_recording_f = spre.bandpass_filter(sub_recording, freq_min=300, freq_max=5000, dtype="float32")
recording_cmr = sub_recording
sub_recording_cmr = spre.common_reference(sub_recording_f, reference='global', operator='median')

recording_pre = sub_recording_cmr.save(format='binary')
print(recording_pre)
probe = act_recording.get_probe()

from probeinterface.plotting import plot_probe

_ = plot_probe(probe)

print("SpykingCircus params:")
pprint(ss.get_default_sorter_params('spykingcircus'))

other_params = ss.get_default_sorter_params('spykingcircus')
other_params['detect_threshold'] = 6
other_params['adjacency_radius'] = 250
other_params['template_width_ms'] = 4
print(other_params)

print("SpykingCircus2 params:")
pprint(ss.get_default_sorter_params('spykingcircus2'))
other_params2 = ss.get_default_sorter_params('spykingcircus2')
other_params2['detection']['detect_threshold'] = 6
other_params2['general']['radius_um'] = 250
print(other_params2)

sorting = ss.run_sorter(sorter_name="spykingcircus", remove_existing_folder=True,recording=recording_pre, verbose=True, **other_params)
#sorting2 = ss.run_sorter(sorter_name="spykingcircus2", remove_existing_folder=True,recording=recording_pre, verbose=True, **other_params2)

#sorting = ss.run_sorter(sorter_name='spykingcircus', recording=recording_pre,
#                     remove_existing_folder=True, docker_image=True, verbose=True, **other_params)

print(sorting)
#print(sorting2)

datatrace_filter = sw.plot_traces(recording_pre, time_range=(0, 5))
datatrace_sort = sw.plot_rasters(sorting, time_range=(0, 5))
datatrace_sort = sw.plot_rasters(sorting2, time_range=(0, 5))

we = si.extract_waveforms(recording_pre, sorting, 'waveforms_folder', overwrite=True)
print(we)

firing_rates = []
for unit_id in sorting.get_unit_ids():
    st = sorting.get_unit_spike_train(unit_id=unit_id, segment_index=0)
    firing_rates.append(st.size / 60)
sorting.set_property('firing_rate', firing_rates)

print(sorting.get_property('firing_rate'))

amplitudes = spost.compute_spike_amplitudes(we)
unit_locations = spost.compute_unit_locations(we)
spike_locations = spost.compute_spike_locations(we)
correlograms, bins = spost.compute_correlograms(we)
similarity = spost.compute_template_similarity(we)

unit_ids = sorting.unit_ids[:5]
sw.plot_unit_waveforms_density_map(we, unit_ids=unit_ids, figsize=(28,16))

#import spikeinterface_gui
#app = spikeinterface_gui.mkQApp() 
#we = si.WaveformExtractor.load_from_folder('waveforms_folder')
#win = spikeinterface_gui.MainWindow(we)
#win.show()
#app.exec_()

#stop, read: https://spikeinterface.readthedocs.io/en/latest/modules/curation.html
#scur.plot_sorting_summary(waveform_extractor=we, curation=True, backend='sortingview')

sexp.export_report(waveform_extractor=we, output_folder='export_full')
```

**Comment by yger** [comment]
Ok then I'll give it a try. Note that in circus 2, the detection parameters needs to be 4 in order to be equivalent to the old behaviour or circus 1 (with a default value of 6). This is because internally, we are computing the median absolute deviation in spike interface and there is a hard coded factor of 0.67...

**Comment by yger** [comment]
More globally, I would recommend giving a chance to circus 2. Still beta, but the publication should arrive soon, and performance should be similar 1and/or slightly better than circus 1 , with a faster run time and easily integrated within spike interface

**Comment by soucyjr** [comment]
Thank you for the insights! And looking foward to reading your spykingcircus2 paper! 

Was wondering if there is something to count the spikes detected per channel (not units) after sorting? Still trying to trouble shoot why I'm not detecting very obvious spikes and having this info may be useful.

**Comment by soucyjr** [comment]
I've attempted to go channel by channel (removing various electrodes), and it seems the spike detector is not able to capture very large spikes. Is there some sort of upper limit that is preventing these from being correctly identified?

**Comment by yger** [comment]
By default, there is nothing that should discard large peaks in SC, except if you have activated the mode weird_treshold in the .params (and this is related to artefacts)

**Comment by yger** [comment]
But wait, the confusion is that while me I'm talking about the peaks, i.e raw detection threshold in the data, it is possible that very large peaks are noisy, thus the templates (i.e. the average over multiple peaks) is not really good, and thus during the fitting step (once SC has built a dictionary of templates and tries to reconstruct the signal as a linear sum of these templates), if the template is too dissimilar to individual spikes, then they are unlabelled. It could also be a sign that the clustering has failed. Therefore, you should look at the templates found by SC, and if none of them match a very regular and nice waveforms often seen in your data, then there might be a problem somewhere in the .parms

**Comment by soucyjr** [comment]
I found that CRM seems to remove some of the datatraces, but I also found that the channel numbers seem to be inconsistent. See test code below:

Any suggestions?

```
act_channels = [432, 372, 164, 168, 324, 124, 316, 132, 152, 156, 416, 356, 
                328, 276, 212, 256, 196, 484, 300, 200, 444, 172, 308, 268, 312, 428, 204, 
                288, 236, 116, 504, 16, 228, 264, 500, 216, 492, 284, 240, 140, 296, 280, 244]
act_channels = [str(a) for a in act_channels]

act_recording = recording.channel_slice(act_channels)
act_recording_f = spre.bandpass_filter(act_recording, freq_min=300, freq_max=3000)
act_recording_crm = spre.common_reference(act_recording_f, reference='global', operator='median')
```

```
view_channels = [164,444,484]
view_channels = [str(a) for a in view_channels]
datatrace_filter = sw.plot_traces(act_recording_f, time_range=(0, 5),mode="line", show_channel_ids=True, channel_ids=view_channels)
```
<img width="566" alt="image" src="https://github.com/spyking-circus/spyking-circus/assets/158186080/2bb76832-018b-4a68-b5e4-8a48981061cb">



```
view_channels = [444,484,164]
view_channels = [str(a) for a in view_channels]
datatrace_filter = sw.plot_traces(act_recording_f, time_range=(0, 5),mode="line", show_channel_ids=True, channel_ids=view_channels)
```
<img width="566" alt="image" src="https://github.com/spyking-circus/spyking-circus/assets/158186080/912a08a5-d0bb-4cb7-a1f1-76e99a371b27">



```
view_channels = [444,484,164]
view_channels = [str(a) for a in view_channels]
datatrace_filter = sw.plot_traces(act_recording_crm, time_range=(0, 5),mode="line", show_channel_ids=True, channel_ids=view_channels)
```

<img width="566" alt="image" src="https://github.com/spyking-circus/spyking-circus/assets/158186080/9a62b647-74e6-4c79-86eb-303342dfa93e">

**Comment by soucyjr** [comment]
Solved it!!! Takes a bit over 10min to run for my 5min recording, but seems like everything is perfect now!

I just had to change the order of operations, so that selecting the channels is done after filtering/crm. Thank you for all your help!

```
#channel_ids = recording.channel_ids
recording_f = spre.bandpass_filter(recording, freq_min=300, freq_max=3000,dtype="float32")
recording_crm = spre.common_reference(recording_f, reference='global', operator='median')

act_channels = [432, 372, 164, 168, 324, 124, 316, 132, 152, 156, 416, 356, 
                328, 276, 212, 256, 196, 484, 300, 200, 444, 172, 308, 268, 312, 428, 204, 
                288, 236, 116, 504, 16, 228, 264, 500, 216, 492, 284, 240, 140, 296, 280, 244]
act_channels = [str(a) for a in act_channels]

recording_act = recording_crm.channel_slice(act_channels)

```
<img width="1306" alt="image" src="https://github.com/spyking-circus/spyking-circus/assets/158186080/ec0c51a8-ee8b-4600-8950-929d589ad9e5">

![image](https://github.com/spyking-circus/spyking-circus/assets/158186080/e70e3fce-6325-420c-84bb-bc5c7f215708)
