### ISSUE TITLE
Help using spyking-circus with MaxwellTwo

### ISSUE THREAD

**Issue by sofiapuvogelvittini** [spyking-circus/spyking-circus#394]
Hello, and thank you for providing this excellent software.

I would greatly appreciate your assistance in configuring it to work with my MaxwellTwo data. When attempting to run spyking-circus, I encounter an issue indicating that my data is corrupted. However, I can visualize the data in MATLAB using Maxwell functions without any problems. I have tested this with different recordings, and the same error persists:

"Code was interrupted while filtering. Data is likely to be corrupted. Please recopy raw data..." (attached screenshot).

Additionally, there is another error at the end of the output:

"OSError: Can't read data (can't open directory:/home/USER.anaconda3/envs/circus2/lib/hdf5/plugin; attached screenshot)."

It appears that the software is attempting to locate hdf5inside the 'lib' folder of my environment, but that folder is not present there. Despite this, hdf5 is installed in the specified environment (attached picture of all packages in my circus2 environment).

Do you have any insights into what might be causing this issue? Can I provide you my raw data so you can have a look at it?
Thank you very very much
[Errors.pdf](https://github.com/spyking-circus/spyking-circus/files/14463342/Errors.pdf)

**Comment by yger** [comment]
Maybe you can try to see if you can load the data via spikeinterface https://github.com/SpikeInterface/spikeinterface ? If so, then maybe either you save them to disk as raw binary (and then launch SC), either you launch SC from spikeinterface (using si.run_sorter("spykingcircus', ...)), either you try SC2, now part of spikeinterface

**Comment by sofiapuvogelvittini** [comment]
Thanks yger!
After a fix introduced by spikeinterface and neo developers: https://github.com/NeuralEnsemble/python-neo/pull/1444#discussion_r1536663783, I can load the MaxTwo data.
