### ISSUE TITLE
Cannot delete temporary files during clustering

### ISSUE THREAD

**Issue by paolodeluna** [spyking-circus/spyking-circus#41]
Hi,

While clustering, I sometimes encounter an error due to Windows not being able to delete temporary files created by SpyKING CIRCUS. Here my [.params file](https://github.com/spyking-circus/spyking-circus/files/1308145/params.txt) and below the error message.

Unfortunately, it doesn't happen too often for me to debug the problem, and it doesn't happen consistently on the same data file to suspect a problem with a particular dataset. Did you ever encounter the same problem, or have any suggestions on how to fix it?

Thank you for your time.
Kind regards,
Paolo  
  
  
  

  
  
**The error message:**

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda\envs\dev\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.6.0', 'console_scripts', 'spyking-circus-subtask')()
  File "C:\ProgramData\Anaconda\envs\dev\lib\site-packages\circus\scripts\subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "C:\ProgramData\Anaconda\envs\dev\lib\site-packages\circus\__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "C:\ProgramData\Anaconda\envs\dev\lib\site-packages\circus\clustering.py", line 996, in main
    merged1 = algo.merging_cc(params, nb_cpu=nb_cpu, nb_gpu=nb_gpu, use_gpu=use_gpu)
  File "C:\ProgramData\Anaconda\envs\dev\lib\site-packages\circus\shared\algorithms.py", line 429, in merging_cc
    os.remove(filename)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'C:\SC\data.overlap-merging.hdf5'

**My system config:**
Windows 7 x64, 32GB RAM, Intel Xeon E5
python 2.7.13
SpyKING CIRCUS 0.6.0 launched to run on 24 CPUs
The raw-binary .dat file is 3.2GB

**Comment by yger** [comment]
Dear Paolo

If this error is only appearing from times to times, then it is likely to
be because of missing synchronisation barriers between the processes. I'll
have a look, I never encountered this problem.

Just to be sure, is your install compatible with the memory shared option
(highly recommended if you are on a single machine with 24 cores). This
info is displayed in the header when the software is launched.

Best

Pierre

**Comment by paolodeluna** [comment]
Hi Pierre,

Yes, it is (please see below).
Thank you for checking.


##################################################################
#####           Welcome to the SpyKING CIRCUS (0.6.0)        #####
#####                                                        #####
#####              Written by P.Yger and O.Marre             #####
##################################################################


Steps         : whitening, clustering, fitting
GPU detected  : False
Number of CPU : 24/24
Parallel HDF5 : False
Shared memory : True
Hostfile      : C:\Users\delunap\spyking-circus\circus.hosts

##################################################################


-------------------------  Informations  -------------------------
| Number of recorded channels : 4
| Number of analyzed channels : 4
| File format                 : RAW_BINARY
| Data type                   : float32
| Sampling rate               : 40 kHz
| Duration of the recording   : 87 min 17 s 800 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 100 um
| Threshold crossing          : positive
| Waveform alignment          : True
| Matched filters             : False
| Template Extraction         : median-raw
| Overwrite                   : True
| Collect all spikes          : True
| Smart Search                : True
| Smart Selection             : True
------------------------------------------------------------------
Analyzing data to get whitening matrices and thresholds...

**Comment by yger** [comment]
I tried something, let me know if the bug is still seen sometimes
