### ISSUE TITLE
Filename cannot contain spaces in .params file

### ISSUE THREAD

**Issue by paolodeluna** [spyking-circus/spyking-circus#42]
Dear Pierre,

Filenames of probe and exclude files in the params file cannot contain spaces. The line that causes this issue is line 106 in circus/shared/parser.py (version 0.6.0):

`self.parser.set(section, key, value.split('#')[0].replace(' ', '').replace('\t', ''))`

This line strips all whitespaces from the value of any parameter. Could you perhaps add a conditional rule for not doing so for probe and exclude files?

Thank you very much.
Best,
Paolo

**Comment by yger** [comment]
I'll try to see what I can do!

**Comment by yger** [comment]
I made a patch, working on linux, but I won't be able to test that on windows before next week
