### ISSUE TITLE
dead_times doesn't work on unclustered spikes

### ISSUE THREAD

**Issue by paolodeluna** [spyking-circus/spyking-circus#43]
Thank you so much for the option to exclude "dead" periods from the recording in version 0.6.0.

However, I found that clustered spikes (those ending up in result.hdf5/spiketimes/temp_) do respect these boundaries, whereas the unclustered spikes (that is, "garbage") do not (those in gspikes/gelec_). 

For instance, I see that in fitting.main(), the last time `if ignore_dead_times` is checked is on line 277 and applied to get good `local_peaktimes`. But unclustered spikes don't get equally checked before being written to disk (for example, in the `if collect_all:` block on line 483). 
Is that correct?

**Comment by yger** [comment]
Indeed, this is correct, I'll try to fix that. Thanks for spotting these
corner cases.

Best

Pierre
