### ISSUE TITLE
Export only MUA activity

### ISSUE THREAD

**Issue by yger** [spyking-circus/spyking-circus#45]
Sometimes, for quick analysis, we don't need to perform spike sorting. Therefore, it would be good to have the option to simply export MUA, per electrode.

**Comment by yger** [comment]
Done with the thresholding method

**Comment by SaraMati** [comment]
thanks, where can I read the instructions on setting up method as 'theresholding'

**Comment by yger** [comment]
https://spyking-circus.readthedocs.io/en/latest/advanced/mua.html
