### ISSUE TITLE
Compatible with Qt5

### ISSUE THREAD

**Issue by yger** [spyking-circus/spyking-circus#46]
Actually, I don't know if this is already the case, and if not, if this is complicated to add such a support. As Qt5 will become soon the default, maybe it is worth implementing that

**Comment by mstimberg** [comment]
Some class/method names changed between Qt4 and Qt5, so it will most likely not work with Qt5 as it is. I think making it compatible would be easy if we don't care breaking compatibility with Qt4. If we want to keep it compatible with both, we'd have to add a compatibility layer (I think ACQ4 does something like that?).

**Comment by yger** [comment]
Ok, let's say I want it to be compatible with Qt5, is it possible? Qt5 is becoming the default now, so we must follow the trend and get rid of Qt4 support I guess. If you are saying that this is an easy fix :-)

**Comment by yger** [comment]
This has been solved by mstimberg :+1:
