### ISSUE TITLE
Memory leak when using dead_times

### ISSUE THREAD

**Issue by paolodeluna** [spyking-circus/spyking-circus#56]
Dear Pierre, 

I found a memory leak in the functions that use dead_times. The problem is due to appending lists in a for-loop while the function creates the indices of the dead_times. For example, I ran the whitening step on my data (ca. 60 minutes, 3 channels, 11 dead intervals, shared memory = True) on my machine (24 logical CPUs, 32 GB memory, 64bit Windows 7). The code that causes the memory leak in whitening.py is on lines 280-282 (in the [latest version](https://github.com/spyking-circus/spyking-circus/commit/592fad9faf6728226be82a210460e19dbafb5ce5)).

I tried:
- commenting lines 281-282, which leaves the list empty: peak memory usage was 9.23 GB
![no_dead_times](https://user-images.githubusercontent.com/12517451/34716285-a43f749e-f52f-11e7-800c-5fb84171e9d1.PNG)

- your implementation using lists (peak memory usage is > 31.8 GB):
```
all_dead_times = []
for i in xrange(len(dead_times)):
    all_dead_times += range(dead_times[i, 0], dead_times[i, 1])
```
![list](https://user-images.githubusercontent.com/12517451/34716033-f2100216-f52e-11e7-86cb-60696a925d8d.PNG)

- replacing lines 280-282 with a similar numpy implementation (peak memory 18.0 GB):
```
n_samples = dead_times.max()
mask = np.zeros((n_samples + 1, ), dtype=bool)
for i in xrange(len(dead_times)):
    mask[dead_times[i, 0]:dead_times[i, 1]] = 1
all_dead_times = np.where(mask)[0]
```
![numpy](https://user-images.githubusercontent.com/12517451/34716463-4355c4b6-f530-11e7-8692-22a80c20c451.PNG)

- First part of this [SO answer](https://stackoverflow.com/a/4708737) (peak memory usage 15.9 GB):
```
start = dead_times[:, 0]
end = dead_times[:, 1]
all_dead_times = np.r_[tuple(slice(s, e) for s, e in zip(start, end))]
```
![numpy_r](https://user-images.githubusercontent.com/12517451/34716584-91a6f87e-f530-11e7-8a11-f74cb66dcc05.PNG)

- Second part of the same SO answer (peak memory usage 11.7 GB):
```
def indices(start, end):
    lens = end - start
    np.cumsum(lens, out=lens)
    i = np.ones(lens[-1], dtype=int)
    i[0] = start[0]
    i[lens[:-1]] += start[1:]
    i[lens[:-1]] -= end[:-1]
    np.cumsum(i, out=i)
    return i
start = dead_times[:, 0]
end = dead_times[:, 1]
all_dead_times = indices(start, end)
```
![indices_fun](https://user-images.githubusercontent.com/12517451/34716694-eaeca3c0-f530-11e7-9000-9dffd119fd74.PNG)

From these tests it seems like the last implementation might be the faster and more memory efficient among those I tried. Would it be possible to replace the original implementation in both whitening and the other functions that use dead_times?

Thanks a lot.

**Comment by yger** [comment]
Sure, thanks for spotting that. I'm not really using this dead_times feature, so any optimizations is welcome. I'll give it a look and implement your suggestions

**Comment by yger** [comment]
This has been tested and implemented

**Comment by paolodeluna** [comment]
Thank you. Although I'm not very familiar with the MPI, my understanding is that this operation, like others might be, is performed by each node. However, each node has to work independently to produce exactly the same result in the whitening function as well as any other function. Do you think it would be better to write these arrays to disk, so that you create them once and then each node can memory-map that array and use it with minimal memory consumption?

**Comment by yger** [comment]
Indeed, currently every node will generate a duplicate array for the dead times. Are these array really big for you? I mean do need to exclude large portions of your recordings? If so, several options:
- we can optimize: I just implemented dead_times as the most naive way of doing so, but clearly, maybe this array is not even needed. Of course, this would slow everything a bit, but each time a buffer of data is loaded and processed, we could check what is the intersection of its current time with the dead times intervals that we do have in the text file. This might be slightly slower in general, but we'll get rid of this array.
- we can write it to disk, as you are saying, and memap it
- we can create a shared memory structure with MPI, such that processes on the same machine share the same array in memory. However, this solution will not work if the code is launched on several machines

**Comment by paolodeluna** [comment]
Thank you for your reply.

Not only these dead_times, but more generally I wanted to point out that other operations might be redundant and each node would have to do the same as other nodes, which diminishes the usefulness of having parallel workers in the first place. This is not to criticize your work, because redundant operations in parallel loops are a common problem. Regarding your solutions, my opinion is:

1) Repeatedly finding the intersection of two intervals leads us back to square one, where the same computation is performed over and over again with no added benefit. This would slow the algorithm AND increase the memory usage, which I believe is the scarcest resource compared to computing power.

2) Writing the array to disk is a good solution in principle. Also, it would be quite small (good reading speed) compared to the data file. The drawback of this procedure is that because Spyking Circus' steps are quite stand-alone, each module would have to create the file in case it doesn't exist. Or perhaps, the launcher routine could do that once and for all the modules.

3) I don't know how many users distribute the code to different machines. Apart from starting a poll among users, if you want to keep this option available, shared memory is not a viable solution. By the way, I don't know enough about GPUs to tell whether this would work on graphic cards.


--- 
In my particular case, my recordings are up to 2 hours long, up to 32 channels, at 40 kHz. The "dead intervals" are a good feature for the workflow of my lab, because we can discard mechanical or electrical artifacts. The recording I described in the first post was a particularly noisy one: the all_dead_times array was 35 million samples long (25% of the recording). For your information, when written to disk in binary format it occupied 135 MB vs. 1.6 GB for the data file (about 8%).

Having said this, an ideal solution (for me) would be to store the data array in another format, like a pytables chunked-array object (stored in a .hdf5 file), where each data sample would be stored beside a flag to mark its validity and its chunk index, like so:
```
sample     chunk_index    dead?
  x0            0         True
  x1            0         False
  x2            0         False
  x3            1         False
  x4            1         True
  ...
```
In this way, one would assign the chunk_index once, and then very quickly search for the good samples of chunk 0, for example. Probably not ideal, but just brainstorming! Another solution, which is not currently supported in numpy AFAIK, would be to store and memmap a numpy masked array!

**Comment by yger** [comment]
Thanks a lot for your comment! Indeed, with MPI, some operations are redundant, but those operations are not the main bottleneck of the algorithm. The key point is that, for loading chunks, all processes are loading different chunks during all steps of the algorithms such that the load is distributed among workers. Of course, here and there, local computations may be redundant, such as for example the initialization of the array of all times that need to be ignored. But I really don't think this is the main bottleneck. 

Regarding the dead_times, I will try to brainstorm it a bit and come up with a solution (maybe a shared array written to disk, as you are suggesting). In fact, in our case, we mostly implemented such a feature to ignore here and there some small part of the data. This is why in my mind, the dead_times array was not that big. However, I understand that for your workflow, it may be more problematic.

Note that despite the fact that this "dead_times" feature is convenient, checking if a portion of a chunk is valid or not (and this is why the Pytable solution you are proposing is too simple, as a chunk can be only partially dead) will always slow down the algorithm a little. If really you have large portions of your recording that you want to discard, maybe the best is to split your signals into "good" sub portions, and process them as a single file with the multi-files mode of the software, virtually concatenating all of them.

**Comment by paolodeluna** [comment]
Thank you for taking time to work on this minor issue. I agree with you on small redundant operations not being a bottleneck of the algorithm, and the lookup table I mentioned would probably be one!

Regarding your last point, in the past year I first adopted the solution of cutting-and-stitching parts of the recording, as well as the multi-files feature. However, I kept wondering what happened during processes like filtering and "whitening", which might not behave well with discontinuities in the signal. That is why I was very happy when you recently introduced the option to mask putative spikes in the middle of the algorithm, rather than masking / cutting the signal itself.

**Comment by yger** [comment]
I've implemented a shared memory array for dead times. Could you test and tell me if you see a decrease in the memory usage (assuming you do have an MPI version compatible with Shared Memory ?). In theory, it should reduce the memory usage, as all processes on a local machine will read the same array, computed only once (by master node)

**Comment by paolodeluna** [comment]
Thank you so much for working on this. I did a few tests, hoping they help.

Unfortunately, I don't see any improvement over the commit [6ae9484](https://github.com/spyking-circus/spyking-circus/commit/6ae9484bd490f7c978d79439d452e6820b0a6077) (which added the function `indices_for_dead_times()`). 

Just for clarity, After updating to the commit [6a24b6f](https://github.com/spyking-circus/spyking-circus/commit/6a24b6f036fc3039cd37e2540779e15e09990869), I added a print command in circus/shared/files.py around lines 163 (in the new `get_dead_times()` function) to show whether my machine passed `if not SHARED_MEMORY:` (line 163), which it doesn't, continuing in the `else` block. There, I printed when a node was computing dead times, and the message was printed only once, confirming that only the master node reached and executed the nested function `_get_dead_times()`. So, everything should work as expected.

---
Below is the screenshot of memory consumption running the whitening step on the same file of the first post. The first memory spike is at around 28 GB. Every time the memory went down, I could see a 20% increase in the progress from the console (in fact, there are 5 hills in the memory profile).

![shared_memory](https://user-images.githubusercontent.com/12517451/35032017-a25b323a-fb65-11e7-81dd-8b28126cd91a.PNG)

--- 

To make sure the problem did not depend on ckunk_size in the params file, the screenshot above reads 60s chunks and the one below 1s chunks.

![shared_memory2](https://user-images.githubusercontent.com/12517451/35032550-8af25414-fb67-11e7-9e00-9d90000a694a.PNG)

---

Also, to be sure that it wasn't related to anything weird about today (!), I ran the whitening step with 60s chunks on the same file once more, but checking out (going in "detached HEAD" state) at the commit [6ae9484](https://github.com/spyking-circus/spyking-circus/commit/6ae9484bd490f7c978d79439d452e6820b0a6077) (which added the function `indices_for_dead_times()`). Here the result: faster and less memory-intensive!

![detached_head](https://user-images.githubusercontent.com/12517451/35032972-3fa93afc-fb69-11e7-9015-483089078624.PNG)

**Comment by yger** [comment]
I'm not sure to fully understand. So your conclusion is that it used to be faster and less memory-intensive before the shared array mechanism? I'll have a look, and otherwise, I'll remove this feature. Note that I also made some modifications elsewhere, in the way this array is used to select the appropriate times (I used to have sets(), and I switch to a pure numpy based solution with in1d  (see L368 in whitening.py for example). I naively assumed it would be faster, but this could be the reason why you see a speed difference (as the construction of the array themselves should really be negligible)

**Comment by paolodeluna** [comment]
Yes, **from my tests** it is faster without the shared array mechanism!

I saw the new numpy implementation you've added. As you can see from the last test in my first post and the last test in my previous post, speed and memory footprint are very similar. In any case, a pure-type implementation is surely better because it doesn't involve type conversions between list, set and numpy-array as it would do before.

**Comment by yger** [comment]
Ok, I'll try to reproduce the problem with a larger dataset, and come up with a proper answer to speed up your use-case.

**Comment by yger** [comment]
Ok, it seems the leak is in the in1d function, for reasons that I'm not understanding yet. So I just commited a patch that will bring back the selection of the local_peaktimes as they were, keeping also the shared array mechanism. This should be the best solution for the moment, the memory usage you were observing in latest commits were not due to the shared array (this is working fine), but rather to this new numpy.1d function

**Comment by paolodeluna** [comment]
Now I get the following error:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\spyking_circus_env2\Scripts\spyking-circus-subtask-script.py", line 11, in <module>
    load_entry_point('spyking-circus==0.6.3', 'console_scripts', 'spyking-circus-subtask')()
  File "C:\ProgramData\Anaconda2\envs\spyking_circus_env2\lib\site-packages\spyking_circus-0.6.3-py2.7.egg\circus\scripts\subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "C:\ProgramData\Anaconda2\envs\spyking_circus_env2\lib\site-packages\spyking_circus-0.6.3-py2.7.egg\circus\__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "C:\ProgramData\Anaconda2\envs\spyking_circus_env2\lib\site-packages\spyking_circus-0.6.3-py2.7.egg\circus\whitening.py", line 374, in main
    all_times       = numpy.zeros((N_e, diff_times+1), dtype=numpy.bool)
ValueError: negative dimensions are not allowed
```

I don't understand why, but I think there is a missing `sort()` call missing after it computes the set difference, because the output is unsorted. Is it true?

**Comment by yger** [comment]
Indeed, sort are missing, you are right :-(

2018-01-17 11:57 GMT+01:00 paolodeluna <notifications@github.com>:

**Comment by paolodeluna** [comment]
No problem :)

---
Below the results of the same recording, again. It is a little slower, but memory efficient, which means that the issue is resolved for me. 

![capture2](https://user-images.githubusercontent.com/12517451/35040291-d0b2f8a0-fb80-11e7-9941-f0a689111848.PNG)

**Comment by yger** [comment]
Just to let you know, also, in last commits (so in 0.6.4, git master branch), I've pushed changes that should drastically speed the software when using dead_times. Hope it will do something for you too

**Comment by paolodeluna** [comment]
Great! Thank you. I'll test and let you know if I notice anything wrong.
