### ISSUE TITLE
Tests failing on AppVeyor

### ISSUE THREAD

**Issue by yger** [spyking-circus/spyking-circus#57]
Tests for last commits are failing on AppVeyor, with a weird error message. Should we worry or is it a problem of the platform itself, or our integration script? Note that not all python versions are crashing..

**Comment by mstimberg** [comment]
Yea, it's an annoying issue. I don't completely understand it, but there seems to be a problem when Anaconda's `conda` version is downgraded to the version available in conda-forge. For Brian, I worked around this issue by pinning the conda version to the one that is pre-installed on appveyor, so no up-/downgrading takes place. I'll try to apply the same workaround here (it's only a change to `appveyor.yml`, so I'll directly push to master, right?).

**Comment by yger** [comment]
Yes, feel free to do whatever you want in master



2018-01-10 16:57 GMT+01:00 Marcel Stimberg <notifications@github.com>:

**Comment by mstimberg** [comment]
> Yes, feel free to do whatever you want in master

That's a dangerous thing to say :grin:

**Comment by mstimberg** [comment]
It seems to have worked, tests are no longer failing.
