### ISSUE TITLE
circus.shared is broken on Python 3

### ISSUE THREAD

**Issue by QuLogic** [spyking-circus/spyking-circus#60]
I see that Travis and AppVeyor test out Python 3 and the FAQ claims Python 3 support, but it seems that `circus.shared` is not really tested as it contains many bits of Python 2 specific code.

For example, `circus/shared/__init__.py` uses:
```python
import files
import parser
import algorithms
import plot
import utils
```
These relative imports don't work any more and must be made absolute.

There's also imports of `cPickle` in many places.

cc @SaraMahallati

**Comment by yger** [comment]
Dear Sara

Indeed, the code is written for python 2, but it is compatible with python
3 when installed (using the 2to3 converter). So despite the fact that
individual files in the source branch may not comply with python 3 syntax,
everything should work properly.

Do you have trouble running it ?

Best

Pierre

**Comment by SaraMahallati** [comment]
Hi Pierre, 
yes, I'm getting errors.
I installed the package through conda, but I have first forked the repo. does that mean that the installation didn't overwrite it? I fixed those lines manually but I'm getting a new error. probably similar issue. I'll email you the last one. 
Do you recommend a new installation? 
Sara

**Comment by QuLogic** [comment]
Ah, sorry, I completely forgot about 2to3 because it's a very outdated method of providing support for both versions. It's not even mentioned in the [Python 3 porting guide](https://docs.python.org/3/howto/pyporting.html) any more. I'd recommend using `futurize` to convert to a shared codebase. It is much easier to work with a shared codebase since you don't need to run that 2to3 conversion on every install.

**Comment by yger** [comment]
Dear Elliott

Thanks again for the hint. We are currently working on a real-time
rewriting of the software, to perform sorting online and on the fly, and
this is currently our main priority. This code will be more pythonic,
object oriented and python3 compatible. It should be available as a beta
soon.

But as soon as this will be done, we should clearly refactor a bit the
offline version, as 2to3 is indeed not the best solution

Pierre
