### ISSUE TITLE
cudamat.cudamat.CUDAMatException: CUBLAS error.

### ISSUE THREAD

**Issue by catubc** [spyking-circus/spyking-circus#61]
I was previously using CPU only and it seemed to get passed whitening step. Now with GPU version installed I get error below. 

Is it a matter of lowering batch/GPU ram?  I only have a 1050TI video card, which usually only has about 3GB of free video memory.

**********************************************************************************

cat@catlab:~/Downloads/spyking-circus-master$ spyking-circus ~/2017-04-25-0/spyking_circus/data.dat -c 16 -g 1
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

##################################################################
##################################################################

Steps         : filtering, whitening, clustering, fitting
GPU detected  : True
Number of CPU : 16/32
Number of GPU : 1
Parallel HDF5 : False
Shared memory : True
Hostfile      : /home/cat/spyking-circus/circus.hosts

##################################################################

-------------------------  Informations  -------------------------
| Number of recorded channels : 512
| Number of analyzed channels : 512
| File format                 : RAW_BINARY
| Data type                   : int16
| Sampling rate               : 20 kHz
| Duration of the recording   : 60 min 20 s 0 ms
| Width of the templates      : 3 ms
| Spatial radius considered   : 70 um
| Threshold crossing          : negative
| Waveform alignment          : True
| Matched filters             : False
| Template Extraction         : median-raw
| Overwrite                   : True
| Collect all spikes          : False
| Smart Search                : False
| Smart Selection             : False
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Smart Search could be activated for long recordings
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Large number of electrodes, reducing chunk sizes to 10s
------------------------------------------------------------------
-------------------------  Informations  -------------------------
| Filtering has already been done
------------------------------------------------------------------
Analyzing data to get whitening matrices and thresholds...
Found 0.01165s without spikes for whitening matrices...
-------------------------  Informations  -------------------------
| Disabling spatial whitening because of NaNs found
------------------------------------------------------------------
Because of whitening, need to recompute the thresholds...
Traceback (most recent call last):
  File "/usr/local/bin/spyking-circus-subtask", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/circus/scripts/subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "/usr/local/lib/python3.5/dist-packages/circus/__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "/usr/local/lib/python3.5/dist-packages/circus/whitening.py", line 225, in main
    local_chunk = cmt.CUDAMatrix(local_chunk, copy_on_host=False)
  File "/usr/local/lib/python3.5/dist-packages/cudamat/cudamat.py", line 268, in __init__
    raise generate_exception(err_code)
cudamat.cudamat.CUDAMatException: CUBLAS error.

**Comment by yger** [comment]
I'll have a look. However, I would recommend not to use the GPU support in
latest releases. It has been somehow left aside because performance could
be rather good with several CPU cores, so this is on our to-do list to
improve it again.
We are currently rewriting dedicated opencl kernels for the online version
of the software, and they might be implemented for the offline version as
soon as they are finished and tested

Best

Pierre

**Comment by catubc** [comment]
Ok thanks, will do for now.
