### ISSUE TITLE
Import MPI broken on windows with mpi4py 3.0

### ISSUE THREAD

**Issue by CowanCS1** [spyking-circus/spyking-circus#62]
After updating spyking-circus I ran into a failed DLL load on two windows machines with previously working configurations. The call was line 2 of circus' mpi.py, 

`from mpi4py import MPI`

The import also failed directly in python (Anaconda 2.7, windows 7, msmpi 6.0 installed/tested independently/appropriately pathed). 

Oddly, the problem was fixed by attempting to downgrade to mpi4py with

`pip install -Iv mpi4py==2.0.0`

which gave a weird result - appears to download and install a 2.0.0 copy, but the installation reports as being 3.0.0

`  Downloading mpi4py-2.0.0-cp27-none-win_amd64.whl (385kB)
  Downloading from URL https://pypi.python.org/packages/15/51/6bf7a00ba213768ce9447e1f27fd80786d5f752cf15019d838390983f236/mpi4py-2.0.0-cp27-none-win_amd64.whl#md5=bc03f2cb1b270634a19f767d0a77514b (fr
om https://pypi.python.org/simple/mpi4py/)
    98% |############################### | 378kB 1.7MB/s eta 0:00:01  Updating cache with response from "https://pypi.python.org/packages/15/51/6bf7a00ba213768ce9447e1f27fd80786d5f752cf15019d838390983
f236/mpi4py-2.0.0-cp27-none-win_amd64.whl"
  Caching due to etag
    100% |################################| 389kB 853kB/s
Installing collected packages: mpi4py

Successfully installed mpi4py-3.0.0`

and now

`(C:\Users\mouse\Anaconda2) C:\Users\mouse>pip show mpi4py
Name: mpi4py
Version: 3.0.0`

Regardless, the problem and solution were both reproducible locally on the two somewhat distinct rigs. The issue appears to be resolved for me locally, but only with a manual downgrade attempt.

**Comment by yger** [comment]
Thanks a lot for the bug report. We'll investigate, as the code is working fine with mpi4py 3.0.0 on Linux, I see no reasons why it shouldn't on Windows. My bet is that there is currently a packaging bug with mpi4py and pip, but I'll try to see if I can reproduce it

**Comment by yger** [comment]
Actually, I just had a look and the reason why you see that is that because there are no "python wheels" for mpi4py 3.0.0, so you must have a valid compiler Visual C++ if you want to install it with pip. Otherwise, you should use conda, but then only 2.0.0 is pre-compiled. 

If you run the command

>>pip install -Iv mpi4py==2.0.0

you should see error messages such as

error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools
