### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by leeccj** [spyking-circus/spyking-circus#89]
Dear Dr. Yger,

I've got an error after update, 0.7.0 version. I couldn't figure out what causes the error. I tried running with many different parameters, but the result was the same. so.. I am just copying and pasting the message below.. The error comes out in the middle of "Searching random spikes to sample amplitudes ....".

The thing is, when using previous version (0.6.7), it run properly without any issues (with exactly same data and same parameters). 

In addition, the error happens for some of my data; interestingly, it runs properly on some other data (parameters & probe are all the same). The data I am referring are from the same experimental design. 

I don't wanna go back to previous version because I like the new version fixing some bugs that I was struggling with. 

Below is the error message I got.
==================================================

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\spyking-circus-subtask.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\circus\scripts\subtask.py", line 43, in main
    circus.launch(task, filename, nb_cpu, nb_gpu, use_gpu)
  File "c:\programdata\anaconda3\lib\site-packages\circus\__init__.py", line 21, in launch
    module.main(params, nb_cpu, nb_gpu, use_gpu)
  File "c:\programdata\anaconda3\lib\site-packages\circus\clustering.py", line 415, in main
    f        = scipy.interpolate.RectBivariateSpline(xdata, ydata, zdata, s=zdata.size*mads[elec]**2, kx=3, ky=1)
  File "c:\programdata\anaconda3\lib\site-packages\scipy\interpolate\fitpack2.py", line 1180, in __init__
    raise ValueError(msg)
ValueError:
the maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached:
s too small.
Weighted sum of squared residuals does not satisfy abs(fp-s)/s < tol.

**Comment by yger** [comment]
Sure, let me have a quick look. The error seems to be related to the
bicubic spline interpolation that I slightly changed in 0.7.0, to smooth
more accurately the waveforms while interpolating. I'll come back to you
quickly (and meanwhile, you can avoid such an error by setting the
alignment parameter to False in the [detection] section)

**Comment by yger** [comment]
I just pushed a patch in the master branch (0.7.1). Can you install it with
git (if you know how to do), and test if this is solving your problem?
Meanwhile, I would be interested to get a portion of your data able to
trigger the problem, if you are willing to share it
