### ISSUE TITLE
Data Type Offset for uint16

### ISSUE THREAD

**Issue by BeaMCC** [spyking-circus/spyking-circus#91]
Dear all,

I am a new user of Spyking Circus (and Python as well). I have therefore a very little experience. 

I have problems in identifying the correct padding for my data. My data files are raw binary, uint16. I can normally open them in Matlab using uint16 with the ieee-le option.

In Spyking Circus if I use the auto parameter for the data type offset I get all my signals flat, so they are not correctly imported. Could you please help me to understand how to compute the correct data type offset for my data set?

Thank you in advance.

**Comment by yger** [comment]
Can I close the ticket? Did you managed to view the data?

**Comment by BeaMCC** [comment]
Hallo, no at the moment I did not solve the issue. I tried several random numbers until I found one that was giving acceptable results, but I am not sure if the data are correctly processed. Do you have any suggestion?

Thanks in advance.

**Comment by yger** [comment]
Can you send me a small example of your data, if you have any?

**Comment by BeaMCC** [comment]
Sure, thanks a lot! I have only initial recordings but they should be enough. How can I share them with you privately?

Thanks again

> Il giorno 06 nov 2018, alle ore 14:56, Pierre Yger <notifications@github.com> ha scritto:
> 
> Can you send me a small example of your data, if you have any?
>

**Comment by yger** [comment]
Just send me a Dropbox/Google drive (with the .params and the .prb)

**Comment by yger** [comment]
any update on this issue? Can I close it?
