### ISSUE TITLE
Install from sources in windows

### ISSUE THREAD

**Issue by Tom-TBT** [spyking-circus/spyking-circus#92]
Hello,
I've tried to install from sources in windows 10 with Anaconda3.
I created an env with python=3.5, activated it.

Then:
conda install mpi4py
In the cloned folder -> pip install .

After that trying to start the GUI does a silent crash. I installed pyqt 4 like this:
conda install pyqt=4

Now this seems to work for me. I think you should add this to the dependency. 

I'm testing the version 7.0 with new data I have. I might open multiple issues these days. Thanks for your work!

Bests,
Tom Boissonnet

**Comment by yger** [comment]
Thanks for the feedback. In fact, SpyKING CIRCUS should work with pyqt 4 or 5, and in theory it is installed by default in a conda environment. But we'll try to reproduce the error and enhance the packaging

**Comment by yger** [comment]
I added the dependency, thanks for spotting that
